import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function fixture(){let clock=20000,id=0;const timers=new Map(),storage=new Map(),nodes=[];class Node{constructor(){this.children=[];this.handlers={};this.style={setProperty(){}};this.classList={add(){}};this.offsetWidth=286;this.offsetHeight=90;this.attrs={};}append(...n){this.children.push(...n);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.handlers[k]=f;}contains(n){return this===n||this.children.includes(n);}getBoundingClientRect(){return {left:150,top:40,bottom:84};}querySelector(){return this.children[0];}focus(){}remove(){this.removed=true;}}
const trigger=new Node(),body=new Node(),document={body,hidden:false,querySelector:()=>trigger,createElement:()=>{const n=new Node();nodes.push(n);return n;},createTextNode:s=>s,addEventListener(){}};const window={addEventListener(){}};const ctx={document,window,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},Date:{now:()=>clock},crypto:{randomUUID:()=>String(++id)},innerWidth:390,innerHeight:800,matchMedia:()=>({matches:true}),navigator:{},setTimeout:(fn,ms)=>{const key=++id;timers.set(key,{fn,ms});return key;},clearTimeout:key=>timers.delete(key)};vm.runInNewContext(readFileSync(new URL('../public/buzz.js',import.meta.url),'utf8'),ctx);const calls=[];const app=readFileSync(new URL('../public/app.js',import.meta.url),'utf8');Object.assign(ctx,{info(){},api:async(path,data)=>{calls.push(data);return {event:{...data,from:'Mahmoud',at:clock,to:'Safy'}};},command(){},sync(){},goto(){}});vm.runInNewContext(app.slice(app.indexOf('window.OurComfort?.init('),app.indexOf('sync().then(connect)')),ctx);window.OurBuzz.sync({who:'Mahmoud'});return {body,document,buzz:window.OurBuzz,trigger,picker:nodes[0],calls,timers,storage,advance:()=>clock+=11000};}
test('quick tap sends default; 450ms hold opens without sending; selected effect persists per account',async()=>{const f=fixture();await f.trigger.onclick();await Promise.resolve();assert.equal(f.calls[0].kind,'electric');f.advance();f.trigger.handlers.pointerdown({button:0,clientX:0,clientY:0});const hold=[...f.timers.values()].find(t=>t.ms===450);assert.ok(hold);hold.fn();f.trigger.handlers.pointerup();await f.trigger.onclick();assert.equal(f.calls.length,1);assert.equal(f.picker.hidden,false);await f.picker.children[4].onclick();assert.equal(f.calls.at(-1).kind,'need');assert.equal(f.trigger.textContent,'🔔');f.buzz.reset();f.buzz.sync({who:'Mahmoud'});assert.equal(f.trigger.textContent,'🔔');f.buzz.reset();f.buzz.sync({who:'Safy'});assert.equal(f.trigger.textContent,'⚡');});
test('drag cancels press and quick send',()=>{const f=fixture();f.trigger.handlers.pointerdown({button:0,clientX:0,clientY:0});f.trigger.handlers.pointermove({clientX:20,clientY:0});f.trigger.handlers.pointerup();f.trigger.onclick();assert.equal(f.calls.length,0);assert.equal(f.timers.size,0);});

test('both participants show effects, newest replaces immediately and old snapshots do not replay',()=>{const f=fixture(),first={id:'one',from:'Mahmoud',to:'Safy',kind:'love',at:20000,sequence:1},next={...first,id:'two',kind:'kiss',sequence:2};f.buzz.receive(first);const original=f.body.children.at(-1);assert.equal(original.attrs['aria-label'],'Love from Mahmoud');f.buzz.receive(next);assert.equal(original.removed,true);const latest=f.body.children.at(-1);assert.equal(latest.attrs['aria-label'],'Kiss from Mahmoud');const count=f.body.children.length;f.buzz.receive(first);f.buzz.receive(next);assert.equal(f.body.children.length,count);f.buzz.reset();f.buzz.sync({who:'Safy',pendingBuzz:next});assert.equal(f.body.children.at(-1).attrs['aria-label'],'Kiss from Mahmoud');const n=f.body.children.length;f.buzz.reset();f.buzz.sync({who:'Safy',pendingBuzz:next});assert.equal(f.body.children.length,n);});
test('rapid sends are accepted without waiting for prior requests',async()=>{const f=fixture();await Promise.all([f.trigger.onclick(),f.trigger.onclick(),f.trigger.onclick()]);assert.equal(f.calls.length,3);});

test('sad and missing-you choices send, render distinct artwork and remember the last selection',async()=>{
 const f=fixture();
 for(const [index,kind,icon,artClass]of [[5,'sad','😔','buzz-tear'],[6,'miss','🥺','buzz-held-heart']]){
  await f.picker.children[index].onclick();assert.equal(f.calls.at(-1).kind,kind);assert.equal(f.trigger.textContent,icon);
  const overlay=f.body.children.at(-1);assert.equal(overlay.className,'buzz-overlay buzz-'+kind);assert.match(overlay.children[0].innerHTML,new RegExp(artClass));
 }
 f.buzz.reset();f.buzz.sync({who:'Mahmoud'});assert.equal(f.trigger.textContent,'🥺');
 await f.trigger.onclick();assert.equal(f.calls.at(-1).kind,'miss');
});
