import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../public/chat-tools.js',import.meta.url),'utf8');
function harness(api=async()=>({total:0,matches:[]})){
 const nodes=new Map(),timers=new Map();let serial=0,restored=0;const classes=()=>{const set=new Set();return {add:x=>set.add(x),remove:x=>set.delete(x),toggle(x,value){value?set.add(x):set.delete(x);},contains:x=>set.has(x)};};
 const get=id=>{if(!nodes.has(id))nodes.set(id,{id,hidden:false,textContent:'',value:'',children:[],classList:classes(),setAttribute(){},removeAttribute(){},append(){},focus(){},blur(){}});return nodes.get(id);};
 const document={getElementById:get,querySelector:()=>get('room-tools'),querySelectorAll:()=>[]};
 const ctx=vm.createContext({window:{},document,Date,setTimeout(fn,ms){timers.set(++serial,{fn,ms});return serial;},clearTimeout(id){timers.delete(id);},PlaceScroll:{capture:()=>({id:'reading',top:12,end:false}),restore(){restored++;}}});vm.runInContext(source,ctx);
 const inserted=[];ctx.window.OurChatTools.init({api,insert:m=>inserted.push(m),stopReading(){}});
 return {get,timers,tools:ctx.window.OurChatTools,inserted,restored:()=>restored,run(ms){for(const [id,t]of [...timers])if(t.ms===ms){timers.delete(id);t.fn();}}};
}
const tick=()=>new Promise(r=>setImmediate(r));
test('notice lasts three seconds, fades and deduplicates repeated failures',()=>{const h=harness();h.tools.notice('Could not send. Try again.');assert.equal(h.get('notice').classList.contains('visible'),true);assert.equal(h.timers.size,1);h.tools.notice('Could not send. Try again.');assert.equal(h.timers.size,1);h.run(3000);assert.equal(h.get('notice').classList.contains('visible'),false);h.run(180);assert.equal(h.get('notice').textContent,'');});
test('closing search restores reading and prevents late search results from jumping',async()=>{let finish;const h=harness(()=>new Promise(r=>finish=r));h.get('chat-search-open').onclick();h.get('chat-search-query').value='hello';h.get('chat-search-query').oninput();h.run(240);h.tools.close();finish({total:1,matches:[{id:'old'}]});await tick();assert.equal(h.inserted.length,0);assert.equal(h.restored(),1);assert.equal(h.get('chat-search').hidden,true);});
test('changing query invalidates an in-flight message load',async()=>{let finish;const h=harness(async path=>path.startsWith('messages/')?new Promise(r=>finish=r):{total:1,matches:[{id:'old'}]});h.get('chat-search-open').onclick();h.get('chat-search-query').value='hello';h.get('chat-search-query').oninput();h.run(240);await tick();h.get('chat-search-query').value='وحشتيني';h.get('chat-search-query').oninput();finish({id:'old'});await tick();assert.equal(h.inserted.length,0);});
test('no matches disables navigation and reset clears feedback',async()=>{const h=harness();h.get('chat-search-open').onclick();h.get('chat-search-query').value='missing';h.get('chat-search-query').oninput();h.run(240);await tick();assert.equal(h.get('chat-search-count').textContent,'No matches');assert.equal(h.get('chat-search-next').disabled,true);h.tools.notice('Could not send.');h.tools.reset();assert.equal(h.get('notice').textContent,'');assert.equal(h.timers.size,0);});
