import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const walk=n=>[n,...n.children.flatMap(walk)];
function fixture(who){class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.className='';this.handlers={};this.classList={add:c=>{this.className+=' '+c;},toggle:(c,on)=>{const s=new Set(this.className.split(' '));(on??!s.has(c))?s.add(c):s.delete(c);this.className=[...s].join(' ');}};}append(n){n.remove();n.parent=this;this.children.push(n);}remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);}replaceChildren(){this.children=[];}querySelectorAll(q){return walk(this).slice(1).filter(n=>n.className.split(' ').includes(q.slice(1)));}querySelector(q){return this.querySelectorAll(q)[0];}setAttribute(k,v){this[k]=v;}addEventListener(k,f){this.handlers[k]=f;}get lastElementChild(){return this.children.at(-1);}}
const feed=new Node('div'),el=(tag,text,parent,cls)=>{const n=new Node(tag);n.textContent=text;n.className=cls||'';parent?.append(n);return n;};const context={state:{who,messages:[],pins:[],personal:{profiles:{Safy:{photo:'safy-photo'},Mahmoud:{photo:'mahmoud-photo'}}}},tab:'chat',older:[],pending:new Map(),activityNodes:new Map(),$:()=>feed,PlaceScroll:{capture:()=>({}),restore(){}},el,btn:(text,parent,fn,cls)=>{const n=el('button',text,parent,cls);n.onclick=fn;return n;},window:{},document:{},Intl,Date,Map,JSON,renderMessageText:(p,m)=>p.textContent=m.text,paintActivity(){},updateLatest(){},openEchoProfile(){}};vm.createContext(context);const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8');vm.runInContext(source.slice(source.indexOf('function messageDate('),source.indexOf('function paintReply(')),context);return {context,feed,paint:()=>context.paintFeed(),walk};}
for(const who of ['Mahmoud','Safy'])test('compact message structure, grouping and last-seen marker for '+who,()=>{const c=fixture(who),other=who==='Mahmoud'?'Safy':'Mahmoud';c.context.state.messages=[{id:'1',author:who,text:'Hey',status:'sent',sequence:1,createdAt:'2026-09-19T08:00:00Z',readAt:'yes'},{id:'2',author:who,text:'How are you?',status:'sent',sequence:2,createdAt:'2026-09-19T08:00:01Z',readAt:'yes'},{id:'3',author:other,text:'Hello',status:'sent',sequence:3,createdAt:'2026-09-19T08:00:02Z'}];c.paint();const rows=c.feed.children.filter(n=>n.dataset.message);assert.equal(rows.length,3);assert.equal(rows[0].querySelector('.bubble').children.length,1);assert.equal(rows[0].querySelector('.bubble').children[0].textContent,'Hey');assert.equal(rows[0].querySelector('.status').hidden,true);assert.match(rows[1].className,/grouped/);const seen=rows[1].querySelector('.read-receipt');assert.equal(seen.title,'Seen by '+other);assert.equal(seen.children[0].src,'/api/photos/'+other.toLowerCase()+'-photo');assert.equal(rows[2].querySelector('.status').hidden,true);assert.notEqual(rows[0].querySelector('.message-actions').parent,rows[0].querySelector('.bubble'));c.paint();assert.equal(c.feed.children.filter(n=>n.dataset.message).length,3);assert.ok(c.feed.children.includes(rows[0]));});
test('delivery and failure remain distinct in the rendered receipt',()=>{const c=fixture('Mahmoud');c.context.state.messages=[{id:'s',author:'Mahmoud',text:'x',status:'sent',sequence:1,createdAt:Date.now(),deliveredAt:'yes'},{id:'f',author:'Mahmoud',text:'failed',status:'failed-local',sequence:2,createdAt:Date.now()}];c.paint();const rows=c.feed.children.filter(n=>n.dataset.message);assert.equal(rows[0].querySelector('.status').title,'Delivered');assert.match(rows[1].querySelector('.status').textContent,/Not sent/);assert.ok(walk(rows[1]).some(n=>n.textContent==='Retry'));});

for(const who of ['Mahmoud','Safy'])test('both authors retain avatars on own, received and consecutive messages: '+who,()=>{
 const c=fixture(who),other=who==='Mahmoud'?'Safy':'Mahmoud';
 c.context.state.messages=[who,who,other,other].map((author,i)=>({id:String(i),author,text:'Hi',status:'sent',sequence:i,createdAt:1760000000000+i*1000}));
 c.paint();
 const rows=c.feed.children.filter(n=>n.dataset.message);
 assert.equal(rows.length,4);
 for(const row of rows){const avatar=row.children.find(n=>n.className==='avatar');assert.ok(avatar,'profile avatar retained for '+row.dataset.author);assert.equal(avatar.textContent,row.dataset.author[0]);assert.equal(avatar.hidden,undefined);assert.equal(row.querySelector('.bubble').children.length,1);}
 const css=readFileSync(new URL('../public/style.css',import.meta.url),'utf8');
 for(const rule of css.matchAll(/([^{}]+)\{([^{}]*)\}/g))if(rule[1].includes('.avatar'))assert.doesNotMatch(rule[2],/visibility\s*:\s*hidden|display\s*:\s*none|opacity\s*:\s*0(?:\D|$)/,'avatar must not be hidden by '+rule[1]);
});

for(const who of ['Mahmoud','Safy'])test('Echo badge is inside its bubble and keeps profile action across text updates: '+who,()=>{
 const c=fixture(who);let opened=0;c.context.openEchoProfile=()=>opened++;
 c.context.state.messages=[{id:'echo',author:'Echo',text:'Hello',status:'streaming',sequence:1,createdAt:1760000000000}];c.paint();
 let row=c.feed.children.find(n=>n.dataset.message==='echo'),bubble=row.querySelector('.bubble'),badge=bubble.querySelector('.echo-inline-badge');
 assert.ok(badge);assert.equal(row.children.some(n=>n.className.split(' ').includes('avatar')),false);assert.equal(bubble.children[0],badge);assert.equal(bubble.children[1].textContent,'Hello');assert.equal(badge['aria-label'],'About Echo');badge.onclick();assert.equal(opened,1);
 c.context.state.messages[0].text='Hello again';c.context.state.messages[0].status='sent';c.paint();row=c.feed.children.find(n=>n.dataset.message==='echo');bubble=row.querySelector('.bubble');assert.ok(bubble.querySelector('.echo-inline-badge'));assert.equal(bubble.children[1].textContent,'Hello again');assert.notEqual(row.querySelector('.message-actions').parent,bubble);assert.ok(walk(row).some(n=>n.textContent==='React'));
});
