import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {initial,change,project} from '../domain.mjs';
import {respond} from '../ai.mjs';
import {attentionEvents} from '../push-events.mjs';
import {PushNotifications} from '../push.mjs';
import {Store} from '../store.mjs';
import {createApp} from '../server.mjs';
const context={window:{}};vm.runInNewContext(readFileSync(new URL('../public/comfort.js',import.meta.url),'utf8'),context);const invitations=context.window.OurComfort.invitations;
for(const who of ['Mahmoud','Safy'])test('all invitations target only recipient '+who,()=>{const owner=who==='Mahmoud'?'Safy':'Mahmoud',s={who,serverNow:10,domino:{shared:{id:'d',owner,status:'waiting',expires:20}},ocho:{shared:{id:'o',owner,status:'waiting',expires:20}},court:{cases:[{id:'c',owner,stage:'invited',pauses:[],round:1}]},draw:{match:{id:'a',owner,status:'invited'}},media:{id:'m',owner,invitation:{id:'i',to:who,expires:20}},raceInvitation:{id:'r',owner}};assert.equal(invitations(s).length,6);assert.equal(invitations({...s,who:owner}).length,0);s.serverNow=30;assert.equal(invitations(s).length,3);});
test('message reactions preserve partner, switch and remove independently',()=>{const s=initial();change(s,'Mahmoud','message.react',{id:'m',value:'😂',who:'Safy'});change(s,'Safy','message.react',{id:'m',value:'❤️'});change(s,'Mahmoud','message.react',{id:'m',value:'👏'});assert.deepEqual(project(s,'Safy').messageReactions.m,{Mahmoud:'👏',Safy:'❤️'});change(s,'Mahmoud','message.react',{id:'m',value:null});assert.deepEqual(s.messageReactions.m,{Safy:'❤️'});assert.throws(()=>change(s,'Mahmoud','message.react',{id:'m',value:'bogus'}));});
for(const [prompt,language] of [['How are you?','English'],['ezayek ya Echo 3amel eh','English'],['إزيك يا إيكو','English'],['رد بالعربي','Arabic'],['Please reply in Arabic','Arabic']])test('Echo current-message language: '+prompt,async()=>{process.env.OPENAI_API_KEY='test-only';await respond({actor:'Safy',prompt,context:'Previous Mahmoud: العربية فقط',onText(){},fetcher:async(_,options)=>{assert.ok(JSON.parse(options.body).instructions.includes('Reply in '+language+'.'));return new Response('data: '+JSON.stringify({type:'response.completed',response:{output:[],usage:{input_tokens:1,output_tokens:1}}})+'\n\n');}});});
for(const who of ['Mahmoud','Safy'])test('mention inbox persists and read status is private: '+who,()=>{const other=who==='Mahmoud'?'Safy':'Mahmoud',store=new Store(':memory:');try{const push=new PushNotifications(store,{secret:'test secret',origin:'https://example.test'}),s=initial();change(s,who,'item.save',{type:'Discussion',title:'Look at this @'+other});const events=attentionEvents(initial(),s,who);assert.equal(events.length,1);assert.equal(events[0].to,other);assert.match(events[0].body,/mentioned you/);push.enqueue(events[0]);push.enqueue(events[0]);assert.equal(push.inbox(other).length,1);const id=push.inbox(other)[0].id;push.readInbox(who,id);assert.equal(push.inbox(other)[0].readAt,null);const reopened=new PushNotifications(store,{secret:'test secret',origin:'https://example.test'});assert.equal(reopened.inbox(other).length,1);reopened.readInbox(other,id);assert.ok(reopened.inbox(other)[0].readAt);assert.equal(reopened.inbox(who).length,0);}finally{store.close();}});
test('HTTP reactions validate messages and update both accounts; inbox read cannot affect partner',async()=>{process.env.MAHMOUD_EMAIL='mahmoud@example.test';process.env.SAFY_EMAIL='safy@example.test';const store=new Store(':memory:'),authFetch=async(url,opts)=>{const name=url.includes('/token?')?JSON.parse(opts.body).email.split('@')[0]:opts.headers.Authorization.split(' ')[1];const user={id:name+'-uid',email:name+'@example.test',email_confirmed_at:'2026-01-01'};return Response.json(url.includes('/token?')?{user,access_token:name,refresh_token:name,expires_in:3600}:user);};const server=createApp({store,origin:'http://localhost',secret:'test secret with over thirty characters',testing:true,authFetch});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,cookies={};const req=async(who,path,data)=>{const r=await fetch(base+'/api/'+path,{method:data?'POST':'GET',headers:{Origin:'http://localhost',Cookie:cookies[who]||'','Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});if(r.headers.get('set-cookie'))cookies[who]=r.headers.get('set-cookie').split(';')[0];return {status:r.status,body:await r.json()};};const cmd=(who,type,data)=>req(who,'command',{id:randomUUID(),type,data});try{for(const who of ['mahmoud','safy'])assert.equal((await req(who,'login',{email:who+'@example.test',password:'test'})).status,200);assert.equal((await cmd('mahmoud','message.react',{id:'missing',value:'❤️'})).status,404);const id=randomUUID();store.message({id,author:'Safy',text:'Hello'});assert.equal((await req('safy','delivered',{ids:[id]})).body.ids.length,0);assert.equal((await req('mahmoud','delivered',{ids:[id]})).body.ids[0],id);const delivered=(await req('safy','state')).body.messages.find(m=>m.id===id);assert.ok(delivered.deliveredAt);assert.equal(delivered.readAt,null);assert.equal((await cmd('mahmoud','message.react',{id,value:'❤️'})).status,200);assert.equal((await req('safy','state')).body.messageReactions[id].Mahmoud,'❤️');await cmd('mahmoud','item.save',{type:'Discussion',title:'Hey @Safy'});const inbox=(await req('safy','state')).body.inbox;assert.equal(inbox.length,1);await req('mahmoud','notifications/seen',{ids:[inbox[0].id]});assert.equal((await req('safy','state')).body.inbox[0].readAt,null);await req('safy','notifications/seen',{ids:[inbox[0].id]});assert.ok((await req('safy','state')).body.inbox[0].readAt);}finally{await new Promise(r=>server.close(r));store.close();}});

test('inbox batch acknowledgement preserves later arrivals, partner inbox, and chat receipts',()=>{
 const store=new Store(':memory:');try{
 const push=new PushNotifications(store,{secret:'test secret',origin:'https://example.test'});
 const add=(key,to)=>push.enqueue({key,to,kind:'wall',body:'Activity',target:{tab:'space'}});
 add('old','Mahmoud');add('partner','Safy');const ids=push.inbox('Mahmoud').map(x=>x.id);add('new','Mahmoud');
 store.message({id:'chat-unread',author:'Safy',text:'Hello',status:'sent'});
 const before=store.db.prepare('SELECT * FROM messages WHERE id=?').get('chat-unread');
 push.seenInbox('Mahmoud',[...ids,'partner']);
 assert.ok(push.inbox('Mahmoud').find(x=>x.id==='old').readAt);
 assert.equal(push.inbox('Mahmoud').find(x=>x.id==='new').readAt,null);
 assert.equal(push.inbox('Safy')[0].readAt,null);
 assert.equal(push.inbox('Mahmoud').length,2);
 assert.deepEqual(store.db.prepare('SELECT * FROM messages WHERE id=?').get('chat-unread'),before);
 assert.throws(()=>push.seenInbox('Mahmoud',['old',null]));
 }finally{store.close();}
});
