import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const walk=n=>[n,...n.children.flatMap(walk)];
function client(response){
 class Node{constructor(tag){this.tag=tag;this.children=[];this.textContent='';this.events={};}append(n){n.parent=this;this.children.push(n);}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}setAttribute(k,v){this[k]=v;}addEventListener(k,f){this.events[k]=f;}showModal(){this.open=true;}}
 const body=new Node('body'),requests=[],blobs=[],revoked=[];const context={document:{body,createElement:t=>new Node(t)},AbortController,Blob,fetch:async(url,options)=>{requests.push({url,options});return response;},URL:{createObjectURL:b=>{blobs.push(b);return 'blob:private-document-'+blobs.length;},revokeObjectURL:u=>revoked.push(u)}};context.window=context;vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/court-export.js',import.meta.url),'utf8'),context);return {ui:context.OurCourtExport,body,requests,blobs,revoked};
}
test('case download fetches inside the active session, then saves a local blob instead of opening the protected endpoint',async()=>{const c=client(new Response('<!doctype html><p>Private case</p>',{headers:{'Content-Type':'text/html; charset=utf-8'}}));await c.ui.open('case-id',7,'download');assert.equal(c.requests[0].options.credentials,'same-origin');assert.equal(c.requests[0].options.cache,'no-store');assert.equal(c.requests[0].url,'/api/court/case-id');const link=walk(c.body).find(n=>n.tag==='a');assert.equal(link.href,'blob:private-document-1');assert.equal(link.download,'court-case-7.html');assert.equal(link.target,undefined);assert.equal(await c.blobs[0].text(),'<!doctype html><p>Private case</p>');c.ui.reset();assert.equal(c.body.children.length,0);assert.deepEqual(c.revoked,['blob:private-document-1']);});
test('expired authentication stays inside the app and cannot create a preview or download',async()=>{const c=client(new Response('{"error":"Please sign in."}',{status:401,headers:{'Content-Type':'application/json'}}));await c.ui.open('case-id',7,'print');const text=walk(c.body).map(n=>n.textContent).join(' ');assert.match(text,/session expired/);assert.ok(!text.includes('{"error"'));assert.ok(!walk(c.body).some(n=>n.tag==='a'||n.tag==='iframe'));assert.equal(c.blobs.length,0);});
test('a failed or non-document response cannot be downloaded as a case file',async()=>{for(const response of [new Response('Error',{status:500}),new Response('{}',{headers:{'Content-Type':'application/json'}})]){const c=client(response);await c.ui.open('case-id',1,'download');assert.equal(c.blobs.length,0);assert.ok(walk(c.body).some(n=>n.tag==='button'&&n.textContent==='Retry'));}});
