import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initial} from '../domain.mjs';
import {courtView,courtCase,courtChange,courtRequest,courtApply} from '../court.mjs';
import {courtDocument} from '../court-document.mjs';
import {judge} from '../court-ai.mjs';
import {Store} from '../store.mjs';
import {createApp} from '../server.mjs';
function setup(){const s=initial(),{id}=courtChange(s,'Mahmoud','court.create',{title:'Plans changed',issue:'Were our arrangements clear?',language:'Arabic'});const c=courtCase(s,id);const act=(who,t,d={})=>courtChange(s,who,'court.'+t,{id,revision:c.revision,...d});return {s,c,id,act};}
function heard(){const h=setup();h.act('Safy','accept');h.act('Mahmoud','statement',{text:'M SEALED'});h.act('Safy','statement',{text:'S SEALED'});return h;}
function ai(h,result){const id=randomUUID();h.c.pending=id;return courtApply(h.s,h.id,id,result);}
function review(h){for(const n of ['Mahmoud','Safy']){ai(h,{kind:'question',target:n,text:'What was agreed?'});h.act(n,'answer',{question:h.c.questions.at(-1).id,text:'We discussed a time but did not confirm it.'});}ai(h,{kind:'review',text:'Both describe an unconfirmed time.',agreed:['A time was discussed'],disputed:['Whether it was final'],missing:['Explicit confirmation']});}
const decision=h=>({kind:'verdict',text:'There is insufficient evidence of a firm commitment.',reasons:['Both accounts distinguish discussion from confirmation.'],agreed:['Discussion occurred'],disputed:['Whether a promise existed'],missing:['Explicit confirmation'],steps:['Confirm plans explicitly next time.'],references:h.c.records.filter(r=>r.kind==='statement').map(r=>r.id)});
test('court statements stay sealed in partner projection and export until both submit',()=>{const h=setup();assert.throws(()=>h.act('Mahmoud','accept'));h.act('Safy','accept');h.act('Mahmoud','statement',{text:'PRIVATE UNTIL BOTH'});assert.ok(!JSON.stringify(courtView(h.s,'Safy')).includes('PRIVATE UNTIL BOTH'));assert.ok(!courtDocument(courtView(h.s,'Safy').cases[0],'Safy').includes('PRIVATE UNTIL BOTH'));assert.throws(()=>courtRequest(h.c),/statements/);h.act('Safy','statement',{text:'Second account'});assert.ok(JSON.stringify(courtView(h.s,'Safy')).includes('PRIVATE UNTIL BOTH'));});
test('question ownership, balanced hearing, factual approval and verdict citation gates',()=>{const h=heard();assert.throws(()=>ai(h,decision(h)),/review/);h.c.pending=null;assert.throws(()=>ai(h,{kind:'review',text:'Premature',agreed:[],disputed:[],missing:[]}),/chance/);h.c.pending=null;ai(h,{kind:'question',target:'Mahmoud',text:'What was agreed?'});assert.throws(()=>h.act('Safy','answer',{question:h.c.questions.at(-1).id,text:'Wrong person'}));h.act('Mahmoud','answer',{question:h.c.questions.at(-1).id,text:'A tentative time'});assert.throws(()=>ai(h,{kind:'question',target:'Mahmoud',text:'Again?'}),/equally/);h.c.pending=null;ai(h,{kind:'question',target:'Safy',text:'How did you understand the plan?'});h.act('Safy','answer',{question:h.c.questions.at(-1).id,text:'Tentative too'});ai(h,{kind:'review',text:'Tentative plans',agreed:['Time discussed'],disputed:[],missing:[]});h.act('Mahmoud','approve');assert.throws(()=>courtRequest(h.c),/step/);h.act('Safy','approve');assert.throws(()=>ai(h,{...decision(h),references:['fabricated']}),/outside/);h.c.pending=null;ai(h,decision(h));assert.equal(h.c.stage,'decided');});
test('pause cancels in-flight output, separate resume permissions, correction resets review',()=>{const h=heard();h.c.pending='old-job';h.act('Mahmoud','pause',{value:true});h.act('Safy','pause',{value:true});assert.equal(courtApply(h.s,h.id,'old-job',{kind:'question',target:'Mahmoud',text:'late'}),false);h.act('Mahmoud','pause',{value:false});assert.throws(()=>courtRequest(h.c),/paused/);h.act('Safy','pause',{value:false});review(h);h.act('Mahmoud','approve');h.act('Safy','correct',{text:'The summary missed a qualification.'});assert.equal(h.c.stage,'investigation');assert.equal(h.c.approvals.length,0);assert.equal(h.c.review,null);});
test('appeal retains original verdict and transcript while requiring new consent and accounts',()=>{const h=heard();review(h);h.act('Mahmoud','approve');h.act('Safy','approve');ai(h,decision(h));const before=structuredClone(h.c.verdict),recordCount=h.c.records.length;h.act('Safy','appeal',{text:'A new confirmation message was found.'});assert.equal(h.c.round,2);assert.equal(h.c.stage,'invited');assert.deepEqual(h.c.history[0].verdict,before);assert.equal(h.c.history[0].records.length,recordCount);assert.equal(h.c.owner,'Safy');assert.throws(()=>courtRequest(h.c),/consent/);h.act('Mahmoud','accept');h.act('Safy','statement',{text:'NEW SECRET'});assert.ok(!JSON.stringify(courtView(h.s,'Mahmoud')).includes('NEW SECRET'));assert.ok(courtDocument(courtView(h.s,'Mahmoud').cases[0],'Mahmoud').includes(before.decision));});
test('export escapes hostile content and preserves Arabic and embedded evidence',()=>{const h=heard();h.act('Mahmoud','evidence',{text:'<img src=x onerror=alert(1)> دليل',image:'photo'});const html=courtDocument(courtView(h.s,'Safy').cases[0],'Safy',{photo:'data:image/png;base64,AAAA'});assert.ok(!html.includes('<img src=x'));assert.ok(html.includes('&lt;img'));assert.ok(html.includes('دليل'));assert.ok(html.includes('data:image/png;base64,AAAA'));});
test('store restart preserves cases and releases interrupted court jobs without paid retry',()=>{const dir=mkdtempSync(join(tmpdir(),'court-')),path=join(dir,'db');let store=new Store(path);const h=heard();h.c.pending='interrupted';store.save(h.s);store.close();store=new Store(path);assert.equal(store.state().court.cases[0].pending,null);assert.match(store.state().court.cases[0].error,/interrupted/);assert.equal(store.state().court.cases[0].statements.Mahmoud.text,'M SEALED');store.close();rmSync(dir,{recursive:true});});
test('judge uses structured function output, pinned existing model, and treats evidence as data',async()=>{process.env.OPENAI_API_KEY='test-only';const result=await judge({context:{stage:'investigation',language:'Arabic'},images:[],fetcher:async(_,options)=>{const b=JSON.parse(options.body);assert.equal(b.model,'gpt-5.6-luna');assert.equal(b.store,false);assert.equal(b.parallel_tool_calls,false);assert.equal(b.tools[0].strict,true);assert.match(b.instructions,/untrusted data/);return new Response('data: '+JSON.stringify({type:'response.completed',response:{output:[{type:'function_call',name:'court_step',arguments:JSON.stringify({kind:'question',target:'Mahmoud',text:'Clarify?'})}],usage:{input_tokens:10,output_tokens:10}}})+'\n\n');}});assert.equal(result.result.kind,'question');});
test('two HTTP accounts complete a case, export it and recover from a cancelled judge',async()=>{
 process.env.MAHMOUD_EMAIL='mahmoud@example.test';process.env.SAFY_EMAIL='safy@example.test';process.env.OPENAI_API_KEY='test-only';const store=new Store(':memory:');let captured,hold=false,release;const courtAI=async args=>{captured=args.context;if(hold)return new Promise(r=>release=r);const c=store.state().court.cases[0];const context=args.context;if(context.stage==='ready')return {result:decision({c}),usage:{input_tokens:1,output_tokens:1}};if(!context.canReview)return {result:{kind:'question',target:context.allowedTargets[0],text:'What exactly was agreed?'},usage:{input_tokens:1,output_tokens:1}};return {result:{kind:'review',text:'Both accounts were heard.',agreed:['Discussion'],disputed:['Commitment'],missing:['Confirmation']},usage:{input_tokens:1,output_tokens:1}};};
 const authFetch=async(url,opts)=>{const name=url.includes('/token?')?JSON.parse(opts.body).email.split('@')[0]:opts.headers.Authorization.split(' ')[1],user={id:name+'-uid',email:name+'@example.test',email_confirmed_at:'2026-01-01'};return Response.json(url.includes('/token?')?{user,access_token:name,refresh_token:name,expires_in:3600}:user);};const server=createApp({store,origin:'http://localhost',secret:'test secret with more than thirty two characters',testing:true,authFetch,courtAI});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,cookies={};const request=async(n,path,data)=>{const r=await fetch(base+'/api/'+path,{method:data?'POST':'GET',headers:{Origin:'http://localhost',Cookie:cookies[n]??'','Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});if(r.headers.get('set-cookie'))cookies[n]=r.headers.get('set-cookie').split(';')[0];return {status:r.status,text:await r.text()};};const state=()=>store.state().court?.cases[0];const cmd=async(n,t,d={})=>request(n,'command',{id:randomUUID(),type:'court.'+t,data:{id:state()?.id,revision:state()?.revision,...d}});const wait=async()=>{for(let i=0;i<100&&state().pending;i++)await new Promise(r=>setTimeout(r,5));assert.equal(state().pending,null);};
 try{for(const n of ['mahmoud','safy'])assert.equal((await request(n,'login',{email:n+'@example.test',password:'test'})).status,200);assert.equal((await cmd('mahmoud','create',{title:'Plans',issue:'Was the plan confirmed?'})).status,200);assert.equal((await cmd('safy','accept')).status,200);assert.equal((await cmd('mahmoud','statement',{text:'HTTP SEALED'})).status,200);assert.ok(!(await request('safy','export')).text.includes('HTTP SEALED'));assert.ok(!(await request('safy','court/'+state().id)).text.includes('HTTP SEALED'));assert.equal((await cmd('safy','statement',{text:'Other view'})).status,200);
 for(let i=0;i<2;i++){assert.equal((await cmd('mahmoud','ask')).status,200);await wait();const q=state().questions.at(-1);assert.equal((await cmd(q.target.toLowerCase(),'answer',{question:q.id,text:'My answer'})).status,200);}assert.equal((await cmd('mahmoud','ask')).status,200);await wait();assert.equal(state().stage,'review');assert.equal((await cmd('mahmoud','approve')).status,200);assert.equal((await cmd('safy','approve')).status,200);assert.equal((await cmd('safy','ask')).status,200);await wait();assert.equal(state().stage,'decided');const doc=await request('safy','court/'+state().id+'?download=1');assert.equal(doc.status,200);assert.ok(doc.text.includes('insufficient evidence'));assert.equal(captured.records.some(r=>r.text==='HTTP SEALED'),true);
 assert.equal((await cmd('mahmoud','appeal',{text:'New evidence'})).status,200);await cmd('safy','accept');await cmd('mahmoud','statement',{text:'New account'});await cmd('safy','statement',{text:'New response'});hold=true;await cmd('mahmoud','ask');for(let i=0;i<50&&!release;i++)await new Promise(r=>setTimeout(r,5));assert.ok(release);await cmd('safy','pause',{value:true});release({result:{kind:'question',target:'Mahmoud',text:'MUST NOT ARRIVE'}});await new Promise(r=>setTimeout(r,20));assert.ok(!JSON.stringify(store.state()).includes('MUST NOT ARRIVE'));assert.equal(state().pending,null);
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));store.close();}
});
