import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {initial} from '../domain.mjs';
import {courtChange,courtView} from '../court.mjs';
const walk=n=>[n,...n.children.flatMap(walk)];
function client(s){
 class Node{
  constructor(tag='div'){this.tag=tag;this.children=[];this.dataset={};this.className='';this.value='';this.ownText='';this.scrollTop=0;this.scrollHeight=200;this.clientHeight=200;this.classList={add:c=>this.className+=' '+c,toggle:(c,v)=>{const all=new Set(this.className.split(' '));if(v)all.add(c);else all.delete(c);this.className=[...all].join(' ');}};}
  set textContent(v){this.ownText=v;this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join('');}
  append(...nodes){for(const n of nodes){n.remove();n.parentElement=this;this.children.push(n);}}after(n){this.parentElement?.append(n);}replaceChildren(){this.children=[];this.ownText='';}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(n=>n!==this);this.parentElement=null;}
  setAttribute(k,v){this[k]=v;}querySelectorAll(q){return walk(this).slice(1).filter(n=>n.tag===q||q.startsWith('.')&&n.className.split(' ').includes(q.slice(1)));}querySelector(q){return this.querySelectorAll(q)[0]??null;}showModal(){this.open=true;}close(){this.open=false;}
 }
 const body=new Node('body'),together=new Node(),space=new Node(),crown=new Node('button'),heading=new Node();body.append(together,space);together.append(crown);space.append(heading);crown.id='crown-summary';const document={body,createElement:t=>new Node(t),querySelector:q=>q==='#space .wall-heading'?heading:walk(body).find(n=>n.id===q.slice(1))??null};const storage=new Map(),ctx={document,Intl,Date,crypto:{randomUUID},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(readFileSync(new URL('../public/court.js',import.meta.url),'utf8'),ctx);let reveals=[],errors=[];
 const sync=async()=>ctx.OurCourt.sync({who:'Mahmoud',court:courtView(s,'Mahmoud'),personal:{profiles:{Mahmoud:{},Safy:{}}},messages:[],pauses:[]});ctx.OurCourt.init({goto(){},revealPanel:id=>reveals.push(id),info:e=>errors.push(e),command:async(type,data)=>courtChange(s,'Mahmoud',type,data),sync});sync();return {ui:ctx.OurCourt,doc:document,sync,reveals,errors,panel:()=>document.querySelector('#court-panel'),modal:()=>walk(body).find(n=>n.tag==='dialog'&&n.open)};
}
const button=(n,t)=>walk(n).find(n=>n.tag==='button'&&n.textContent===t);
test('court opens maximized, preserves typed account across sizing and partner updates, then saves it',async()=>{
 const s=initial(),{id}=courtChange(s,'Mahmoud','court.create',{title:'Our plans',issue:'A misunderstanding'});let c=s.court.cases[0];courtChange(s,'Safy','court.accept',{id,revision:c.revision});const ui=client(s);await ui.doc.querySelector('#court-open').onclick();assert.equal(ui.panel().hidden,false);assert.deepEqual(ui.reveals,[]);assert.ok(ui.panel().className.includes('court-full'));const form=ui.panel().querySelector('form'),textarea=form.querySelector('textarea');textarea.value='My account in progress';textarea.oninput();await button(ui.panel(),'Minimize').onclick();assert.equal(ui.panel().hidden,false);assert.ok(!ui.panel().className.split(' ').includes('court-full'));assert.equal(ui.panel().querySelector('form'),form);await button(ui.panel(),'Maximize').onclick();assert.ok(ui.panel().className.includes('court-full'));assert.equal(textarea.value,'My account in progress');courtChange(s,'Safy','court.statement',{id,revision:c.revision,text:'Partner account'});await ui.sync();assert.equal(ui.panel().querySelector('form'),form);assert.equal(textarea.value,'My account in progress');assert.ok(!ui.panel().textContent.includes('Partner account'));await form.onsubmit({preventDefault(){}});assert.equal(c.stage,'investigation');assert.ok(ui.panel().textContent.includes('Partner account'));assert.ok(ui.panel().textContent.includes('My account in progress'));assert.deepEqual(ui.errors,[]);await button(ui.panel(),'Minimize').onclick();assert.equal(ui.panel().hidden,false);await button(ui.panel(),'Close').onclick();assert.equal(ui.panel().hidden,true);ui.ui.reset();assert.equal(ui.doc.querySelector('#court-open').hidden,false);
});
test('case file presents current status, record and download actions without creating duplicate cases',async()=>{
 const s=initial();courtChange(s,'Mahmoud','court.create',{title:'Case title',issue:'Case issue'});const ui=client(s);await ui.doc.querySelector('#court-open').onclick();await button(ui.panel(),'Case record').onclick();assert.ok(ui.modal().textContent.includes('Waiting for Safy'));assert.ok(walk(ui.modal()).some(n=>n.tag==='a'&&n.textContent==='Download record'));assert.ok(walk(ui.modal()).some(n=>n.tag==='a'&&n.textContent==='Print / Save PDF'));assert.equal(s.court.cases.length,1);
});
