import test from 'node:test';
import assert from 'node:assert/strict';
import {updateCrown,crownSnapshot} from '../crown.mjs';
import {Store} from '../store.mjs';
const ledger=(m,c)=>({records:{solo:{Mahmoud:{wins:{Mahmoud:m,Computer:c},history:[]}},shared:{wins:{Mahmoud:999,Safy:999}}}});
test('solo totals combine match wins only and stay private to Mahmoud',()=>{const s={domino:ledger(5,3),ocho:ledger(4,4)};updateCrown(s);assert.equal(s.crownTrial.holder,'Mahmoud');assert.deepEqual(s.crownTrial.totals,{Mahmoud:9,Computer:7});assert.equal(crownSnapshot(s,'Safy'),null);});
test('incumbent retains ties, transfer occurs once on overtaking, zero-zero has no crown',()=>{const s={domino:ledger(0,0),ocho:ledger(0,0)};updateCrown(s);assert.equal(s.crownTrial.holder,null);s.domino.records.solo.Mahmoud.wins.Mahmoud=1;updateCrown(s);assert.equal(s.crownTrial.holder,'Mahmoud');s.ocho.records.solo.Mahmoud.wins.Computer=1;updateCrown(s);assert.equal(s.crownTrial.holder,'Mahmoud');s.ocho.records.solo.Mahmoud.wins.Computer=2;updateCrown(s);assert.equal(s.crownTrial.holder,'Computer');s.domino.records.solo.Mahmoud.wins.Mahmoud=2;updateCrown(s);updateCrown(s);assert.equal(s.crownTrial.holder,'Computer');assert.equal(s.crownTrial.events.length,2);});
test('backfill finds incumbent from cross-game history at an existing tie',()=>{const s={domino:ledger(1,0),ocho:ledger(0,1)};s.domino.records.solo.Mahmoud.history=[{id:'m',winner:'Mahmoud',date:'2026-01-01'}];s.ocho.records.solo.Mahmoud.history=[{id:'c',winner:'Computer',at:'2026-01-02'}];updateCrown(s);assert.equal(s.crownTrial.holder,'Mahmoud');assert.equal(s.crownTrial.events.length,0);});
test('save atomically persists totals, incumbent and transfer history without generating chat or AI work',()=>{const store=new Store(':memory:');try{const s=store.state();s.domino=ledger(1,0);store.save(s);const a=store.state();a.ocho=ledger(0,1);store.save(a);assert.equal(store.state().crownTrial.holder,'Mahmoud');a.ocho.records.solo.Mahmoud.wins.Computer=2;store.save(a);assert.equal(store.state().crownTrial.holder,'Computer');assert.equal(store.state().crownTrial.events.length,2);assert.equal(store.messages().length,0);}finally{store.close();}});
