import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function client(){
 class Node{constructor(text=''){this.textContent=text;this.children=[];this.dataset={};this.classes=new Set();this.classList={toggle:(k,v)=>v?this.classes.add(k):this.classes.delete(k),contains:k=>this.classes.has(k)};this.events={};}append(n){this.children.push(n);n.parent=this;}replaceChildren(){this.children=[];}setAttribute(k,v){this[k]=v;}removeAttribute(k){delete this[k];}addEventListener(k,f){this.events[k]=f;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}showModal(){this.open=true;}close(){this.open=false;}}
 const nodes=new Map(),get=k=>{if(!nodes.has(k))nodes.set(k,new Node());return nodes.get(k);};const avatar=new Node('M'),account=new Node('Mahmoud'),domino=new Node('Mahmoud · 5 wins');const lists={'.message.mahmoud .avatar':[avatar],'#account > span':[account],'#domino-records .domino-win-total':[domino]};get('#ocho-solo').classes.add('selected');get('#domino-solo-tab').classes.add('selected');
 const walk=n=>[n,...n.children.flatMap(walk)],body=new Node();const doc={body,createElement:()=>new Node(),querySelector:q=>q==='#crown-moment'?walk(get('#chat')).find(n=>n.id==='crown-moment')??null:get(q),querySelectorAll:q=>lists[q]??[]};const ctx={document:doc};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(readFileSync(new URL('../public/crown.js',import.meta.url),'utf8'),ctx);return {ui:ctx.OurCrown,get,avatar,domino,body,walk};
}
const snapshot=()=>({who:'Mahmoud',crown:{holder:'Mahmoud',totals:{Mahmoud:9,Computer:7},breakdown:{domino:{Mahmoud:5,Computer:3},ocho:{Mahmoud:4,Computer:4}},revision:0,events:[]}});
test('crown decorates avatar and solo score, opens breakdown and cleans up on logout',()=>{const c=client();c.ui.sync(snapshot());assert.ok(c.avatar.classes.has('crown-avatar'));assert.ok(c.domino.classes.has('crown-holder'));c.get('#crown-summary').onclick();assert.ok(c.body.children[0].open);assert.ok(c.walk(c.body).some(n=>n.textContent==='Total wins'));c.ui.reset();assert.equal(c.avatar.classes.has('crown-avatar'),false);assert.equal(c.get('#crown-summary').hidden,true);assert.equal(c.body.children.length,0);});
test('one private crown moment per transfer, no repeated sync celebration and no trial in Safy account',()=>{const c=client(),s=snapshot();c.ui.sync(s);s.crown={...s.crown,holder:'Computer',revision:1,events:[{holder:'Computer',totals:{Mahmoud:9,Computer:10}}]};c.ui.sync(s);const banner=c.get('#chat').children[0];assert.ok(banner);assert.equal(c.avatar.classes.has('crown-avatar'),false);c.ui.sync(s);assert.equal(c.get('#chat').children[0],banner);c.ui.reset();c.ui.sync({who:'Safy',crown:null});assert.equal(c.get('#crown-summary').hidden,true);assert.equal(c.avatar.classes.has('crown-holder'),false);});
