import test from 'node:test';
import assert from 'node:assert/strict';
import {updateCrown,crownSnapshot,recordCompetitiveResult} from '../crown.mjs';
import {Store} from '../store.mjs';
import {initial} from '../domain.mjs';
import {ochoChange} from '../ocho.mjs';
const ledger=(m,f)=>({records:{shared:{wins:{Mahmoud:m,Safy:f},history:[]},solo:{Mahmoud:{wins:{Mahmoud:999,Computer:500}}}}});
const result=(winner,id,game='ocho')=>({game,title:game,matchId:id,participants:['Mahmoud','Safy'],mode:'shared',status:'complete',winner});
test('migration excludes solo trial, retains all shared totals and projects identically for both players',()=>{const s={domino:ledger(5,3),ocho:ledger(4,4),crownTrial:{holder:'Computer'}};updateCrown(s);assert.equal(s.competition.holder,'Mahmoud');assert.deepEqual(s.competition.totals,{Mahmoud:9,Safy:7});assert.deepEqual(crownSnapshot(s,'Safy'),crownSnapshot(s,'Mahmoud'));assert.equal(crownSnapshot(s,'Computer'),null);});
test('zero-zero, first winner, tied incumbent, repeated transfers and duplicate receipts',()=>{const s={};updateCrown(s);assert.equal(s.competition.holder,null);recordCompetitiveResult(s,result('Safy','1'));assert.equal(s.competition.holder,'Safy');recordCompetitiveResult(s,result('Mahmoud','2'));assert.equal(s.competition.holder,'Safy');recordCompetitiveResult(s,result('Mahmoud','3'));assert.equal(s.competition.holder,'Mahmoud');recordCompetitiveResult(s,result('Safy','4'));assert.equal(s.competition.holder,'Mahmoud');assert.equal(recordCompetitiveResult(s,result('Safy','4')),false);recordCompetitiveResult(s,result('Safy','5'));assert.equal(s.competition.holder,'Safy');assert.equal(s.competition.events.length,3);assert.deepEqual(s.competition.totals,{Mahmoud:2,Safy:3});});
test('only Ocho and Dominoes enter the crown; invalid modes cannot earn wins',()=>{const s={};recordCompetitiveResult(s,result('Safy','same','chess'));recordCompetitiveResult(s,result('Mahmoud','same','ocho'));assert.equal(crownSnapshot(s,'Safy').breakdown.chess,undefined);for(const override of [{mode:'solo'},{mode:'cooperative'},{status:'ended'},{winner:null},{participants:['Mahmoud','Computer']}])assert.equal(recordCompetitiveResult(s,{...result('Mahmoud','invalid'),...override}),false);assert.deepEqual(s.competition.totals,{Mahmoud:1,Safy:0});});
test('historical tie reconstructs holder and imported match IDs cannot be counted again',()=>{const s={domino:ledger(1,0),ocho:ledger(0,1)};s.domino.records.shared.history=[{id:'m',winner:'Mahmoud',status:'completed',date:'2026-01-01'}];s.ocho.records.shared.history=[{id:'f',winner:'Safy',status:'complete',at:'2026-01-02'}];updateCrown(s);assert.equal(s.competition.holder,'Mahmoud');assert.equal(recordCompetitiveResult(s,result('Safy','f')),false);assert.equal(s.competition.events.length,0);});
test('persisted ledger survives repeated saves without chat messages or duplicate totals',()=>{const store=new Store(':memory:');try{const s=store.state();recordCompetitiveResult(s,result('Safy','1'));store.save(s);const recovered=store.state();recordCompetitiveResult(recovered,result('Safy','1'));store.save(recovered);assert.deepEqual(store.state().competition.totals,{Mahmoud:0,Safy:1});assert.equal(store.messages().length,0);}finally{store.close();}});
test('actual shared Ocho completion feeds the unified ledger exactly once',()=>{const s=initial();ochoChange(s,'Mahmoud','ocho.create',{mode:'shared'},1000);const g=s.ocho.shared;ochoChange(s,'Safy','ocho.accept',{game:g.id,revision:g.revision},1001);g.hands.Mahmoud=[{id:'win',kind:'number',color:'red',value:1}];g.color='red';ochoChange(s,'Mahmoud','ocho.play',{game:g.id,revision:g.revision,card:'win'},1002);assert.equal(s.competition.totals.Mahmoud,1);assert.equal(s.ocho.records.shared.wins.Mahmoud,1);assert.equal(crownSnapshot(s,'Safy').holder,'Mahmoud');});


test('schema migration removes historical drawing wins and wrong incumbent without losing eligible totals',()=>{
 const s={competition:{schema:1,totals:{Mahmoud:9,Safy:20},holder:'Safy',games:{ocho:{title:'Ocho',wins:{Mahmoud:2,Safy:1}},domino:{title:'Dominoes',wins:{Mahmoud:7,Safy:3}},draw:{title:'Draw',wins:{Mahmoud:0,Safy:16}}},results:{x:{game:'draw',matchId:'x',winner:'Safy',at:'2026-01-01'}},events:[{holder:'Safy'}]}};
 const c=crownSnapshot(s,'Mahmoud');assert.deepEqual(c.totals,{Mahmoud:9,Safy:4});assert.equal(c.holder,'Mahmoud');assert.deepEqual(Object.keys(c.breakdown),['domino','ocho']);assert.equal(c.events.length,0);assert.equal(recordCompetitiveResult(s,result('Safy','new','draw')),false);assert.deepEqual(crownSnapshot(s,'Safy').totals,c.totals);
});
