import test from 'node:test';import assert from 'node:assert/strict';
import {dailyGenerate} from '../daily-ai.mjs';import {editorialIssue,morningFallback} from '../daily-editorial.mjs';
const usage={input_tokens:100,output_tokens:40};
function response(text,extra=[]){return Response.json({status:'completed',usage,output:[...extra,{type:'message',content:[{type:'output_text',text}]}]});}
test('morning bus filler fails before spending on a review',async()=>{process.env.OPENAI_API_KEY='test';let calls=0;await assert.rejects(dailyGenerate({kind:'morning',variant:'question',fetcher:async()=>{calls++;return response('DATE: none\nThe best seat on a bus is the one near the window.');}}),/Off-topic/);assert.equal(calls,1);});
test('independent review rejects off-contract post and accounts for both requests',async()=>{process.env.OPENAI_API_KEY='test';let calls=0;try{await dailyGenerate({kind:'morning',variant:'question',fetcher:async()=>++calls===1?response('DATE: none\nAn ordinary comment that offers nothing interesting to discuss.'):response(JSON.stringify({approve:false,reason:'Mundane filler, not a couple question.'}))});assert.fail('should reject');}catch(e){assert.match(e.message,/Editorial review/);assert.equal(e.usage.input_tokens,200);}assert.equal(calls,2);});
test('approved candidate retains sources and sums writer plus reviewer usage',async()=>{process.env.OPENAI_API_KEY='test';let calls=0;const result=await dailyGenerate({kind:'morning',variant:'question',fetcher:async()=>++calls===1?response('DATE: none\nWould you rather plan our next trip together or surprise each other?'):response(JSON.stringify({approve:true,reason:'Specific, natural shared choice.'}))});assert.equal(result.value.reviewed,true);assert.equal(result.usage.output_tokens,80);});
test('review network failure retains the conservative reservation',async()=>{process.env.OPENAI_API_KEY='test';let calls=0;try{await dailyGenerate({kind:'morning',variant:'question',fetcher:async()=>{if(++calls===1)return response('DATE: none\nWould you rather plan our next trip together or surprise each other?');throw Error('disconnected');}});}catch(e){assert.equal(e.usage,undefined);assert.equal(e.unknownReviewCost,true);}});
test('comment language is English for Arabic input until explicitly requested',async()=>{process.env.OPENAI_API_KEY='test';for(const [text,language]of [['ازيك','English'],['رد بالعربي','Arabic']])await dailyGenerate({kind:'comment',post:{comments:[{text}]},fetcher:async(_,opts)=>{assert.match(JSON.parse(opts.body).instructions,new RegExp('Reply in '+language));return response('A short relevant reply.');}});});
test('reserves do not repeat and old candidates fail similarity gate',()=>{let items=[];for(let i=0;i<6;i++){const p=morningFallback(items);assert.ok(p);items.unshift({...p,daily:{slot:'morning',reserveFormat:p.reserveFormat}});}assert.equal(morningFallback(items),null);assert.match(editorialIssue(items[0],'morning',items.map(x=>x.title)),/Repeated/);});
