import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {initial} from '../domain.mjs';
import {drawState,drawChange,drawView,drawApply} from '../draw.mjs';
const walk=n=>[n,...n.children.flatMap(walk)];
function client(s){
 class Node{constructor(tag='div'){this.tag=tag;this.children=[];this.className='';this.style={};this.value='';this.ownText='';this.classList={add:c=>this.className+=' '+c,remove:c=>this.className=this.className.split(' ').filter(x=>x!==c).join(' '),toggle:(c,v)=>{this.classList.remove(c);if(v)this.classList.add(c);}};}set textContent(v){this.ownText=v;this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join('');}append(...nodes){for(const n of nodes){n.parentElement=this;this.children.push(n);}}replaceChildren(){this.children=[];this.ownText='';}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(n=>n!==this);}setAttribute(k,v){this[k]=v;}querySelector(q){return walk(this).slice(1).find(n=>n.tag===q)??null;}getBoundingClientRect(){return {left:0,top:0,width:400,height:300};}getContext(){return {fillRect(){},clearRect(){},beginPath(){},lineTo(){},moveTo(){},arc(){},fill(){},stroke(){}};}setPointerCapture(){}toDataURL(){return 'data:image/png;base64,AAAA';}click(){this.onclick?.();}}
 const body=new Node('body'),together=new Node();together.id='together';body.append(together);const document={body,createElement:t=>new Node(t),createTextNode:text=>{const n=new Node('text');n.textContent=text;return n;},querySelector:q=>walk(body).find(n=>n.id===q.slice(1)),addEventListener(){}};
 const ctx={document,Date,Math,JSON,Map,crypto:{randomUUID},setInterval(){},setTimeout:fn=>{fn();},ResizeObserver:class{observe(){}},confirm:()=>true};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(readFileSync(new URL('../public/draw.js',import.meta.url),'utf8'),ctx);
 const sync=async()=>ctx.OurDraw.sync({who:'Mahmoud',draw:structuredClone(drawView(s,'Mahmoud')),personal:{profiles:{}},serverNow:Date.now()});ctx.OurDraw.init({command:async(t,d)=>drawChange(s,'Mahmoud',t,d),sync,revealPanel(){}});sync();const panel=()=>document.querySelector('#draw-panel');const button=t=>walk(panel()).find(n=>n.tag==='button'&&n.textContent===t);return {ctx,document,panel,button,sync};
}
test('drawing canvas opens inline, sizes without losing the canvas, and clears private UI on sign-out',async()=>{const s=initial();drawState(s);const c=client(s);c.document.querySelector('#draw-open').onclick();const canvas=c.panel().querySelector('canvas');assert.equal(c.panel().hidden,false);c.button('Full screen').onclick();assert.ok(c.panel().className.includes('draw-full'));c.button('Minimize').onclick();assert.equal(c.panel().querySelector('canvas'),canvas);c.ctx.OurDraw.reset();assert.equal(c.panel().hidden,true);});
test('shared strokes are persisted and partner updates preserve the guess input',async()=>{const s=initial();drawState(s);const c=client(s);c.document.querySelector('#draw-open').onclick();const canvas=c.panel().querySelector('canvas');canvas.onpointerdown({button:0,pointerId:1,clientX:100,clientY:100,preventDefault(){}});canvas.onpointermove({pointerId:1,clientX:120,clientY:100});canvas.onpointerup();await new Promise(r=>setTimeout(r,10));assert.equal(s.draw.shared.strokes.length,1);assert.equal(s.draw.shared.strokes[0].points.length,2);await c.sync();c.button('Draw & Guess').onclick();const form=c.panel().querySelector('form'),input=form.querySelector('input');input.value='a typed guess';await c.sync();assert.equal(input.value,'a typed guess');});
test('guesser UI never contains the active word and exposes guess and hint controls',()=>{const s=initial();drawState(s);drawChange(s,'Safy','draw.create',{settingsRevision:0,language:'English',difficulty:'Easy',seconds:90});const m=s.draw.match;drawChange(s,'Mahmoud','draw.accept',{id:m.id});m.pending='job';drawApply(s,m.id,'job',Array.from({length:6},(_,i)=>({word:'Secret'+i,hint:'An object',answers:[]})));drawChange(s,'Mahmoud','draw.ready',{id:m.id,round:0});drawChange(s,'Safy','draw.ready',{id:m.id,round:0});const c=client(s);c.document.querySelector('#draw-open').onclick();c.button('Draw & Guess').onclick();assert.ok(!c.panel().textContent.includes('Secret0'));assert.ok(c.button('Ask for hint · max 5 points'));assert.equal(c.panel().querySelector('form').hidden,false);});
