import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {drawState,drawView,drawChange,drawApply,drawTick,drawDeck} from '../draw.mjs';
import {crownTotals} from '../crown.mjs';
import {initial} from '../domain.mjs';
import {Store} from '../store.mjs';
import {createApp} from '../server.mjs';
const deck=['elephant','bicycle','umbrella','guitar','castle','rocket'].map(word=>({word,hint:'A thing to draw',answers:[]}));
function setup(count=true){const s=initial();drawState(s);const act=(n,t,p={},now=1000)=>drawChange(s,n,'draw.'+t,{id:s.draw.match?.id,round:s.draw.match?.round,...p},now);if(count)act('Mahmoud','settings',{value:true,revision:0});act('Mahmoud','create',{settingsRevision:s.draw.settingsRevision,language:'English',difficulty:'Easy',seconds:90});act('Safy','accept');const m=s.draw.match;m.pending='job';drawApply(s,m.id,'job',deck);return {s,m,act};}
function ready(h,time=1000){h.act('Mahmoud','ready',{},time);h.act('Safy','ready',{},time);}
test('word deck never appears in guesser projection; each player draws and guesses equally',()=>{const h=setup();assert.ok(!JSON.stringify(drawView(h.s,'Mahmoud')).includes('elephant'));ready(h);assert.equal(drawView(h.s,'Mahmoud').match.word,'elephant');assert.ok(!JSON.stringify(drawView(h.s,'Safy')).includes('elephant'));assert.ok(!JSON.stringify(drawView(h.s,'Mahmoud')).includes('rocket'));assert.throws(()=>h.act('Mahmoud','guess',{text:'elephant'}));h.act('Safy','guess',{text:'elephant'});h.act('Mahmoud','next');ready(h);assert.equal(drawView(h.s,'Safy').match.word,'bicycle');assert.equal(drawView(h.s,'Mahmoud').match.word,null);});
test('six drawing rounds never award a crown win even with a legacy enabled setting',()=>{const h=setup();h.act('Safy','settings',{revision:1,value:false});for(let i=0;i<6;i++){ready(h);if(h.m.guesser==='Safy')h.act('Safy','hint');h.act(h.m.guesser,'guess',{text:deck[i].word});if(i<5)h.act('Mahmoud','next');}assert.equal(h.m.status,'complete');assert.deepEqual(h.m.scores,{Mahmoud:30,Safy:15});assert.deepEqual(crownTotals(h.s),{Mahmoud:0,Safy:0});assert.equal(h.s.draw.history[0].countCrown,true);assert.throws(()=>h.act('Mahmoud','guess',{text:'rocket'}));assert.deepEqual(crownTotals(h.s),{Mahmoud:0,Safy:0});});
test('excluded games, ties and abandoned matches never award crown wins',()=>{for(const count of [false,true]){const h=setup(count);for(let i=0;i<6;i++){ready(h);h.act(h.m.guesser,'guess',{text:deck[i].word});if(i<5)h.act('Mahmoud','next');}assert.equal(h.m.winner,null);assert.deepEqual(crownTotals(h.s),{Mahmoud:0,Safy:0});}const h=setup(false);for(let i=0;i<6;i++){ready(h);if(h.m.guesser==='Safy')h.act('Safy','hint');h.act(h.m.guesser,'guess',{text:deck[i].word});if(i<5)h.act('Mahmoud','next');}assert.equal(h.m.winner,'Mahmoud');assert.deepEqual(crownTotals(h.s),{Mahmoud:0,Safy:0});const a=setup();a.act('Safy','end');assert.equal(a.m.status,'closed');assert.deepEqual(crownTotals(a.s),{Mahmoud:0,Safy:0});});
test('server timer expires rounds once and pauses require each owner to resume',()=>{const h=setup();ready(h);h.act('Mahmoud','pause',{value:true},11000);h.act('Safy','pause',{value:true},12000);assert.equal(drawTick(h.s,999999),false);h.act('Mahmoud','pause',{value:false},20000);assert.equal(h.m.pauses.length,1);h.act('Safy','pause',{value:false},30000);assert.equal(h.m.deadline,110000);assert.equal(drawTick(h.s,110000),true);assert.equal(drawTick(h.s,110001),false);assert.equal(h.m.results.length,1);});
test('strokes validate ownership, segments and canvas generations; undo touches only own strokes',()=>{const h=setup();const b=h.s.draw.shared;const stroke=(by,id,offset=0)=>h.act(by,'stroke',{mode:'shared',boardId:b.id,strokeId:id,offset,color:'#123456',width:5,tool:'pen',points:[[0.2,0.5]]});const a=randomUUID(),c=randomUUID();stroke('Mahmoud',a);stroke('Safy',c);assert.throws(()=>stroke('Safy',a,1));assert.throws(()=>stroke('Mahmoud',a,0));stroke('Mahmoud',a,1);h.act('Mahmoud','undo',{mode:'shared',boardId:b.id});assert.equal(b.strokes.length,1);assert.equal(b.strokes[0].by,'Safy');const id=b.id;h.act('Safy','clear',{mode:'shared',boardId:id,revision:b.revision});assert.notEqual(b.id,id);assert.throws(()=>h.act('Safy','stroke',{mode:'shared',boardId:id}));ready(h);assert.throws(()=>h.act('Safy','stroke',{mode:'guess',matchId:h.m.id,boardId:h.m.board.id}));});
test('invalid word decks and late AI results do not start matches',()=>{assert.throws(()=>drawDeck(deck.slice(0,3)));assert.throws(()=>drawDeck(deck.map(w=>({...w,hint:w.word}))));const h=setup();assert.equal(drawApply(h.s,h.m.id,'old',deck),false);});
test('two authenticated HTTP sessions preserve private words across state and export; strokes are idempotent',async()=>{
 process.env.MAHMOUD_EMAIL='mahmoud@example.test';process.env.SAFY_EMAIL='safy@example.test';process.env.OPENAI_API_KEY='test-only';const store=new Store(':memory:');const authFetch=async(url,opts)=>{const n=url.includes('/token?')?JSON.parse(opts.body).email.split('@')[0]:opts.headers.Authorization.split(' ')[1],user={id:n+'-uid',email:n+'@example.test',email_confirmed_at:'2026-01-01'};return Response.json(url.includes('/token?')?{user,access_token:n,refresh_token:n,expires_in:3600}:user);};const server=createApp({store,origin:'http://localhost',secret:'a test secret that is more than thirty two chars',testing:true,authFetch,drawAI:async()=>({result:deck,usage:{input_tokens:1,output_tokens:1}})});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,cookies={};const req=async(n,path,data)=>{const r=await fetch(base+'/api/'+path,{method:data?'POST':'GET',headers:{Origin:'http://localhost',Cookie:cookies[n]??'','Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});if(r.headers.get('set-cookie'))cookies[n]=r.headers.get('set-cookie').split(';')[0];return {status:r.status,text:await r.text()};};const cmd=(n,t,data={},id=randomUUID())=>req(n,'command',{id,type:'draw.'+t,data:{id:store.state().draw.match?.id,round:store.state().draw.match?.round,...data}});
 try{for(const n of ['mahmoud','safy'])assert.equal((await req(n,'login',{email:n+'@example.test',password:'test'})).status,200);const b=JSON.parse((await req('mahmoud','state')).text).draw.shared,receipt=randomUUID();const stroke={mode:'shared',boardId:b.id,strokeId:randomUUID(),offset:0,points:[[0.2,0.3]],color:'#123456',width:5,tool:'pen'};assert.equal((await cmd('mahmoud','stroke',stroke,receipt)).status,200);assert.equal((await cmd('mahmoud','stroke',stroke,receipt)).status,200);assert.equal(store.state().draw.shared.strokes.length,1);assert.equal((await cmd('mahmoud','create',{settingsRevision:0,language:'English',difficulty:'Easy',seconds:90})).status,200);assert.equal((await cmd('safy','accept')).status,200);assert.equal((await cmd('mahmoud','prepare',{once:true})).status,200);for(let i=0;i<100&&store.state().draw.match.pending;i++)await new Promise(r=>setTimeout(r,5));assert.equal(store.state().draw.match.status,'ready');await cmd('mahmoud','ready');await cmd('safy','ready');assert.ok((await req('mahmoud','state')).text.includes('elephant'));assert.ok(!(await req('safy','state')).text.includes('elephant'));assert.ok(!(await req('safy','export')).text.includes('elephant'));assert.ok(!(await req('mahmoud','export')).text.includes('rocket'));assert.equal((await cmd('mahmoud','guess',{text:'elephant'})).status,409);assert.equal((await cmd('safy','guess',{text:'elephant'})).status,200);
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));store.close();}
});

