import test from 'node:test';
import assert from 'node:assert/strict';
import {ochoDeck,ochoLegal,ochoChange,ochoSnapshot,ochoTick,ochoDue} from '../ocho.mjs';
import {initial} from '../domain.mjs';
import {Store} from '../store.mjs';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
const C=(id,color,kind='number',value=5)=>({id,color,kind,value:kind==='number'?value:null});
function setup(mode='solo',seconds=0){const s=initial();ochoChange(s,'Mahmoud','ocho.create',{mode,turnSeconds:seconds},1000);const g=mode==='solo'?s.ocho.solo.Mahmoud:s.ocho.shared;if(mode==='shared')act(s,g,'Safy','accept');return {s,g};}
function act(s,g,who,type,p={},now=1100){ochoChange(s,who,'ocho.'+type,{game:g.id,revision:g.revision,...p},now);}
function hands(g,a,b){g.hands={[g.players[0]]:a,[g.players[1]]:b};g.pile=[C('top','red')];g.color='red';g.turn=g.players[0];g.pending=0;g.drawn=null;g.pausedBy=[];g.stock=[C('stock','yellow', 'number',9),C('stock2','green','number',8)];}
test('Ocho deals eight unique cards each from a conserved 116-card deck',()=>{const {g}=setup();assert.equal(ochoDeck().length,116);assert.equal(g.hands.Mahmoud.length,8);assert.equal(g.hands.Computer.length,8);const all=[...g.stock,...g.pile,...Object.values(g.hands).flat()];assert.equal(all.length,116);assert.equal(new Set(all.map(c=>c.id)).size,116);assert.equal(g.pile[0].kind,'number');});
test('legal moves match number, color, action or wild; inactive hands have no misleading highlight',()=>{const {g}=setup();hands(g,[C('r','red','number',1),C('n','blue','number',5),C('bad','blue','number',2),C('w',null,'wild')],[C('b','green')]);assert.deepEqual(ochoLegal(g,'Mahmoud'),['r','n','w']);assert.deepEqual(ochoLegal(g,'Computer'),[]);g.pausedBy=['Mahmoud'];assert.deepEqual(ochoLegal(g,'Mahmoud'),[]);g.pausedBy=[];g.status='complete';assert.deepEqual(ochoLegal(g,'Mahmoud'),[]);});
test('draw penalties mix, reflect twice, and are paid together; ordinary wild cannot evade debt',()=>{const {s,g}=setup('shared');hands(g,[C('a','red','draw2'),C('s1',null,'shield'),C('tail','green')],[C('b',null,'draw4'),C('s2',null,'shield'),C('wild',null,'wild')]);g.stock=ochoDeck().slice(0,20);act(s,g,'Mahmoud','play',{card:'a'});act(s,g,'Safy','play',{card:'b',color:'blue'});assert.equal(g.pending,6);act(s,g,'Mahmoud','play',{card:'s1',color:'yellow'});assert.equal(g.turn,'Safy');assert.ok(!ochoLegal(g,'Safy').includes('wild'));const before=g.hands.Mahmoud.length;act(s,g,'Safy','play',{card:'s2',color:'green'});assert.equal(g.hands.Mahmoud.length,before+6);assert.equal(g.pending,0);assert.equal(g.turn,'Safy');});
test('skip and reverse keep the turn for two players',()=>{for(const kind of ['skip','reverse']){const {s,g}=setup();hands(g,[C('s','red',kind),C('tail','blue')],[C('other','yellow')]);act(s,g,'Mahmoud','play',{card:'s'});assert.equal(g.turn,'Mahmoud');}});
test('a matching drawn card must be played; Pass is rejected without changing state',()=>{const {s,g}=setup();hands(g,[C('bad','blue','number',1)],[C('other','green')]);g.stock=[C('d','red')];act(s,g,'Mahmoud','draw');assert.deepEqual(ochoLegal(g,'Mahmoud'),['d']);assert.equal(g.turn,'Mahmoud');assert.throws(()=>act(s,g,'Mahmoud','draw'),/drawn/);const before=JSON.stringify(s);assert.throws(()=>act(s,g,'Mahmoud','pass'),/Unknown/);assert.equal(JSON.stringify(s),before);assert.equal('canPass' in ochoSnapshot(s,'Mahmoud').solo,false);act(s,g,'Mahmoud','play',{card:'d'});assert.equal(g.turn,'Computer');});
test('reshuffle keeps top discard and retains every card',()=>{const {s,g}=setup();hands(g,[C('bad','blue','number',1)],[C('other','yellow')]);g.stock=[];g.pile.unshift(C('recycle','green','number',2));act(s,g,'Mahmoud','draw');assert.equal(g.pile.at(-1).id,'top');assert.equal(g.pile.length,1);assert.ok(g.hands.Mahmoud.some(c=>c.id==='recycle'));});
test('X-Ray projection reveals only the chosen opponent card, not their hand or deck',()=>{const {s,g}=setup('shared');hands(g,[C('x',null,'xray'),C('tail','red')],[C('secret1','blue'),C('secret2','green')]);act(s,g,'Mahmoud','play',{card:'x',color:'blue'});const a=ochoSnapshot(s,'Mahmoud').shared,b=ochoSnapshot(s,'Safy').shared;assert.ok(['secret1','secret2'].includes(a.peek.id));assert.equal(b.peek,null);assert.equal('hands' in a,false);assert.equal('stock' in a,false);assert.equal('peeks' in a,false);const hidden=['secret1','secret2'].find(id=>id!==a.peek.id);assert.ok(!JSON.stringify(a).includes(hidden));g.hands.Safy=g.hands.Safy.filter(c=>c.id!==a.peek.id);assert.equal(ochoSnapshot(s,'Mahmoud').shared.peek,null);});
test('Dead Red and Boo Blue target hands after playing; shields cannot stop them; ties draw for both',()=>{const {s,g}=setup('shared');hands(g,[C('d','red','deadred'),C('keep','red')],[C('shield',null,'shield')]);g.stock=ochoDeck().slice(0,20);act(s,g,'Mahmoud','play',{card:'d'});assert.equal(g.hands.Mahmoud.length,1);assert.equal(g.hands.Safy.length,3);assert.equal(g.pending,0);
 const x=setup('shared');hands(x.g,[C('boo','blue','booblue'),C('keep','red')],[C('other','red')]);x.g.color='blue';x.g.stock=ochoDeck().slice(0,20);act(x.s,x.g,'Mahmoud','play',{card:'boo'});assert.equal(x.g.hands.Mahmoud.length,3);assert.equal(x.g.hands.Safy.length,3);
});
test('winner recorded once; no moves after finish; solo and shared ledgers separated',()=>{const {s,g}=setup();hands(g,[C('win','red')],[C('other','green')]);act(s,g,'Mahmoud','play',{card:'win'});assert.equal(g.status,'complete');assert.equal(ochoSnapshot(s,'Mahmoud').records.solo.wins.Mahmoud,1);assert.equal(ochoSnapshot(s,'Mahmoud').records.shared.wins.Mahmoud,0);assert.throws(()=>act(s,g,'Mahmoud','play',{card:'win'}),/Wait/);assert.equal(ochoTick(s,999999),false);assert.equal(s.ocho.records.solo.Mahmoud.history.length,1);});
test('invitations need acceptance; reject stale turns, private solo access and expired invitations',()=>{const s=initial();ochoChange(s,'Mahmoud','ocho.create',{mode:'shared'},1000);const g=s.ocho.shared;assert.throws(()=>act(s,g,'Mahmoud','accept'),/invitation/);assert.throws(()=>act(s,g,'Safy','accept',{},700000),/invitation/);act(s,g,'Safy','accept');assert.throws(()=>ochoChange(s,'Mahmoud','ocho.draw',{game:g.id,revision:1},1200),/changed/);const solo=setup();assert.equal(ochoSnapshot(solo.s,'Safy').solo,null);assert.throws(()=>act(solo.s,solo.g,'Safy','leave'),/private/);});
test('both participants control their pause; timer resumes remaining time; delayed computer does not move early',()=>{const {s,g}=setup('shared',30);act(s,g,'Mahmoud','pause',{},2100);act(s,g,'Safy','pause',{},2200);assert.equal(ochoDue(s,90000),false);act(s,g,'Mahmoud','resume',{},3000);assert.equal(g.deadline,null);act(s,g,'Safy','resume',{},5000);assert.equal(g.deadline,34000);assert.equal(ochoTick(s,33999),false);assert.equal(ochoTick(s,34000),true);
 const x=setup();hands(x.g,[C('a','red'),C('b','blue')],[C('c','red'),C('d','yellow')]);act(x.s,x.g,'Mahmoud','play',{card:'a'},2000);assert.equal(ochoTick(x.s,3399),false);assert.equal(ochoTick(x.s,3400),true);});
test('saved games, pause and records survive SQLite restart',()=>{const dir=mkdtempSync(join(tmpdir(),'ocho-'));try{const path=join(dir,'db');let store=new Store(path);const {s,g}=setup();act(s,g,'Mahmoud','pause');store.save(s);store.close();store=new Store(path);const v=ochoSnapshot(store.state(),'Mahmoud');assert.equal(v.solo.id,g.id);assert.deepEqual(v.solo.hand,g.hands.Mahmoud);assert.deepEqual(v.solo.pausedBy,['Mahmoud']);assert.equal(ochoDue(store.state(),900000),false);store.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('complete simulated two-player games conserve cards and never leak the hidden hand',()=>{for(let run=0;run<20;run++){const {s,g}=setup('shared',15);let now=1000;for(let move=0;move<2000&&g.status==='active';move++){now+=16000;assert.equal(ochoTick(s,now),true);const all=[...g.stock,...g.pile,...Object.values(g.hands).flat()];assert.equal(all.length,116);assert.equal(new Set(all.map(c=>c.id)).size,116);for(const n of g.players){const v=ochoSnapshot(s,n).shared;assert.equal('hands' in v,false);assert.equal('stock' in v,false);}}assert.equal(g.status,'complete');assert.equal(s.ocho.records.shared.history.length,1);}});

test('draw event snapshots reveal only actual draw counts and public discards',()=>{const {s,g}=setup('shared');hands(g,[C('bad','blue','number',1)],[C('secret','green')]);g.pending=6;g.stock=[C('draw1','yellow'),C('draw2','yellow')];act(s,g,'Mahmoud','draw');const v=ochoSnapshot(s,'Safy').shared;assert.equal(v.drawEvents.at(-1).count,2);assert.equal(v.drawEvents.at(-1).by,'Mahmoud');assert.deepEqual(Object.keys(v.drawEvents.at(-1)).sort(),['by','count','id']);assert.deepEqual(v.discards.map(c=>c.id),['top']);assert.ok(!JSON.stringify(v.drawEvents).includes('draw1'));});

test('unanswerable +2 and +4 draw immediately in solo and shared, once, preserving draw animation events',()=>{for(const mode of ['solo','shared'])for(const kind of ['draw2','draw4']){const {s,g}=setup(mode,30);const opponent=g.players[1],n=kind==='draw2'?2:4;hands(g,[C('attack',kind==='draw2'?'red':null,kind),C('tail','green')],[C('other','blue','number',1)]);g.stock=ochoDeck().slice(0,20);const revision=g.revision;act(s,g,'Mahmoud','play',{card:'attack',color:'yellow'});assert.equal(g.hands[opponent].length,1+n);assert.equal(g.pending,0);assert.equal(g.turn,'Mahmoud');assert.equal(g.revision,revision+1);assert.deepEqual(g.drawEvents,[{id:1,by:opponent,count:n}]);assert.ok(g.last.includes('played'));assert.ok(g.last.includes('drew'));assert.equal(ochoTick(s,1101),false);assert.equal(g.drawEvents.length,1);}});
test('every legal counter keeps the choice with the defender; regular Wild is not a counter',()=>{for(const kind of ['draw2','draw4','shield']){const {s,g}=setup('shared');hands(g,[C('a','red','draw2'),C('tail','green')],[C('reply',null,kind),C('tail2','blue')]);act(s,g,'Mahmoud','play',{card:'a'});assert.equal(g.turn,'Safy');assert.equal(g.pending,2);assert.deepEqual(ochoLegal(g,'Safy'),['reply']);assert.equal(g.drawEvents,undefined);assert.equal(ochoDue(s,1101),false);}});
test('saved unavoidable penalties resolve on the next tick, paused ones wait for resume',()=>{for(const paused of [false,true]){const {s,g}=setup('shared');hands(g,[C('a','blue')],[C('other','green')]);g.pending=4;g.lastDrawBy='Safy';g.stock=ochoDeck().slice(0,20);if(paused){act(s,g,'Mahmoud','pause');assert.equal(ochoDue(s,1200),false);assert.equal(ochoTick(s,1200),false);act(s,g,'Mahmoud','resume');}else{assert.equal(ochoDue(s,1100),true);assert.equal(ochoTick(s,1100),true);}assert.equal(g.hands.Mahmoud.length,5);assert.equal(g.turn,'Safy');assert.equal(g.pending,0);assert.equal(g.drawEvents.length,1);assert.equal(ochoTick(s,1101),false);}});
test('final attack still ends the game using the existing winner rule',()=>{const {s,g}=setup('shared');hands(g,[C('a','red','draw2')],[C('other','green')]);act(s,g,'Mahmoud','play',{card:'a'});assert.equal(g.status,'complete');assert.equal(g.winner,'Mahmoud');assert.equal(g.hands.Safy.length,1);assert.equal(g.drawEvents,undefined);});


test('ordinary drawing is rejected without mutation for every kind of playable card',()=>{for(const kind of ['number','wild','draw4','shield','xray','skip','reverse','draw2','deadred','booblue']){const {s,g}=setup('shared');const color=['wild','draw4','shield','xray'].includes(kind)?null:kind==='booblue'?'blue':'red';hands(g,[C('ready',color,kind)],[C('other','green')]);g.color=color||'red';assert.equal(ochoSnapshot(s,'Mahmoud').shared.canDraw,false);const before=JSON.stringify(s);assert.throws(()=>act(s,g,'Mahmoud','draw'),/matching/);assert.equal(JSON.stringify(s),before);}});
test('a defender may accept the full penalty instead of playing a counter',()=>{const {s,g}=setup('shared');hands(g,[C('counter',null,'shield')],[C('other','green')]);g.pending=2;g.lastDrawBy='Safy';assert.equal(ochoSnapshot(s,'Mahmoud').shared.canDraw,true);act(s,g,'Mahmoud','draw');assert.equal(g.hands.Mahmoud.length,3);assert.equal(g.pending,0);assert.equal(g.turn,'Safy');});
test('X-Ray requires playing it and cannot track a card after it leaves and returns',()=>{const {s,g}=setup('shared');hands(g,[C('eye',null,'xray'),C('tail','yellow','number',1)],[C('seen','red','number',2),C('tail2','green','number',3)]);assert.equal(ochoSnapshot(s,'Mahmoud').shared.peek,null);act(s,g,'Mahmoud','play',{card:'eye',color:'red'});const id=g.peeks.Mahmoud,seen=g.hands.Safy.find(c=>c.id===id);g.color=seen.color;act(s,g,'Safy','play',{card:id});assert.equal(ochoSnapshot(s,'Mahmoud').shared.peek,null);g.hands.Safy.push(g.pile.pop());assert.equal(ochoSnapshot(s,'Mahmoud').shared.peek,null);});
test('completed result reports final counts and winning card, active games have no result',()=>{const {s,g}=setup('shared');hands(g,[C('win','red')],[C('other','green')]);assert.equal(ochoSnapshot(s,'Mahmoud').shared.result,null);act(s,g,'Mahmoud','play',{card:'win'});const v=ochoSnapshot(s,'Mahmoud').shared;assert.deepEqual(v.result.counts,{Mahmoud:0,Safy:1});assert.equal(v.result.lastCard.id,'win');assert.equal(JSON.stringify(v).includes('"id":"other"'),false);});
