import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {initial} from '../domain.mjs';
import {ochoChange,ochoSnapshot} from '../ocho.mjs';
const walk=e=>[e,...e.children.flatMap(walk)];
const flush=()=>new Promise(r=>setImmediate(r));
function client(s,storage=new Map()){
 let doc;class Node{constructor(tag='div'){this.tag=tag;this.children=[];this.dataset={};this.className='';this.textContent='';this.value='';this.hidden=false;this.classList={toggle:(c,value)=>{const a=new Set(this.className.split(' ').filter(Boolean));(value?a.add(c):a.delete(c));this.className=[...a].join(' ');}};}append(n){n.remove();this.children.push(n);n.parent=this;}remove(){if(this.parent){this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=null;}}querySelector(q){return walk(this).find(n=>q.startsWith('.')?n.className.split(' ').includes(q.slice(1)):n.id===q.slice(1))??null;}getBoundingClientRect(){return {left:20,top:100,width:120,height:80};}animate(frames,options){this.animations??=[];this.animations.push({frames,options});return {finished:Promise.resolve()};}replaceChildren(){this.children=[];}setAttribute(k,v){this[k]=v;}focus(){doc.activeElement=this;}showModal(){this.open=true;}close(){this.open=false;}}
 const nodes=new Map(),$=q=>{for(const root of nodes.values()){const found=walk(root).find(n=>'#'+n.id===q);if(found)return found;}if(!nodes.has(q)){const n=new Node();n.id=q.slice(1);nodes.set(q,n);}return nodes.get(q);};doc={querySelector:$,createElement:t=>new Node(t),createElementNS:(_,t)=>new Node(t),hidden:false};const context={document:doc,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},queueMicrotask,setTimeout,setInterval(){},Date,Promise,console};context.window=context;vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/ocho.js',import.meta.url),'utf8'),context);
 const ui=context.OurOcho,commands=[];const sync=async()=>ui.sync(JSON.parse(JSON.stringify({...s,who:'Mahmoud',serverNow:Date.now(),ocho:ochoSnapshot(s,'Mahmoud')})));ui.init({command:async(type,data)=>{commands.push({type,data});ochoChange(s,'Mahmoud',type,data);},sync,goto(){}});sync();return {$,ui,commands,sync,storage};
}
const find=(c,text)=>walk(c.$('#ocho-game')).find(n=>n.tag==='button'&&n.textContent===text);
function gameState(){const s=initial();ochoChange(s,'Mahmoud','ocho.create',{mode:'solo'});return s;}
test('Ocho panel minimizes with pause and remains minimized after a fresh client; reopening requires Resume',async()=>{const s=gameState(),c=client(s);c.$('#ocho-open').onclick();assert.equal(c.$('#ocho-panel').hidden,false);await c.$('#ocho-close').onclick();assert.deepEqual(s.ocho.solo.Mahmoud.pausedBy,['Mahmoud']);assert.equal(c.$('#ocho-panel').hidden,true);const fresh=client(s,c.storage);assert.equal(fresh.$('#ocho-panel').hidden,true);fresh.$('#ocho-open').onclick();assert.ok(find(fresh,'Resume game'));await find(fresh,'Resume game').onclick();assert.deepEqual(s.ocho.solo.Mahmoud.pausedBy,[]);});
test('Ocho wildcard opens color picker without playing; cancel keeps hand, color choice makes one move',async()=>{const s=gameState(),g=s.ocho.solo.Mahmoud;g.hands.Mahmoud=[{id:'w',color:null,kind:'wild'},{id:'n',color:'red',kind:'number',value:1}];const c=client(s);c.$('#ocho-open').onclick();const w=()=>walk(c.$('#ocho-game')).find(n=>n.tag==='button'&&n['aria-label']==='Wild');w().onclick();assert.equal(g.hands.Mahmoud.length,2);assert.ok(find(c,'Cancel'));await find(c,'Cancel').onclick();assert.equal(g.hands.Mahmoud.length,2);w().onclick();await find(c,'blue').onclick();assert.equal(g.color,'blue');assert.equal(g.hands.Mahmoud.length,1);assert.equal(c.commands.filter(x=>x.type==='ocho.play').length,1);});
test('Ocho full screen toggle, mute, leave confirmation and recorded outcome have working controls',async()=>{const s=gameState(),c=client(s);c.$('#ocho-open').onclick();c.$('#ocho-size').onclick();assert.ok(c.$('#ocho-panel').className.includes('ocho-full'));c.$('#ocho-size').onclick();assert.ok(!c.$('#ocho-panel').className.includes('ocho-full'));await c.$('#ocho-sound').onclick();assert.equal(c.$('#ocho-sound').textContent,'Muted');await find(c,'Leave game').onclick();assert.equal(c.$('#ocho-leave-dialog').open,true);c.$('#ocho-keep').onclick();assert.equal(s.ocho.solo.Mahmoud.status,'active');await find(c,'Leave game').onclick();await c.$('#ocho-leave-confirm').onclick();assert.equal(s.ocho.solo.Mahmoud.status,'ended');assert.ok(find(c,'Play against computer'));assert.equal(s.ocho.records.solo.Mahmoud.history[0].status,'ended');});
test('switching away during an action pauses as soon as it completes',async()=>{const s=gameState(),c=client(s);c.$('#ocho-open').onclick();const g=s.ocho.solo.Mahmoud;const playable=walk(c.$('#ocho-game')).find(n=>n.tag==='button'&&n.className.includes('ocho-card')&&!n.disabled&&!n.className.includes('wild'));if(playable)playable.onclick();c.ui.tab('chat');await flush();await flush();assert.ok(g.pausedBy.includes('Mahmoud')||g.status==='complete');assert.equal(c.$('#ocho-panel').hidden,true);});

test('discard cards stay centered in one pile, retain their tilt on unrelated renders, and all specials have artwork',async()=>{const s=gameState(),g=s.ocho.solo.Mahmoud;const kinds=['wild','draw4','draw2','skip','reverse','shield','xray','deadred','booblue'];g.hands.Mahmoud=kinds.map((kind,i)=>({id:'art'+i,kind,color:['deadred','draw2','skip','reverse'].includes(kind)?'red':kind==='booblue'?'blue':null}));g.color='red';const c=client(s);c.$('#ocho-open').onclick();const all=walk(c.$('#ocho-game'));for(const kind of kinds)assert.ok(all.some(n=>n.href==='/ocho-art.svg#'+kind));const pile=c.$('#ocho-game').querySelector('.ocho-pile'),old=pile.children.at(-1),tilt=old.className;await c.$('#ocho-sound').onclick();assert.equal(c.$('#ocho-game').querySelector('.ocho-pile'),pile);assert.equal(pile.children.at(-1),old);assert.equal(old.className,tilt);const chosen=walk(c.$('#ocho-game')).find(n=>n.tag==='button'&&n['aria-label']==='red +2');chosen.onclick();await flush();assert.equal(pile.children.length,2);assert.equal(old.className,tilt);assert.ok(pile.children.at(-1).className.includes('tilt-1'));assert.equal(pile.children.at(-1).animations.length,1);await c.$('#ocho-size').onclick();assert.equal(pile.children.at(-1).animations.length,1);});
test('actual draw effects display exact quantity once; repeated snapshots and refresh never replay the effect',async()=>{const s=gameState(),g=s.ocho.solo.Mahmoud,c=client(s);c.$('#ocho-open').onclick();g.drawEvents=[{id:1,by:'Computer',count:6}];g.revision++;s.version++;c.sync();const badges=()=>walk(c.$('#ocho-game')).filter(n=>n.className==='ocho-draw-badge');assert.equal(badges()[0].textContent,'+6 cards');assert.equal(walk(c.$('#ocho-panel')).filter(n=>n.className.includes('ocho-fly-card')).length,6);await flush();await c.sync();assert.equal(badges().length,0);const fresh=client(s,c.storage);assert.equal(walk(fresh.$('#ocho-panel')).filter(n=>n.className==='ocho-draw-badge').length,0);});

test('draw presentation preserves existing card nodes, anchors the badge to the player and reveals incoming cards on landing',async()=>{const s=gameState(),g=s.ocho.solo.Mahmoud,c=client(s);c.$('#ocho-open').onclick();const hand=c.$('#ocho-game').querySelector('.ocho-hand'),kept=[...hand.children],count=g.hands.Mahmoud.length;g.hands.Mahmoud.push({id:'incoming-1',color:'blue',kind:'number',value:4},{id:'incoming-2',color:'green',kind:'number',value:3});g.drawEvents=[{id:1,by:'Mahmoud',count:2}];g.revision++;s.version++;c.sync();assert.equal(c.$('#ocho-game').querySelector('.ocho-hand'),hand);for(const node of kept)assert.ok(hand.children.includes(node));assert.equal(hand.children.filter(n=>n.className.includes('ocho-arriving')).length,2);const badge=c.$('#ocho-game').querySelector('.ocho-draw-badge');assert.ok(badge.parent.parent.className.includes('ocho-self'));assert.ok(walk(c.$('#ocho-game')).some(n=>n.textContent==='Your cards · '+count));await flush();assert.equal(hand.children.filter(n=>n.className.includes('ocho-arriving')).length,0);assert.ok(walk(c.$('#ocho-game')).some(n=>n.textContent==='Your cards · '+(count+2)));});
