import test from 'node:test';
import assert from 'node:assert/strict';
import {initial} from '../domain.mjs';
import {personalSnapshot as view,personalChange as change,instant} from '../personal.mjs';
import {Store} from '../store.mjs';
import {createApp} from '../server.mjs';
import {randomUUID} from 'node:crypto';
const now=Date.parse('2026-09-14T06:00:00Z');
const profile=(extra={})=>({revision:0,bio:'بحب الهدوء',birthday:'1993-09-15',showAge:false,zone:'Africa/Cairo',photo:null,...extra});
const event=(extra={})=>({title:'Our anniversary',date:'2026-09-15',time:'09:00',zone:'Asia/Riyadh',person:'Both',annual:true,visibility:'shared',offsets:[0,1,7],notifyBoth:true,note:'Secret gift plan',...extra});
test('profiles hide birth year and private occasions at the server boundary; birthday has one shared source',()=>{
 const s=initial();change(s,'Mahmoud','personal.profile',profile(),now);change(s,'Mahmoud','personal.date.save',event({visibility:'private',title:'Secret surprise'}),now);const partner=view(s,'Safy',now),own=view(s,'Mahmoud',now);assert.equal(partner.profiles.Mahmoud.age,null);assert.equal(partner.profiles.Mahmoud.birthday,undefined);assert.equal(partner.dates.length,1);assert.equal(own.dates.length,2);assert.ok(!JSON.stringify(partner).includes('1993'));assert.ok(!JSON.stringify(partner).includes('Secret'));assert.equal(own.profiles.Mahmoud.age,32);
 change(s,'Mahmoud','personal.profile',profile({revision:1,birthday:'1993-10-01',showAge:true}),now);assert.equal(view(s,'Safy',now).dates.length,1);assert.equal(view(s,'Safy',now).profiles.Mahmoud.age,32);assert.throws(()=>change(s,'Safy','personal.profile',profile({name:'Mahmoud'}),now),/owner/);
});
test('reminders follow selected time zone, offsets, catch up after reopening and dismiss per account',()=>{
 const s=initial();const created=now-8*86400000;change(s,'Mahmoud','personal.date.save',event(),created);let a=view(s,'Mahmoud',now),b=view(s,'Safy',now);assert.equal(a.reminders.length,2);assert.equal(b.reminders.length,2);assert.equal(b.dates[0].preferences.note,'');assert.ok(!JSON.stringify(b).includes('Secret gift'));assert.equal(a.reminders[0].at,now);const keys=a.reminders.map(r=>r.key);change(s,'Mahmoud','personal.reminder.read',{keys},now);assert.equal(view(s,'Mahmoud',now).reminders.length,0);assert.equal(view(s,'Safy',now).reminders.length,2);
 const e=a.dates[0];change(s,'Mahmoud','personal.reminder.save',{id:e.id,revision:1,offsets:[7,1,0],note:'Updated private note'},now);assert.equal(view(s,'Mahmoud',now).reminders.length,0,'editing a note must not resurrect dismissed reminders');assert.equal(view(s,'Mahmoud',now+86400000).reminders.length,1);assert.equal(view(s,'Mahmoud',now+40*86400000).reminders.length,0);
 assert.equal(instant('2026-01-01','09:00','Asia/Riyadh'),Date.parse('2026-01-01T06:00Z'));assert.equal(instant('2026-01-01','09:00','Africa/Cairo'),Date.parse('2026-01-01T07:00Z'));assert.equal(instant('2026-07-01','09:00','Africa/Cairo'),Date.parse('2026-07-01T06:00Z'));
});
test('annual birthdays handle leap years and New Year advance reminders without duplicate copies',()=>{
 const s=initial();change(s,'Mahmoud','personal.profile',profile({birthday:'2000-02-29',zone:'UTC'}),Date.parse('2025-01-01'));assert.equal(view(s,'Safy',Date.parse('2027-02-01')).dates[0].nextDate,'2027-02-28');assert.equal(view(s,'Safy',Date.parse('2028-02-01')).dates[0].nextDate,'2028-02-29');change(s,'Mahmoud','personal.date.save',event({date:'2026-01-01',zone:'UTC',offsets:[7]}),Date.parse('2025-01-01'));assert.equal(view(s,'Safy',Date.parse('2026-12-25T09:00Z')).reminders[0].date,'2027-01-01');
});
test('occasion changes enforce creator ownership, revisions and private reminder preferences',()=>{
 const s=initial();const {id}=change(s,'Mahmoud','personal.date.save',event(),now);assert.throws(()=>change(s,'Safy','personal.date.save',event({id,revision:1}),now),/creator/);assert.throws(()=>change(s,'Safy','personal.date.delete',{id,revision:1},now),/creator/);assert.throws(()=>change(s,'Mahmoud','personal.date.save',event({id,revision:0}),now),/changed/);change(s,'Safy','personal.reminder.save',{id,revision:1,offsets:[],note:'Safy only'},now);change(s,'Mahmoud','personal.date.save',event({id,revision:1}),now);assert.deepEqual(view(s,'Safy',now).dates[0].preferences.offsets,[]);assert.ok(!JSON.stringify(view(s,'Mahmoud',now)).includes('Safy only'));change(s,'Mahmoud','personal.date.delete',{id,revision:2},now);assert.equal(view(s,'Safy',now).dates.length,0);
});
test('invalid dates, zones and reminder schedules fail validation',()=>{
 for(const d of [{date:'2026-02-30'},{zone:'Bad/Zone'},{time:'25:00'},{offsets:[365]},{title:' '},{person:'Computer'}])assert.throws(()=>change(initial(),'Mahmoud','personal.date.save',event(d),now));assert.throws(()=>change(initial(),'Mahmoud','personal.profile',profile({birthday:'2090-01-01'}),now));
});
test('authenticated API preserves profiles, prevents photo impersonation and keeps private data out of partner export',async()=>{
 process.env.MAHMOUD_EMAIL='mahmoud@example.test';process.env.SAFY_EMAIL='safy@example.test';const store=new Store(':memory:');const authFetch=async(url,opts)=>{const n=url.includes('/token?')?JSON.parse(opts.body).email.split('@')[0]:opts.headers.Authorization.split(' ')[1],user={id:n+'-uid',email:n+'@example.test',email_confirmed_at:'2026-01-01'};return Response.json(url.includes('/token?')?{user,access_token:n,refresh_token:n,expires_in:3600}:user);};
 const server=createApp({store,origin:'http://localhost',secret:'test secret with more than thirty two characters',testing:true,authFetch});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,cookies={};const request=async(n,path,data)=>{const r=await fetch(base+'/api/'+path,{method:data?'POST':'GET',headers:{Origin:'http://localhost',Cookie:cookies[n]??'','Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});if(r.headers.get('set-cookie'))cookies[n]=r.headers.get('set-cookie').split(';')[0];return {status:r.status,body:await r.json()};};const cmd=(n,type,data,id=randomUUID())=>request(n,'command',{id,type,data});
 try{for(const n of ['mahmoud','safy'])assert.equal((await request(n,'login',{email:n+'@example.test',password:'test'})).status,200);const uploaded=await request('mahmoud','photos',{data:Buffer.from([255,216,255,0]).toString('base64')});assert.equal(uploaded.status,201);assert.equal((await cmd('safy','personal.profile',profile({photo:uploaded.body.id}))).status,403);assert.equal((await cmd('mahmoud','personal.profile',profile({photo:uploaded.body.id}))).status,200);assert.equal((await cmd('mahmoud','personal.profile',profile({photo:uploaded.body.id}))).status,409);assert.equal((await cmd('safy','personal.profile',profile({name:'Mahmoud'}))).status,403);const id=randomUUID();assert.equal((await cmd('mahmoud','personal.date.save',event({visibility:'private',title:'PRIVATE OCCASION'}),id)).status,200);assert.equal((await cmd('mahmoud','personal.date.save',event({visibility:'private',title:'PRIVATE OCCASION'}),id)).status,200);const a=(await request('mahmoud','export')).body,b=(await request('safy','export')).body;assert.equal(a.personal.dates.length,2);assert.equal(b.personal.dates.length,1);assert.ok(!JSON.stringify(b).includes('PRIVATE OCCASION'));assert.ok(!JSON.stringify(b).includes('Secret gift'));assert.ok(!JSON.stringify(b).includes('1993'));assert.equal(b.personal.profiles.Mahmoud.photo,uploaded.body.id);
 const ctl=new AbortController();const stream=await fetch(base+'/api/events',{headers:{Cookie:cookies.safy},signal:ctl.signal});const reader=stream.body.getReader();const text=new TextDecoder().decode((await reader.read()).value);assert.ok(text.includes('personal'));assert.ok(!text.includes('PRIVATE OCCASION'));assert.ok(!text.includes('1993'));ctl.abort();
 }finally{await new Promise(r=>server.close(r));store.close();}
});
