import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,change} from '../domain.mjs';
import {attentionEvents} from '../push-events.mjs';
import {Store} from '../store.mjs';
const future=()=>new Date(Date.now()+86400000).toISOString();
function setup(by='Mahmoud',extra={}){const s=initial();change(s,by,'item.save',{type:'Plan',title:'A play together',...extra});return s;}
const act=(s,who,data)=>change(s,who,'item.plan',{id:s.items[0].id,revision:s.items[0].revision,...data});
test('idea agreement is separate from time confirmation for either author',()=>{for(const author of ['Mahmoud','Safy']){const partner=author==='Mahmoud'?'Safy':'Mahmoud',s=setup(author,{proposedAt:future()}),i=s.items[0];assert.deepEqual(i.plan.schedule.confirmed,[author]);assert.throws(()=>act(s,partner,{action:'confirm',scheduleId:i.plan.schedule.id}),/idea first/);act(s,partner,{action:'respond',value:'yes'});assert.deepEqual(i.plan.schedule.confirmed,[author]);act(s,partner,{action:'confirm',scheduleId:i.plan.schedule.id});assert.equal(i.plan.schedule.confirmed.length,2);}});
test('counterproposal requires confirmation of the exact new time, rejecting stale actions',()=>{const s=setup();act(s,'Safy',{action:'respond',value:'yes'});act(s,'Mahmoud',{action:'propose',at:future()});const old=s.items[0].plan.schedule.id,revision=s.items[0].revision;act(s,'Safy',{action:'propose',at:new Date(Date.now()+172800000).toISOString()});assert.deepEqual(s.items[0].plan.schedule.confirmed,['Safy']);assert.throws(()=>act(s,'Mahmoud',{action:'confirm',scheduleId:old}),/changed/);assert.throws(()=>change(s,'Mahmoud','item.plan',{id:s.items[0].id,revision,action:'respond',value:'yes'}),/changed/);});
test('alternative and not now preserve plan content and withdraw time consent',()=>{const s=setup('Safy',{proposedAt:future()}),i=s.items[0];act(s,'Safy',{action:'respond',value:'alternative',note:'A different play'});assert.equal(i.title,'A play together');assert.equal(i.plan.responses.Safy.note,'A different play');assert.deepEqual(i.plan.schedule.confirmed,[]);act(s,'Mahmoud',{action:'respond',value:'later'});assert.equal(i.plan.responses.Mahmoud.value,'later');assert.throws(()=>act(s,'Mahmoud',{action:'respond',value:'alternative',note:''}));});
test('edits invalidate consent only when idea or link changes; images/steps do not',()=>{const s=setup('Mahmoud',{link:'https://example.com/play',proposedAt:future()}),i=s.items[0];act(s,'Safy',{action:'respond',value:'yes'});act(s,'Safy',{action:'confirm',scheduleId:i.plan.schedule.id});change(s,'Mahmoud','item.save',{id:i.id,revision:i.revision,type:'Plan',title:i.title,steps:[{text:'Prepare snacks'}]});assert.equal(i.plan.schedule.confirmed.length,2);change(s,'Safy','item.save',{id:i.id,revision:i.revision,type:'Plan',title:'Another play'});assert.equal(i.plan.schedule,null);assert.deepEqual(Object.keys(i.plan.responses),['Safy']);});
test('legacy plans remain intact and initialize consent without assuming agreement',()=>{const s=setup(),i=s.items[0];delete i.plan;delete i.link;i.done=true;act(s,'Safy',{action:'respond',value:'later'});assert.equal(i.done,true);assert.equal(i.plan.responses.Mahmoud.value,'yes');assert.equal(i.plan.responses.Safy.value,'later');});
test('unsafe links, invalid times and non-plan actions are rejected',()=>{for(const link of ['javascript:alert(1)','data:text/html,hello','https://user:pass@example.com'])assert.throws(()=>setup('Mahmoud',{link}));const s=setup();for(const at of ['bad',null,'2020-01-01'])assert.throws(()=>act(s,'Safy',{action:'propose',at}));s.items[0].type='Idea';assert.throws(()=>act(s,'Safy',{action:'respond',value:'yes'}));});
test('every plan action notifies only the other person and links to its post',()=>{const s=setup();for(const data of [{action:'respond',value:'yes'},{action:'propose',at:future()},{action:'respond',value:'alternative',note:'Another idea'}]){const before=structuredClone(s);act(s,'Safy',data);const events=attentionEvents(before,s,'Safy');assert.equal(events.length,1);assert.equal(events[0].to,'Mahmoud');assert.deepEqual(events[0].target,{tab:'space',post:s.items[0].id});assert.equal(attentionEvents(s,s,'Safy').length,0);}});
test('plan consent and absolute time survive persistence and two time zones show the same instant',()=>{const s=setup('Mahmoud',{proposedAt:'2099-01-01T20:00:00+03:00'}),store=new Store(':memory:');store.save(s);const i=store.state().items[0];assert.equal(i.plan.schedule.at,'2099-01-01T17:00:00.000Z');for(const zone of ['Asia/Riyadh','Africa/Cairo'])assert.ok(new Intl.DateTimeFormat('en',{timeZone:zone,dateStyle:'full',timeStyle:'short'}).format(new Date(i.plan.schedule.at)));store.close();});
