import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createECDH,randomBytes} from 'node:crypto';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {Store} from '../store.mjs';
import {PushNotifications,validateSubscription} from '../push.mjs';
import {attentionEvents} from '../push-events.mjs';
import {createApp} from '../server.mjs';
const secret='test secret with more than thirty two characters';
function subscription(id='a'){const key=createECDH('prime256v1');key.generateKeys();return {endpoint:'https://fcm.googleapis.com/fcm/send/'+id,keys:{p256dh:key.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')}};}
function fixture(t){const store=new Store(':memory:');t.after(()=>store.close());let now=Date.now(),sent=[];for(const name of ['Mahmoud','Safy'])store.db.prepare('INSERT INTO sessions VALUES(?,?)').run(name,now+86400000);const push=new PushNotifications(store,{secret,origin:'https://example.test',now:()=>now,send:async(s,b,o)=>sent.push({sub:s,body:JSON.parse(b),options:o})});return {store,push,sent,advance:n=>now+=n};}
const event=(to='Safy',key=randomUUID())=>({key,to,body:'A new message.',kind:'message',target:{tab:'chat',message:key}});
test('subscriptions reject arbitrary hosts, malformed keys and non-HTTPS endpoints',()=>{const valid=subscription();assert.deepEqual(validateSubscription(valid),valid);for(const endpoint of ['http://fcm.googleapis.com/x','https://localhost/x','https://fcm.googleapis.com.attacker.test/x','https://fcm.googleapis.com:8000/x','https://user@fcm.googleapis.com/x'])assert.throws(()=>validateSubscription({...valid,endpoint}));assert.throws(()=>validateSubscription({...valid,keys:{p256dh:'x',auth:'x'}}));});
test('visible recipient suppresses alerts independently of the other person and across tabs',async t=>{const {push,sent,advance}=fixture(t);push.subscribe('Safy','Safy',subscription());push.subscribe('Mahmoud','Mahmoud',subscription('b'));push.presence('Mahmoud','Mahmoud',{client:randomUUID(),visible:true});const client=randomUUID();push.presence('Safy','Safy',{client,visible:true});push.presence('Safy','Safy',{client:randomUUID(),visible:false});push.enqueue(event());advance(2000);await push.drain();assert.equal(sent.length,0);push.presence('Safy','Safy',{client,visible:false});push.enqueue(event());push.enqueue(event('Mahmoud'));advance(2000);await push.drain();assert.equal(sent.length,1);assert.equal(sent[0].body.owner,'Safy');assert.equal(sent[0].options.urgency,'high');});
test('returning to the app clears pending alerts; closed app receives collapsed notifications once',async t=>{const {push,sent,advance}=fixture(t);push.subscribe('Safy','Safy',subscription());const a=event();push.enqueue(a);push.enqueue(a);push.enqueue(event());advance(2000);await push.drain();await push.drain();assert.equal(sent.length,1);push.enqueue(event());push.presence('Safy','Safy',{client:randomUUID(),visible:true});advance(2000);await push.drain();assert.equal(sent.length,1);});
test('expired alerts and logged-out sessions cannot deliver',async t=>{const {push,sent,advance}=fixture(t);push.subscribe('Safy','Safy',subscription());push.enqueue(event());advance(121000);await push.drain();assert.equal(sent.length,0);push.enqueue(event());push.logout('Safy');advance(2000);await push.drain();assert.equal(sent.length,0);});
test('keys and endpoints are encrypted at rest; restart keeps the same VAPID identity',t=>{const {push,store}=fixture(t),sub=subscription();push.subscribe('Safy','Safy',sub);const raw=store.db.prepare('SELECT body FROM push_subscriptions').get().body;assert.ok(!raw.includes(sub.endpoint));assert.deepEqual(push.open(raw),sub);const again=new PushNotifications(store,{secret,origin:'https://example.test'});assert.equal(again.vapid.publicKey,push.vapid.publicKey);assert.ok(!store.db.prepare('SELECT body FROM push_meta').get().body.includes(push.vapid.privateKey));});
test('retries do not notify successful devices again, and expired subscriptions are removed',async t=>{const {push,store,advance}=fixture(t);push.subscribe('Safy','Safy',subscription('good'));push.subscribe('Safy','Safy',subscription('retry'));let good=0,retry=0;push.send=async sub=>{if(sub.endpoint.endsWith('good'))good++;else if(++retry===1)throw Object.assign(Error(),{statusCode:503});};push.enqueue(event());advance(2000);await push.drain();advance(16000);await push.drain();assert.equal(good,1);assert.equal(retry,2);push.send=async()=>{throw Object.assign(Error(),{statusCode:410});};push.enqueue(event());advance(2000);await push.drain();assert.equal(store.db.prepare('SELECT COUNT(*) n FROM push_subscriptions').get().n,0);});
test('chat scan skips history and own actions, waits for completed Echo replies',async t=>{const store=new Store(':memory:');t.after(()=>store.close());store.message({id:randomUUID(),author:'Mahmoud',text:'Old private text'});let now=Date.now(),sent=[];store.db.prepare('INSERT INTO sessions VALUES(?,?)').run('s',now+86400000);const push=new PushNotifications(store,{secret,origin:'https://example.test',now:()=>now,send:async(s,b)=>sent.push(JSON.parse(b))});push.subscribe('Safy','s',subscription());push.scan();now+=2000;await push.drain();assert.equal(sent.length,0);store.message({id:randomUUID(),author:'Safy',text:'Own'});push.scan('Safy');now+=2000;await push.drain();assert.equal(sent.length,0);const id=randomUUID();store.message({id,author:'Echo',text:'secret text',status:'streaming'});push.scan();now+=2000;await push.drain();assert.equal(sent.length,0);store.db.prepare("UPDATE messages SET status='sent' WHERE id=?").run(id);push.scan();now+=2000;await push.drain();assert.equal(sent.length,1);assert.ok(!JSON.stringify(sent).includes('secret text'));});
test('event policy: invitations and turns need attention; strokes and own actions do not; likes are quiet',()=>{const before={items:[{id:'p',by:'Mahmoud',comments:[],likes:[]}],draw:{strokes:[]}},after=structuredClone(before);after.draw.strokes.push({points:[1,2]});assert.deepEqual(attentionEvents(before,after,'Safy'),[]);after.items[0].likes.push('Safy');const like=attentionEvents(before,after,'Safy');assert.equal(like[0].quiet,true);assert.equal(like[0].to,'Mahmoud');after.ocho={shared:{id:'g',owner:'Mahmoud',status:'waiting'}};assert.equal(attentionEvents(before,after,'Mahmoud').find(e=>e.to==='Safy').target.game,'ocho');const active={ocho:{shared:{id:'g',owner:'Mahmoud',status:'active',turn:'Safy',revision:3}}};assert.equal(attentionEvents(after,active,'Mahmoud').filter(e=>e.to==='Safy').length,1);});
function worker({visible=false,remoteVisible=false,owner='Safy'}={}){const handlers={},shown=[],posted=[];const self={location:{origin:'https://example.test'},addEventListener:(n,f)=>handlers[n]=f,registration:{showNotification:async(...v)=>shown.push(v)},clients:{matchAll:async()=>[{url:'https://example.test/',visibilityState:visible?'visible':'hidden',focus:async()=>{},postMessage:v=>posted.push(v)}],openWindow:async u=>posted.push(u)}};vm.runInNewContext(readFileSync(new URL('../public/sw.js',import.meta.url),'utf8'),{self,URL,Date,AbortSignal,fetch:async()=>({ok:true,json:async()=>({who:owner,visible:remoteVisible})})});return {shown,posted,async push(data){await new Promise((resolve,reject)=>handlers.push({data:{json:()=>data},waitUntil:p=>p.then(resolve,reject)}));},async click(url){await new Promise((resolve,reject)=>handlers.notificationclick({notification:{close(){},data:{url}},waitUntil:p=>p.then(resolve,reject)}));}};}
test('worker suppresses foreground tabs, other visible devices, stale and wrong-account pushes',async()=>{const data={owner:'Safy',expires:Date.now()+120000,body:'Update',target:{tab:'chat'}};for(const opts of [{visible:true},{remoteVisible:true},{owner:'Mahmoud'}]){const w=worker(opts);await w.push(data);assert.equal(w.shown.length,0);}const w=worker();await w.push({...data,expires:0});assert.equal(w.shown.length,0);await w.push(data);assert.equal(w.shown.length,1);assert.deepEqual([...w.shown[0][1].vibrate],[180]);});
test('worker keeps likes silent and notification navigation same-origin',async()=>{const w=worker();await w.push({owner:'Safy',expires:Date.now()+120000,quiet:true,target:{tab:'space',post:'abc'}});assert.equal(w.shown[0][1].silent,true);assert.equal(w.shown[0][1].vibrate,undefined);await w.click('https://evil.test/');assert.equal(w.posted.length,0);await w.click(w.shown[0][1].data.url);assert.ok(w.posted[0].url.startsWith('https://example.test/?notice='));});
test('HTTP notification endpoints require auth and same origin; expose no stored keys; logout removes registration',async t=>{
 process.env.MAHMOUD_EMAIL='mahmoud@example.test';const store=new Store(':memory:');const user={id:'m',email:'mahmoud@example.test',email_confirmed_at:'2026-01-01'};const server=createApp({store,origin:'http://localhost',secret,testing:true,authFetch:async url=>Response.json(url.includes('/token?')?{user,access_token:'m',refresh_token:'m',expires_in:3600}:user),pushSend:async()=>{}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));store.close();});const base='http://127.0.0.1:'+server.address().port;let cookie='';const req=(path,data,origin='http://localhost')=>fetch(base+path,{method:data?'POST':'GET',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});assert.equal((await req('/api/notifications')).status,401);const login=await req('/api/login',{email:user.email,password:'test-password'});cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await req('/api/notifications/subscribe',subscription(),'http://evil.test')).status,403);const device=subscription();assert.equal((await req('/api/notifications/subscribe',device)).status,200);assert.equal((await req('/api/notifications/test',{endpoint:device.endpoint},'http://evil.test')).status,403);assert.equal((await req('/api/notifications/test',{endpoint:device.endpoint})).status,200);assert.equal((await req('/api/notifications/test',{endpoint:subscription('not-mine').endpoint})).status,400);assert.equal((await req('/api/notifications/receipt',{tag:'a'.repeat(24),result:'shown'})).status,200);assert.equal((await req('/api/notifications/receipt',{tag:'invalid',result:'shown'})).status,400);const config=await (await req('/api/notifications')).json();assert.deepEqual(Object.keys(config).sort(),['publicKey','visible','who']);assert.equal((await req('/api/notifications/presence',{client:randomUUID(),visible:true})).status,200);assert.equal((await(await req('/api/notifications')).json()).visible,true);assert.equal((await req('/sw.js')).status,200);await req('/api/logout',{});assert.equal(store.db.prepare('SELECT COUNT(*) n FROM push_subscriptions').get().n,0);assert.equal((await req('/api/notifications')).status,401);
});
test('a quiet like cannot replace an already queued comment alert',async t=>{const {push,sent,advance}=fixture(t);push.subscribe('Safy','Safy',subscription());push.enqueue({...event(),kind:'wall',target:{tab:'space',post:'p'},body:'A comment'});push.enqueue({...event(),kind:'wall',target:{tab:'space',post:'p'},quiet:true,body:'A like'});advance(2000);await push.drain();assert.equal(sent[0].body.body,'A comment');assert.equal(sent[0].body.quiet,false);});
test('wall replies notify the other participant even when the post owner replies',()=>{const before={items:[{id:'p',by:'Mahmoud',comments:[],likes:[]}]},after=structuredClone(before);after.items[0].comments.push({id:'c',by:'Mahmoud',text:'Reply'});const result=attentionEvents(before,after,'Mahmoud');assert.equal(result[0].to,'Safy');assert.equal(result[0].target.post,'p');});
function clientFixture({supported=true,iphone=false,installed=false}={}){
 const nodes=new Map(),handlers={},requests=[];let permissionCalls=0,subscriptionCalls=0;
 const node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,disabled:false,showModal(){},close(){}});return nodes.get(id);};
 const sub=subscription(),registration={pushManager:{getSubscription:async()=>null,subscribe:async()=>{subscriptionCalls++;return {...sub,toJSON:()=>sub,unsubscribe:async()=>{}};}},getNotifications:async()=>[]};
 const document={visibilityState:'visible',hidden:false,querySelector:node,addEventListener:(n,f)=>handlers[n]=f};
 const navigator={userAgent:iphone?'iPhone':'Android',platform:'',standalone:installed};
 if(supported)navigator.serviceWorker={register:async()=>registration,ready:Promise.resolve(registration),addEventListener(){}};
 const window={addEventListener:(n,f)=>handlers[n]=f,dispatchEvent(){},...(supported?{PushManager:{},Notification:{}}:{})};
 const Notification={permission:'default',requestPermission:async()=>{permissionCalls++;Notification.permission='granted';return 'granted';}};
 const context={window,document,navigator,crypto:{randomUUID},matchMedia:()=>({matches:installed}),location:{href:'https://example.test/',origin:'https://example.test'},history:{replaceState(){}},URL,Uint8Array,atob,CustomEvent:class{},setInterval(){},fetch:async(path,options)=>{requests.push({path,options});return {ok:true,json:async()=>path==='/api/notifications'?{publicKey:sub.keys.p256dh}:{ok:true}};},...(supported?{Notification}:{})};
 vm.runInNewContext(readFileSync(new URL('../public/notifications.js',import.meta.url),'utf8'),context);
 return {window,nodes,node,handlers,requests,get permissionCalls(){return permissionCalls;},get subscriptionCalls(){return subscriptionCalls;}};
}
test('client never prompts on sign-in; explicit Enable opts in and visibility updates are sent',async()=>{const c=clientFixture();c.window.OurNotifications.sync({who:'Mahmoud'});await new Promise(setImmediate);assert.equal(c.permissionCalls,0);assert.ok(c.requests.some(r=>r.path.endsWith('/presence')&&JSON.parse(r.options.body).visible));await c.node('#notifications-enable').onclick();assert.equal(c.permissionCalls,1);assert.equal(c.subscriptionCalls,1);assert.ok(c.requests.some(r=>r.path.endsWith('/subscribe')));c.window.OurNotifications.reset();assert.equal(JSON.parse(c.requests.at(-1).options.body).visible,false);});
test('unsupported browsers and non-installed iPhones show usable guidance without permission prompts',async()=>{for(const opts of [{supported:false},{iphone:true}]){const c=clientFixture(opts);c.node('#notifications-open').onclick();await new Promise(setImmediate);assert.equal(c.node('#notifications-enable').disabled,true);assert.ok(c.node('#notifications-status').textContent.length>20);assert.equal(c.permissionCalls,0);}});

test('Echo reply survives a late background transition instead of being lost to the previous foreground lease',async t=>{
 const {push,store,sent,advance}=fixture(t),client=randomUUID();push.subscribe('Safy','Safy',subscription());
 push.presence('Safy','Safy',{client,visible:true,sequence:1});
 store.message({id:randomUUID(),author:'Echo',text:'Hello'});push.scan();advance(2000);await push.drain();assert.equal(sent.length,0);
 push.presence('Safy','Safy',{client,visible:false,sequence:3});
 push.presence('Safy','Safy',{client,visible:true,sequence:2}); // An older heartbeat arrives out of order.
 assert.equal(push.visible('Safy'),false);advance(2000);await push.drain();assert.equal(sent.length,1);assert.equal(sent[0].body.owner,'Safy');assert.equal(sent[0].options.urgency,'high');
});
test('fresh foreground acknowledgement cancels pending replies and avoids a later stale alert',async t=>{
 const {push,sent,advance}=fixture(t),client=randomUUID();push.subscribe('Safy','Safy',subscription());
 push.presence('Safy','Safy',{client,visible:true,sequence:1});push.enqueue(event());advance(2000);await push.drain();
 push.presence('Safy','Safy',{client,visible:true,sequence:2});advance(46000);await push.drain();assert.equal(sent.length,0);
});
test('a killed background process cannot permanently suppress a new reply',async t=>{
 const {push,sent,advance}=fixture(t);push.subscribe('Safy','Safy',subscription());push.presence('Safy','Safy',{client:randomUUID(),visible:true,sequence:1});
 push.enqueue(event());advance(2000);await push.drain();assert.equal(sent.length,0);advance(6500);await push.drain();assert.equal(sent.length,1);
});
test('subscription status checks the current account and login session, not just browser permission',t=>{
 const {push}=fixture(t),sub=subscription();assert.equal(push.registered('Safy','Safy',sub.endpoint),false);push.subscribe('Safy','Safy',sub);assert.equal(push.registered('Safy','Safy',sub.endpoint),true);assert.equal(push.registered('Safy','old-session',sub.endpoint),false);assert.equal(push.registered('Mahmoud','Mahmoud',sub.endpoint),false);push.logout('Safy');assert.equal(push.registered('Safy','Safy',sub.endpoint),false);
});

test('a hidden recipient needs no long debounce before urgent provider delivery',async t=>{
 const {push,sent,advance}=fixture(t);push.subscribe('Safy','Safy',subscription());push.enqueue(event());advance(350);await push.drain();assert.equal(sent.length,1);assert.equal(sent[0].options.urgency,'high');
});

test('daily post reaches both registered devices despite another visible device, with offline delivery time',async t=>{
 const {push,store,sent,advance}=fixture(t);
 push.subscribe('Mahmoud','Mahmoud',subscription('m'));push.subscribe('Safy','Safy',subscription('s'));
 const client=randomUUID();push.presence('Mahmoud','Mahmoud',{client,visible:true,sequence:1});
 const s=store.state();s.items.unshift({id:'daily-new',by:'Echo',daily:{notify:true},comments:[],likes:[]});store.save(s);push.scan();
 push.presence('Mahmoud','Mahmoud',{client,visible:true,sequence:2});advance(5*60000);await push.drain();
 assert.equal(sent.length,2);assert.ok(sent.every(x=>x.body.deviceOnly&&x.body.kind==='daily'&&x.options.TTL>36000));
 push.scan();advance(1000);await push.drain();assert.equal(sent.length,2);
 const off=store.state();off.items.unshift({id:'daily-off',by:'Echo',daily:{notify:false}});store.save(off);push.scan();advance(1000);await push.drain();assert.equal(sent.length,2);
});
test('daily worker alerts a background phone even if another device is active, but never its own foreground',async()=>{
 const data={owner:'Safy',deviceOnly:true,kind:'daily',expires:Date.now()+43200000,target:{tab:'space',post:'daily'}};
 const background=worker({remoteVisible:true});await background.push(data);assert.equal(background.shown.length,1);
 for(const opts of [{visible:true},{owner:'Mahmoud'}]){const w=worker(opts);await w.push(data);assert.equal(w.shown.length,0);}
});
test('notification test is delayed and restricted to the requesting registered device',async t=>{
 const {push,sent,advance}=fixture(t),mine=subscription('mine');push.subscribe('Mahmoud','Mahmoud',mine);push.subscribe('Mahmoud','Mahmoud',subscription('other'));
 assert.throws(()=>push.test('Safy','Safy',mine.endpoint),/Enable/);
 push.test('Mahmoud','Mahmoud',mine.endpoint);advance(4000);await push.drain();assert.equal(sent.length,0);
 advance(1001);await push.drain();assert.equal(sent.length,1);assert.equal(sent[0].sub.endpoint,mine.endpoint);assert.equal(sent[0].body.kind,'test');
});
