import test from 'node:test';import assert from 'node:assert/strict';
import {course,runner,step,botInput,DT} from '../public/race-engine.mjs';import {RaceService} from '../race.mjs';
test('seed reproduces identical obstacles and different seeds vary courses',()=>{assert.deepEqual(course(1),course(1));assert.notDeepEqual(course(1),course(2));for(let n=0;n<100;n++){const c=course(n);assert.equal(c.parts.length,24);for(const q of c.parts){assert.ok(q.b-q.a<=180);assert.ok(q.a-q.start>=145);assert.ok(q.end-q.b>80);}}});
test('same controls and race clock produce identical runs',()=>{const c=course(5),a=runner(),b=runner();let input={dir:1,jump:0};for(let n=0;n<12000;n++){input=botInput(c,a,n*DT,input);step(c,a,input,n*DT);step(c,b,input,n*DT);}assert.deepEqual(a,b);});
test('bot can traverse all generated obstacle types across 30 courses',()=>{for(let seed=0;seed<30;seed++){const c=course(seed),p=runner();let input={dir:1,jump:0},n=0;for(;n<18000&&p.x<c.finish;n++){input=botInput(c,p,n*DT,input);step(c,p,input,n*DT);}assert.ok(p.x>=c.finish,'blocked course '+seed+' at '+p.x);assert.ok(n*DT>60);}});
test('both humans must approve; forged positions ignored; stale inputs rejected; disconnect pauses clock',()=>{let now=10000;const r=new RaceService({now:()=>now});const v=r.action('Mahmoud',{mode:'together',action:'create',wager:'Sing a song'}),id=v.match.id;r.action('Mahmoud',{mode:'together',action:'ready',id});assert.equal(r.get('Mahmoud','together').status,'lobby');r.action('Safy',{mode:'together',action:'ready',id});r.input('Mahmoud',{mode:'together',id,seq:1,dir:1,jump:0,x:999999});r.input('Safy',{mode:'together',id,seq:1,dir:1,jump:0});assert.equal(r.get('Mahmoud','together').runners[0].x,70);now+=1000;r.input('Mahmoud',{mode:'together',id,seq:0,dir:-1,jump:0});assert.equal(r.get('Mahmoud','together').inputs[0].dir,1);now+=3000;r.tick();assert.equal(r.get('Mahmoud','together').status,'paused');assert.equal(r.get('Mahmoud','together').t,0);r.input('Mahmoud',{mode:'together',id,seq:2,dir:0,jump:0});r.input('Safy',{mode:'together',id,seq:2,dir:0,jump:0});r.tick();assert.equal(r.get('Mahmoud','together').status,'countdown');assert.throws(()=>r.input('Safy',{mode:'together',id:'wrong',seq:1,dir:1,jump:0}));});
test('solo races are isolated; leaving awards no winner; rematch has new identity and seed',()=>{const r=new RaceService();const a=r.action('Mahmoud',{mode:'solo',action:'create'}).match;r.action('Safy',{mode:'solo',action:'create'});assert.notEqual(r.get('Mahmoud','solo').id,r.get('Safy','solo').id);r.action('Mahmoud',{mode:'solo',action:'leave',id:a.id});assert.equal(r.get('Mahmoud','solo').winner,null);const b=r.action('Mahmoud',{mode:'solo',action:'create'}).match;assert.notEqual(a.id,b.id);assert.notEqual(a.seed,b.seed);});

test('authoritative finish awards once and treats simultaneous finishes as a tie',()=>{let now=10000,awards=[];const r=new RaceService({now:()=>now,onResult:x=>awards.push(x)});const id=r.action('Mahmoud',{mode:'together',action:'create'}).match.id;for(const name of ['Mahmoud','Safy']){r.action(name,{mode:'together',action:'ready',id});r.input(name,{mode:'together',id,seq:1,dir:1,jump:0});}const m=r.get('Mahmoud','together');m.status='racing';m.runners.forEach(p=>{p.x=m.course.finish-1;});now+=20;r.tick();assert.equal(m.winner,'Tie');now+=20;r.tick();assert.equal(awards.length,1);});

test('HTTP race requires sign-in and same origin; two accounts share one track and approve separately',async t=>{
 const {Store}=await import('../store.mjs'),{createApp}=await import('../server.mjs');process.env.MAHMOUD_EMAIL='m@race.test';process.env.SAFY_EMAIL='s@race.test';
 const store=new Store(':memory:');const origin='http://localhost';const user=name=>({id:name,email:name==='Mahmoud'?'m@race.test':'s@race.test',email_confirmed_at:'2026-01-01'});
 const server=createApp({store,origin,testing:true,secret:'test race secret longer than thirty two characters',authFetch:async(url,opts)=>{if(url.includes('/token?')){const name=JSON.parse(opts.body).email==='m@race.test'?'Mahmoud':'Safy';return Response.json({user:user(name),access_token:name,refresh_token:name,expires_in:3600});}return Response.json(user(opts.headers.Authorization.split(' ')[1]));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));store.close();});const base='http://127.0.0.1:'+server.address().port;
 const req=(path,data,cookie='',from=origin)=>fetch(base+path,{method:data?'POST':'GET',headers:{Origin:from,Cookie:cookie,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});
 assert.equal((await req('/api/race/state?mode=together')).status,401);
 const login=async email=>(await req('/api/login',{email,password:'test-password'})).headers.get('set-cookie').split(';')[0];const m=await login('m@race.test'),s=await login('s@race.test');
 assert.equal((await req('/api/race/action',{action:'create',mode:'together'},m,'https://other.test')).status,403);
 const created=await(await req('/api/race/action',{action:'create',mode:'together',wager:'Winner chooses the movie'},m)).json(),id=created.match.id;
 const shared=await(await req('/api/race/state?mode=together',null,s)).json();assert.equal(shared.match.seed,created.match.seed);assert.equal(shared.who,'Safy');
 await req('/api/race/action',{action:'ready',mode:'together',id},m);
 let view=await(await req('/api/race/state?mode=together',null,s)).json();assert.equal(view.match.status,'lobby');
 view=await(await req('/api/race/action',{action:'ready',mode:'together',id},s)).json();assert.equal(view.match.status,'countdown');
 assert.equal((await req('/api/race/input',{mode:'together',id,seq:1,dir:999,jump:0},m)).status,400);
 await req('/api/race/action',{action:'leave',mode:'together',id},m);assert.equal(store.db.prepare('SELECT count(*) n FROM race_results').get().n,0);
 assert.equal(JSON.parse(store.db.prepare('SELECT body FROM race_sessions').get().body).status,'cancelled');
});
