import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import * as engine from '../public/race-engine.mjs';import {RaceService} from '../race.mjs';
test('client opens, creates a race, sends joystick controls and resumes input sequence after reopening',async()=>{
 const nodes=[],listeners={},timers=[];const context2d=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
 class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.style={};this.hidden=false;this.textContent='';nodes.push(this);}append(e){this.children.push(e);e.parent=this;}setAttribute(){}addEventListener(){}replaceChildren(){this.children=[];}getBoundingClientRect(){return{width:this.id==='race-stage'?840:112,height:this.id==='race-stage'?440:112,left:0,top:0};}getContext(){return context2d;}showModal(){}close(){}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}focus(){}setPointerCapture(){}}
 const body=new Element('body'),launch=new Element('button');launch.id='race-open';let now=10000;const service=new RaceService({now:()=>now});const requests=[];const document={body,hidden:false,createElement:t=>new Element(t),getElementById:id=>nodes.findLast(n=>n.id===id),addEventListener:(n,f)=>listeners[n]=f,removeEventListener(){}};
 const sandbox={...engine,document,window:{addEventListener(){}},screen:{orientation:{}},performance:{now:()=>{now+=100;return now;}},AbortSignal,confirm:()=>true,setInterval:f=>(timers.push(f),timers.length),clearInterval(){},requestAnimationFrame:()=>1,cancelAnimationFrame(){},fetch:async(url,opts)=>{const u=new URL(url,'https://test.local');const d=opts.body?JSON.parse(opts.body):{};requests.push({url,d});const result=u.pathname.endsWith('/action')?service.action('Mahmoud',d):u.pathname.endsWith('/input')?service.input('Mahmoud',d):service.view(service.get('Mahmoud',u.searchParams.get('mode')),'Mahmoud');return{ok:true,json:async()=>structuredClone(result)};}};
 const code=readFileSync(new URL('../public/race.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/,'');vm.runInNewContext(code,sandbox);const flush=()=>new Promise(setImmediate),click=async text=>{const b=nodes.findLast(n=>n.textContent===text&&n.tagName==='BUTTON');assert.ok(b,text);await b.onclick();await flush();};
 launch.onclick();await flush();await click('Create race');await click('Ready — let’s race');const m=service.get('Mahmoud','solo');assert.equal(m.status,'countdown');
 const stick=document.getElementById('race-stick'),event={pointerId:1,clientX:100,clientY:56,preventDefault(){}};stick.onpointerdown(event);await flush();assert.equal(m.inputs[0].dir,1);stick.onpointermove({...event,clientY:0});await flush();assert.ok(m.inputs[0].jump>0);const j=m.inputs[0].jump;stick.onpointermove({...event,clientY:0});await flush();assert.equal(m.inputs[0].jump,j);stick.onpointerup(event);await flush();assert.equal(m.inputs[0].dir,0);
 sandbox.window.OurRace.reset();launch.onclick();await flush();stick.onpointerdown(event);await flush();const next=document.getElementById('race-stick');next.onpointerdown(event);await flush();assert.equal(m.inputs[0].dir,1);assert.ok(m.inputs[0].seq>3);
 m.status='racing';await timers[timers.length-1]();await flush();const before=vm.runInNewContext('predicted.x',sandbox);sandbox.fetch=()=>new Promise(()=>{});for(let n=0;n<4;n++)vm.runInNewContext('dir=1;draw()',sandbox);assert.ok(vm.runInNewContext('predicted.x',sandbox)>before,'local movement continues without network responses');sandbox.window.OurRace.reset();
});
