import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function setup({hugLoaded=true,failStart=false}={}){
 let now=1000,next=0;const requests=[],timers=new Map(),errors=[];
 class Node{
  constructor(){this.handlers={};this.hidden=false;this.children=[];this.nodes=new Map();this.classes=new Set();this.attrs={};this.classList={add:(...v)=>v.forEach(x=>this.classes.add(x)),remove:(...v)=>v.forEach(x=>this.classes.delete(x)),contains:x=>this.classes.has(x),toggle:(x,on)=>on?this.classes.add(x):this.classes.delete(x)};this.style={setProperty(){}};this.clientHeight=500;this.scrollHeight=1000;this.scrollTop=500;this.textContent='';this.paused=true;this.duration=4;this.currentTime=0;}
  getBoundingClientRect(){return {top:0,bottom:500,height:500,width:300,left:0,right:300};}querySelectorAll(){return [{querySelector:()=>({getBoundingClientRect:()=>({top:380,bottom:420})})}];}
  setAttribute(k,v){this.attrs[k]=v;}append(n){this.children.push(n);}insertBefore(n){this.children.unshift(n);}remove(){}setPointerCapture(){}closest(){return null;}pause(){this.paused=true;}play(){this.paused=false;return Promise.resolve();}load(){if(hugLoaded)this.emit('loadeddata');}
  querySelector(k){if(!this.nodes.has(k))this.nodes.set(k,new Node());return this.nodes.get(k);}addEventListener(t,fn){(this.handlers[t]??=[]).push(fn);}emit(t,e={}){e.preventDefault??=()=>{};e.stopPropagation??=()=>{};e.stopImmediatePropagation??=()=>{};for(const fn of this.handlers[t]||[])fn(e);}
 }
 const doc=new Node(),win=new Node(),host=new Node(),timeline=new Node(),app=new Node(),chat=new Node();doc.hasFocus=()=>true;doc.hidden=false;doc.createElement=()=>new Node();doc.querySelector=k=>k==='.conversation-window'?host:k==='#timeline'?timeline:k==='#app'?app:k==='#chat'?chat:null;let balloon=false;win.OurBalloon={busy:()=>balloon,cancel(){}};
 const context={queueMicrotask,document:doc,window:win,crypto:{randomUUID:()=> 'random-moment-123'},performance:{now:()=>now},setTimeout:(fn,delay)=>{timers.set(++next,{fn,delay});return next;},clearTimeout:id=>timers.delete(id),setInterval:()=>++next,clearInterval(){},requestAnimationFrame:()=>++next,cancelAnimationFrame(){},fetch:async()=>({}),console};vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/shared-touch.js',import.meta.url),'utf8'),context);
 win.OurTouch.init({api:async(path,p)=>{requests.push(p);if(failStart&&p.action==='start')throw Error('You both need Our Chat open and in focus.');},error:e=>errors.push(e.message)});win.OurTouch.sync({who:'Mahmoud'});const layer=host.children[0];
 const start=(x=10,y=200,target=timeline)=>timeline.emit('touchstart',{touches:[{clientX:x,clientY:y,identifier:1}],target});const move=(x,y)=>win.emit('touchmove',{touches:[{clientX:x,clientY:y,identifier:1}],cancelable:true});
 return {win,doc,timeline,layer,requests,errors,start,move,runTimers(delay){for(const [id,t]of [...timers])if(t.delay===delay){timers.delete(id);t.fn();}},advance:n=>now+=n,balloon:v=>balloon=v};
}
const m=(extra={})=>({id:'remote-moment',starter:'Safy',kind:'touch',hands:{Mahmoud:true,Safy:true},progress:1,done:true,releaseAt:null,serverNow:10000,...extra});
test('left vertical zone claims rightward touch swipe without scrolling or triggering hug',()=>{const h=setup();h.start();h.move(60,200);assert.equal(h.requests.filter(p=>p.action==='start').length,0);assert.equal(h.win.OurTouch.ownsGesture(),true);h.win.emit('touchend');assert.equal(h.layer.hidden,true);h.start();h.move(180,200);assert.equal(h.requests.at(-1).kind,'touch');assert.equal(h.timeline.scrollTop,500);});
test('original bottom zone starts hug, while a stationary hold is left to balloon',()=>{const h=setup();h.start(200,450);h.move(200,240);assert.equal(h.requests.at(-1).kind,'hug');const b=setup();b.start(200,450);b.advance(350);b.move(200,200);assert.equal(b.requests.filter(p=>p.action==='start').length,0);});
test('older scroll, another section, background and active balloon cannot start either moment',()=>{for(const scenario of ['older','tab','hidden','balloon','disconnected']){const h=setup();if(scenario==='older')h.timeline.scrollTop=100;if(scenario==='tab')h.win.OurTouch.tab('together');if(scenario==='hidden')h.doc.hidden=true;if(scenario==='balloon')h.balloon(true);if(scenario==='disconnected')h.win.OurTouch.connection(false);h.start();h.move(200,200);assert.equal(h.requests.filter(p=>p.action==='start').length,0,scenario);}});
test('unavailable artwork does not start or fake a hug',()=>{const h=setup({hugLoaded:false});h.start(200,450);h.move(200,200);assert.equal(h.requests.filter(p=>p.action==='start').length,0);assert.equal(h.layer.hidden,true);assert.equal(h.errors.length,1);});
test('server readiness rejection removes preview rather than opening a solo scene',async()=>{const h=setup({failStart:true});h.start();h.move(180,200);await new Promise(resolve=>setImmediate(resolve));assert.equal(h.layer.hidden,true);assert.match(h.errors[0],/both need Our Chat/);});
test('initiator identity is shown without starting a hold on behalf of either user',()=>{const h=setup();h.win.OurTouch.receive(m({starter:'Safy',kind:'hug',done:false,progress:0,hands:{}}));assert.equal(h.layer.hidden,false);assert.equal(h.layer.querySelector('.touch-ending').textContent,'Safy wants to hold you');assert.equal(h.layer.querySelector('.touch-status').textContent,'Touch and hold to join');assert.equal(h.requests.filter(p=>p.action==='hold').length,0);});
test('completion stays indefinitely while either partner still holds',()=>{const h=setup();h.win.OurTouch.receive(m());h.runTimers(1000);h.runTimers(1400);assert.equal(h.layer.hidden,false);h.win.OurTouch.receive(m({hands:{Mahmoud:false,Safy:true}}));h.runTimers(1000);h.runTimers(1400);assert.equal(h.layer.hidden,false);});
test('both releases wait one second, fade for 1.4 seconds, and cannot replay',()=>{const h=setup();const released=m({hands:{Mahmoud:false,Safy:false},releaseAt:10000});h.win.OurTouch.receive(released);h.runTimers(1000);assert.equal(h.layer.classes.has('touch-finishing'),true);assert.equal(h.layer.hidden,false);h.runTimers(1400);assert.equal(h.layer.hidden,true);h.win.OurTouch.receive(released);assert.equal(h.layer.hidden,true);});
test('pressing again cancels pending fade immediately and sends hold after completion',()=>{const h=setup();h.win.OurTouch.receive(m({hands:{},releaseAt:10000}));h.layer.querySelector('.touch-thumb').emit('pointerdown',{pointerId:1});h.runTimers(1000);h.runTimers(1400);assert.equal(h.layer.hidden,false);assert.equal(h.layer.classes.has('touch-finishing'),false);assert.equal(h.requests.at(-1).action,'hold');});
test('partner re-press cancels the scheduled exit on the other screen',()=>{const h=setup();h.win.OurTouch.receive(m({hands:{},releaseAt:10000}));h.win.OurTouch.receive(m({hands:{Mahmoud:false,Safy:true},serverNow:10500}));h.runTimers(1000);h.runTimers(1400);assert.equal(h.layer.hidden,false);});
test('leaving chat hides the scene and prevents late replay',()=>{const h=setup();h.win.OurTouch.receive(m());h.win.OurTouch.tab('together');assert.equal(h.layer.hidden,true);h.win.OurTouch.tab('chat');h.win.OurTouch.receive(m());assert.equal(h.layer.hidden,true);});
test('other device audience is ignored; connection loss closes the active scene',()=>{const h=setup();h.win.OurTouch.receive(m({audience:['different-client']}));assert.equal(h.layer.hidden,true);h.win.OurTouch.receive(m());h.win.OurTouch.connection(false);assert.equal(h.layer.hidden,true);});
test('the completion message is placed before the fingerprint, keeping original fingerprint markup',()=>{const source=readFileSync(new URL('../public/shared-touch.js',import.meta.url),'utf8');assert.match(source,/stage.insertBefore\(ending,stage.firstChild\)/);assert.match(source,/touch-finger touch-filling/);});
test('overlapping left and bottom zones resolve by direction, preserving both gestures',()=>{for(const [dx,dy,kind]of [[160,0,'touch'],[0,-150,'hug']]){const h=setup();h.start(10,390);h.move(10+dx,390+dy);assert.equal(h.requests.at(-1).kind,kind);}});
test('late network responses cannot undo a newer release',()=>{const h=setup();h.win.OurTouch.receive(m({hands:{},releaseAt:10000,serverNow:10100}));h.win.OurTouch.receive(m({hands:{Mahmoud:true,Safy:true},serverNow:9900}));h.runTimers(900);assert.equal(h.layer.classes.has('touch-finishing'),true);});
