import test from 'node:test';import assert from 'node:assert/strict';import {SharedTouch} from '../shared-touch.mjs';
const id='moment-test-001';
function setup(){const s=new SharedTouch(),seq={Mahmoud:0,Safy:0};const action=(who,action,now,extra={})=>s.action(who,who+'-session',{id,action,client:who+'-device',seq:++seq[who],...extra},now);action('Mahmoud','start',0);return {s,action};}
test('only two distinct accounts with live touches fill the moment; completion latches both names',()=>{const {s,action}=setup();for(let t=100;t<=5000;t+=100){action('Mahmoud','hold',t);s.tick(t);}assert.equal(s.view(5000).progress,0);for(let t=5100;t<=9300;t+=100){action('Mahmoud','hold',t);action('Safy','hold',t);s.tick(t);}assert.equal(s.view(9300).done,true);action('Safy','release',9400);assert.deepEqual(s.view(9500).hands,{Mahmoud:true,Safy:true});});
test('expired or disconnected touches cannot finish, and release drains progress',()=>{for(const disconnect of [false,true]){const {s,action}=setup();for(let t=100;t<=2100;t+=100){action('Mahmoud','hold',t);action('Safy','hold',t);s.tick(t);}if(disconnect)s.disconnect('Safy-session',2101);else action('Safy','release',2101);for(let t=2200;t<8000;t+=100){action('Mahmoud','hold',t);s.tick(t);}assert.equal(s.view(8000).done,false);assert.equal(s.view(8000).progress,0);}const {s,action}=setup();action('Mahmoud','hold',100);action('Safy','hold',100);for(let t=200;t<6000;t+=100)s.tick(t);assert.equal(s.view(6000).done,false);assert.equal(s.view(6000).progress,0);});
test('reordered holds and starts after cancellation do not resurrect moments',()=>{const {s,action}=setup();action('Mahmoud','hold',100);action('Mahmoud','release',200);s.action('Mahmoud','Mahmoud-session',{id,client:'Mahmoud-device',seq:2,action:'hold'},210);assert.equal(s.view(210).hands.Mahmoud,false);action('Safy','close',220);action('Mahmoud','start',230);assert.equal(s.view(230),null);});
test('concurrent starts share one session; same-account second devices cannot replace a live touch',()=>{const {s,action}=setup();assert.equal(action('Safy','start',50,{id:'another-moment'}).id,id);action('Mahmoud','hold',100);assert.throws(()=>s.action('Mahmoud','other-session',{id,client:'other-device',seq:1,action:'hold'},200),/another device/);assert.throws(()=>s.action('Echo','fake',{id,client:'fake-device',seq:1,action:'hold'},200),/sign in/);});
test('authenticated endpoint binds touches to accounts, rejects foreign origins, and never writes chat',async()=>{
 const {createApp}=await import('../server.mjs'),{Store}=await import('../store.mjs');process.env.MAHMOUD_EMAIL='mahmoud@example.test';process.env.SAFY_EMAIL='safy@example.test';const db=new Store(':memory:');const users={Mahmoud:{id:'mahmoud-uid',email:process.env.MAHMOUD_EMAIL,email_confirmed_at:'2026-01-01'},Safy:{id:'safy-uid',email:process.env.SAFY_EMAIL,email_confirmed_at:'2026-01-01'}};
 const server=createApp({store:db,origin:'http://localhost',secret:'test shared touch secret over thirty two chars',testing:true,authFetch:async(url,opt)=>{if(url.includes('/token?')){const {email}=JSON.parse(opt.body),name=email===users.Mahmoud.email?'Mahmoud':'Safy';return Response.json({user:users[name],access_token:name,refresh_token:name,expires_in:3600});}return Response.json(users[opt.headers.Authorization.split(' ')[1]]);}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const cookies={};try{
 for(const n of ['Mahmoud','Safy']){const r=await fetch(base+'/api/login',{method:'POST',headers:{Origin:'http://localhost','Content-Type':'application/json'},body:JSON.stringify({email:users[n].email,password:'test-password'})});assert.equal(r.status,200);cookies[n]=r.headers.get('set-cookie').split(';')[0];}
 const post=(name,data,origin='http://localhost')=>fetch(base+'/api/shared-touch',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...(name?{Cookie:cookies[name]}:{})},body:JSON.stringify(data)});
 const data={id:'integration-moment',client:'integration-client',seq:1,action:'start'};assert.equal((await post(null,data)).status,401);assert.equal((await post('Mahmoud',data,'http://evil.test')).status,403);
 const start=await post('Mahmoud',data);assert.equal(start.status,200);assert.equal((await start.json()).moment.starter,'Mahmoud');const own=await post('Mahmoud',{...data,seq:2,action:'hold',who:'Safy'});const one=(await own.json()).moment;assert.equal(one.hands.Mahmoud,true);assert.equal(one.hands.Safy,false);
 const both=await post('Safy',{...data,seq:1,action:'hold'});assert.equal((await both.json()).moment.hands.Safy,true);const closed=await post('Safy',{...data,seq:2,action:'close'});assert.equal((await closed.json()).moment,null);assert.equal(db.messages().length,0);
 }finally{await new Promise(r=>server.close(r));db.close();}
});
