import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){let now=1000,next=0;const requests=[],timers=new Map();
 class Node{constructor(){this.handlers={};this.hidden=false;this.children=[];this.nodes=new Map();this.classes=new Set();this.classList={add:(...x)=>x.forEach(v=>this.classes.add(v)),remove:(...x)=>x.forEach(v=>this.classes.delete(v)),toggle:(x,on)=>on?this.classes.add(x):this.classes.delete(x)};this.style={setProperty(){}};this.clientHeight=500;this.scrollHeight=1000;this.scrollTop=500;this.textContent='';}getBoundingClientRect(){return {top:0,bottom:500,height:500,left:0,right:300};}querySelectorAll(){return [{querySelector:()=>({getBoundingClientRect:()=>({top:380,bottom:420})})}];}setAttribute(){}append(n){this.children.push(n);}remove(){}setPointerCapture(){}closest(){return null;}querySelector(k){if(k==='.touch-hint')return null;if(!this.nodes.has(k))this.nodes.set(k,new Node());return this.nodes.get(k);}addEventListener(t,fn){(this.handlers[t]??=[]).push(fn);}emit(t,e={}){e.preventDefault??=()=>{};e.stopPropagation??=()=>{};e.stopImmediatePropagation??=()=>{};for(const fn of this.handlers[t]||[])fn(e);}}
 const doc=new Node(),win=new Node(),host=new Node(),timeline=new Node(),app=new Node(),chat=new Node();doc.hasFocus=()=>true;doc.hidden=false;doc.createElement=()=>new Node();doc.querySelector=k=>k==='.conversation-window'?host:k==='#timeline'?timeline:k==='#app'?app:k==='#chat'?chat:null;let balloon=false,cancels=0;win.OurBalloon={busy:()=>balloon,cancel:()=>{cancels++;}};
 const context={queueMicrotask,document:doc,window:win,crypto:{randomUUID:()=> 'random-moment-123'},performance:{now:()=>now},setTimeout:fn=>{timers.set(++next,fn);return next;},clearTimeout:id=>timers.delete(id),setInterval:()=>++next,clearInterval(){},requestAnimationFrame:()=>++next,cancelAnimationFrame(){},localStorage:{getItem:()=>true,setItem(){}},fetch:async()=>({}),console};vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/shared-touch.js',import.meta.url),'utf8'),context);win.OurTouch.init({api:async(path,p)=>{if(p.action!=='ready')requests.push(p);return undefined;},error(){}});win.OurTouch.sync({who:'Mahmoud'});const layer=host.children[0];
 const start=()=>timeline.emit('touchstart',{touches:[{clientX:100,clientY:400,identifier:1}],target:timeline});const move=y=>win.emit('touchmove',{touches:[{clientX:100,clientY:y,identifier:1}],cancelable:true});return {win,doc,timeline,layer,requests,start,move,advance:n=>now+=n,balloon:v=>balloon=v,cancels:()=>cancels};}
test('partial pull is local and reversible; full pull starts exactly once without moving chat',()=>{const h=setup();h.start();h.move(340);assert.equal(h.requests.length,0);h.win.emit('touchend');assert.equal(h.layer.hidden,true);h.start();h.move(200);h.move(180);assert.equal(h.requests.filter(p=>p.action==='start').length,1);assert.equal(h.timeline.scrollTop,500);assert.ok(h.cancels()>0);});
test('hold gesture belongs to balloon; older messages and active balloon never start fingerprint',()=>{for(const type of ['hold','older','balloon']){const h=setup();if(type==='older')h.timeline.scrollTop=300;if(type==='balloon')h.balloon(true);h.start();if(type==='hold')h.advance(360);h.move(200);assert.equal(h.requests.length,0);}});
test('remote appearance is automatic, completion keeps both names lit after release, X closes both',()=>{const h=setup();h.win.OurTouch.receive({id:'remote-moment',starter:'Safy',hands:{Mahmoud:false,Safy:true},progress:0,done:false});assert.equal(h.layer.hidden,false);h.win.OurTouch.receive({id:'remote-moment',hands:{Mahmoud:true,Safy:true},progress:1,done:true});h.layer.querySelector('.touch-thumb').emit('pointerup');assert.ok(h.layer.querySelector('[data-touch-name="Mahmoud"]').classes.has('on'));assert.ok(h.layer.querySelector('[data-touch-name="Safy"]').classes.has('on'));h.layer.querySelector('.touch-close').onclick();assert.equal(h.layer.hidden,true);assert.equal(h.requests.at(-1).action,'close');h.win.OurTouch.receive({id:'remote-moment',hands:{},progress:0});assert.equal(h.layer.hidden,true);});

test('fingerprint only starts at or below last bubble top and must reach chat midpoint',()=>{const h=setup();h.timeline.emit('touchstart',{touches:[{clientX:100,clientY:300,identifier:1}],target:h.timeline});h.move(50);assert.equal(h.requests.length,0);h.start();h.move(280);assert.equal(h.requests.length,0);h.move(240);assert.equal(h.requests.length,1);});

test('last bubble text can start fingerprint',()=>{const h=setup();const bubble={closest:selector=>selector.split(',').includes('.bubble')?bubble:null};h.timeline.emit('touchstart',{touches:[{clientX:100,clientY:400,identifier:1}],target:bubble});h.move(240);assert.equal(h.requests.length,1);});
test('start strip tracks last bubble edge and spans the whole viewport width',()=>{for(const [x,y,accepted] of [[2,481,true],[298,490,true],[100,470,false],[100,480,true],[100,500,false],[-1,490,false]]){const h=setup();h.timeline.querySelectorAll=()=>[{querySelector:()=>({getBoundingClientRect:()=>({top:480,bottom:495})})}];h.timeline.emit('touchstart',{touches:[{clientX:x,clientY:y,identifier:1}],target:h.timeline});h.win.emit('touchmove',{touches:[{clientX:x,clientY:240,identifier:1}],cancelable:true});assert.equal(h.requests.length,accepted?1:0,JSON.stringify({x,y}));}});
test('interactive controls, horizontal swipes and stationary bubble holds stay separate',()=>{for(const kind of ['control','horizontal','hold']){const h=setup();const target={closest:()=>kind==='control'?{}:null};h.timeline.emit('touchstart',{touches:[{clientX:100,clientY:400,identifier:1}],target});if(kind==='hold')h.advance(310);if(kind==='horizontal')h.win.emit('touchmove',{touches:[{clientX:140,clientY:396,identifier:1}],cancelable:true});h.move(240);assert.equal(h.requests.length,0,kind);}});

test('leaving chat retains a local scene and blocks late replay on return',()=>{const h=setup();const moment={id:'remote-moment',hands:{},progress:0};h.win.OurTouch.receive(moment);h.win.OurTouch.tab('together');assert.equal(h.layer.hidden,false);h.win.OurTouch.tab('chat');h.win.OurTouch.receive(moment);assert.equal(h.layer.hidden,false);});

test('idle server updates cannot interrupt a pull or a pending start',()=>{const h=setup();h.start();h.move(340);h.win.OurTouch.receive(null);assert.equal(h.layer.hidden,false);h.move(240);assert.equal(h.requests.filter(p=>p.action==='start').length,1);h.win.OurTouch.receive(null);assert.equal(h.layer.hidden,false);});
test('routine stream reconnect keeps the scene; an inactive tab cannot close another tab moment',()=>{const h=setup(),moment={id:'transport-moment',hands:{},progress:0};h.win.OurTouch.receive(moment);h.win.OurTouch.connection(false);assert.equal(h.layer.hidden,false);assert.equal(h.requests.filter(p=>p.action==='close').length,0);const other=setup();other.doc.hidden=true;other.win.OurTouch.receive(moment);assert.equal(other.requests.length,0);assert.equal(other.layer.hidden,true);});

test('partner departure leaves scene open until own X; unsolicited old audience is ignored',()=>{const h=setup();h.win.OurTouch.receive({id:'local-moment',hands:{},progress:.3});h.win.OurTouch.receive(null);assert.equal(h.layer.hidden,false);h.win.OurTouch.receive({id:'late-moment',hands:{},progress:0});assert.equal(h.layer.hidden,false);h.layer.querySelector('.touch-close').onclick();assert.equal(h.layer.hidden,true);const other=setup();other.win.OurTouch.receive({id:'foreign-moment',audience:['another-client'],hands:{},progress:0});assert.equal(other.layer.hidden,true);});
