import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(){let now=1000,next=0;const requests=[],timers=new Map();
 class Node{constructor(){this.handlers={};this.hidden=false;this.children=[];this.nodes=new Map();this.classes=new Set();this.classList={add:(...x)=>x.forEach(v=>this.classes.add(v)),remove:(...x)=>x.forEach(v=>this.classes.delete(v)),toggle:(x,on)=>on?this.classes.add(x):this.classes.delete(x)};this.style={setProperty(){}};this.clientHeight=500;this.scrollHeight=1000;this.scrollTop=500;this.textContent='';}setAttribute(){}append(n){this.children.push(n);}remove(){}setPointerCapture(){}closest(){return null;}querySelector(k){if(k==='.touch-hint')return null;if(!this.nodes.has(k))this.nodes.set(k,new Node());return this.nodes.get(k);}addEventListener(t,fn){(this.handlers[t]??=[]).push(fn);}emit(t,e={}){e.preventDefault??=()=>{};e.stopPropagation??=()=>{};e.stopImmediatePropagation??=()=>{};for(const fn of this.handlers[t]||[])fn(e);}}
 const doc=new Node(),win=new Node(),host=new Node(),timeline=new Node(),app=new Node(),chat=new Node();doc.hasFocus=()=>true;doc.hidden=false;doc.createElement=()=>new Node();doc.querySelector=k=>k==='.conversation-window'?host:k==='#timeline'?timeline:k==='#app'?app:k==='#chat'?chat:null;let balloon=false,cancels=0;win.OurBalloon={busy:()=>balloon,cancel:()=>{cancels++;}};
 const context={document:doc,window:win,crypto:{randomUUID:()=> 'random-moment-123'},performance:{now:()=>now},setTimeout:fn=>{timers.set(++next,fn);return next;},clearTimeout:id=>timers.delete(id),setInterval:()=>++next,clearInterval(){},requestAnimationFrame:()=>++next,cancelAnimationFrame(){},localStorage:{getItem:()=>true,setItem(){}},fetch:async()=>({}),console};vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/shared-touch.js',import.meta.url),'utf8'),context);win.OurTouch.init({api:async(path,p)=>{requests.push(p);return undefined;},error(){}});win.OurTouch.sync({who:'Mahmoud'});const layer=host.children[0];
 const start=()=>timeline.emit('touchstart',{touches:[{clientX:100,clientY:400,identifier:1}],target:timeline});const move=y=>win.emit('touchmove',{touches:[{clientX:100,clientY:y,identifier:1}],cancelable:true});return {win,doc,timeline,layer,requests,start,move,advance:n=>now+=n,balloon:v=>balloon=v,cancels:()=>cancels};}
test('partial pull is local and reversible; full pull starts exactly once without moving chat',()=>{const h=setup();h.start();h.move(340);assert.equal(h.requests.length,0);h.win.emit('touchend');assert.equal(h.layer.hidden,true);h.start();h.move(200);h.move(180);assert.equal(h.requests.filter(p=>p.action==='start').length,1);assert.equal(h.timeline.scrollTop,500);assert.ok(h.cancels()>0);});
test('hold gesture belongs to balloon; older messages and active balloon never start fingerprint',()=>{for(const type of ['hold','older','balloon']){const h=setup();if(type==='older')h.timeline.scrollTop=300;if(type==='balloon')h.balloon(true);h.start();if(type==='hold')h.advance(360);h.move(200);assert.equal(h.requests.length,0);}});
test('remote appearance is automatic, completion keeps both names lit after release, X closes both',()=>{const h=setup();h.win.OurTouch.receive({id:'remote-moment',starter:'Safy',hands:{Mahmoud:false,Safy:true},progress:0,done:false});assert.equal(h.layer.hidden,false);h.win.OurTouch.receive({id:'remote-moment',hands:{Mahmoud:true,Safy:true},progress:1,done:true});h.layer.querySelector('.touch-thumb').emit('pointerup');assert.ok(h.layer.querySelector('[data-touch-name="Mahmoud"]').classes.has('on'));assert.ok(h.layer.querySelector('[data-touch-name="Safy"]').classes.has('on'));h.layer.querySelector('.touch-close').onclick();assert.equal(h.layer.hidden,true);assert.equal(h.requests.at(-1).action,'close');h.win.OurTouch.receive({id:'remote-moment',hands:{},progress:0});assert.equal(h.layer.hidden,true);});
