import test from 'node:test';import assert from 'node:assert/strict';
import {initial,change,project} from '../domain.mjs';import {Store} from '../store.mjs';import {composePost,composeOptions} from '../space-compose.mjs';
const activity={kind:'case',difficulty:'medium',hints:['Compare the times.','One clock was stopped.','Check who could hear the bell.'],answer:'The curator',explanation:'Only the curator knew the clock had stopped.'};
const make=()=>{const s=initial();change(s,'Mahmoud','item.save',{type:'Discussion',title:'A fictional case with enough clues to solve together.',activity});return s;};
test('solution and unopened hints stay out of each partner snapshot; reveal does not spoil partner',()=>{const s=make(),id=s.items[0].id;assert.equal(project(s,'Mahmoud').items[0].activity,undefined);assert.equal(project(s,'Mahmoud').items[0].play.answer,undefined);assert.deepEqual(project(s,'Safy').items[0].play.hints,[]);change(s,'Mahmoud','item.play',{id,action:'hint',expected:0});assert.deepEqual(project(s,'Mahmoud').items[0].play.hints,[activity.hints[0]]);assert.deepEqual(project(s,'Safy').items[0].play.hints,[]);assert.throws(()=>change(s,'Mahmoud','item.play',{id,action:'hint',expected:0}),/changed/);change(s,'Mahmoud','item.play',{id,action:'reveal'});assert.equal(project(s,'Mahmoud').items[0].play.answer,activity.answer);assert.equal(project(s,'Safy').items[0].play.answer,undefined);});
test('shared guesses and hint progress survive storage; editing cannot invalidate a published solution',()=>{const s=make(),id=s.items[0].id;change(s,'Safy','item.comment',{id,text:'Could it be the curator?'});change(s,'Safy','item.play',{id,action:'hint',expected:0});const store=new Store(':memory:');try{store.save(s);const restored=store.state();assert.equal(restored.items[0].comments[0].by,'Safy');assert.equal(project(restored,'Safy').items[0].play.hints.length,1);assert.throws(()=>change(restored,'Mahmoud','item.save',{id,revision:restored.items[0].revision,type:'Discussion',title:'Changed clues'}),/clues/);}finally{store.close();}});
test('malformed activities cannot be published',()=>{for(const bad of [{...activity,hints:[]},{...activity,answer:''},{...activity,difficulty:'impossible'}])assert.throws(()=>change(initial(),'Mahmoud','item.save',{type:'Discussion',title:'A shared puzzle to enjoy together',activity:bad}));});
const result=text=>({status:'completed',usage:{input_tokens:10,output_tokens:20},output:[{type:'message',content:[{type:'output_text',text}]}]});process.env.OPENAI_API_KEY='local-test-only';
test('case writer returns structured secrets and reviewer receives the full solution to verify',async()=>{const calls=[];const r=await composePost({options:{kind:'case',difficulty:'hard'},fetcher:async(_,o)=>{const b=JSON.parse(o.body);calls.push(b);return Response.json(result(calls.length===1?JSON.stringify({title:'A stopped clock, three suspects, and the museum bell. Who took the painting?',...activity}):JSON.stringify({approve:true,reason:'Checked clues and unique solution.'})));}});assert.equal(r.proposals[0].activity.difficulty,'hard');const verified=JSON.parse(calls[0].input).verifiedSolution;assert.equal(r.proposals[0].activity.answer,verified.answer);assert.equal(JSON.parse(calls[1].input).candidate.activity.answer,verified.answer);assert.match(r.proposals[0].title,/Verified evidence/);assert.match(calls[1].instructions,/independently solve/);});
test('story brief requires complete arc and respects character selection',async()=>{for(const characters of ['independent','us']){let calls=0,brief='';await composePost({options:{kind:'story',genre:'adventure',characters},fetcher:async(_,o)=>{const b=JSON.parse(o.body);if(++calls===1)brief=b.instructions;return Response.json(result(calls===1?'DATE: none\nThe explorer found the missing map, returned the stolen compass and guided everyone home before the storm.':JSON.stringify({approve:true,reason:'Complete.'})));}});assert.match(brief,/90–150/);assert.match(brief,/satisfying ending/);assert.match(brief,/Genre: adventure/);assert.match(brief,characters==='us'?/protagonists may be Mahmoud and Safy/:/do not insert Mahmoud or Safy/);}assert.throws(()=>composeOptions({genre:'invalid'}));});
test('editor rejection prevents publishing an unsolvable case',async()=>{let calls=0;await assert.rejects(composePost({options:{kind:'case'},fetcher:async()=>Response.json(result(++calls%2===1?JSON.stringify({title:'A case with several suspects and incomplete evidence.',...activity}):JSON.stringify({approve:false,reason:'Two suspects fit all clues.'})))}),/Two suspects/);});

test('one bounded repair uses editorial feedback and accounts for both attempts',async()=>{const calls=[];const r=await composePost({options:{kind:'case'},fetcher:async(_,o)=>{const b=JSON.parse(o.body);calls.push(b);return Response.json(result(calls.length%2===1?JSON.stringify({title:'A complete case with a timeline and enough evidence to solve.',...activity}):JSON.stringify({approve:calls.length===4,reason:calls.length===2?'The timeline leaves two suspects.':'Unique solution.'})));}});assert.equal(calls.length,4);assert.equal(JSON.parse(calls[2].input).editorialFeedback,'The timeline leaves two suspects.');assert.equal(r.usage.input_tokens,40);assert.equal(r.usage.output_tokens,80);});

test('generated mystery evidence gives exactly one matching suspect at each difficulty',async()=>{const {mysteryProof}=await import('../mystery-proof.mjs');for(const difficulty of ['easy','medium','hard'])for(let n=0;n<30;n++){const p=mysteryProof(difficulty),lines=p.activity.explanation.split('\n');assert.equal(lines.filter(x=>x.endsWith('matches all recorded clues.')).length,1);assert.ok(lines.some(x=>x===p.activity.answer+': matches all recorded clues.'));}});
