import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';
function setup(){
 class Node{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.events={};this.hidden=false;this.textContent='';this.value='';}append(n){this.children.push(n);n.parent=this;}setAttribute(k,v){this[k]=v;}addEventListener(k,f){this.events[k]=f;}replaceChildren(){this.children=[];}remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}showModal(){this.open=true;}close(){this.open=false;this.events.close?.();}focus(){}click(){return this.onclick?.();}}
 const root=new Node('div'),trigger=new Node('button'),rows=[],calls=[];let who='Mahmoud',rev=0,fail=false;const context={document:{createElement:t=>new Node(t),createElementNS:(_,t)=>new Node(t),querySelector:q=>q==='#our-place-trial'?root:trigger},crypto:{randomUUID}};context.window=context;vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/files.js',import.meta.url),'utf8'),context);
 context.OurFiles.init({getState:()=>({who}),api:async(path,d)=>{if(path==='files')return {items:rows.map(i=>({...i})),revision:rev};calls.push(d);if(fail)throw Error('This item changed');if(d.action==='create')rows.push({id:randomUUID(),parent:d.parent,kind:d.kind,name:d.name,note:d.note,owner:who,revision:1});else if(d.action==='edit'){const i=rows.find(i=>i.id===d.item);i.note=d.note;i.name=d.name;i.revision++;}rev++;return {};}});
 const walk=n=>[n,...n.children.flatMap(walk)],button=name=>walk(root).find(n=>n.tag==='button'&&(n['aria-label']===name||n.textContent===name)),form=()=>walk(root).find(n=>n.tag==='form'),fields=()=>walk(root).filter(n=>['input','textarea'].includes(n.tag)&&n['aria-label']!=='Find in this folder');
 return {root,trigger,rows,calls,ui:context.OurFiles,button,form,fields,walk,fail:()=>fail=true,switch:()=>who='Safy'};
}
test('folder UI creates a folder, enters it, saves an Arabic note and keeps conflicted edits visible',async()=>{const t=setup();await t.trigger.click();t.button('Add folder, note or files').click();t.button('New folder').click();t.fields()[0].value='Our trip';await t.form().onsubmit({preventDefault(){}});assert.equal(t.rows.length,1);t.button('Our trip').click();t.button('Add folder, note or files').click();t.button('New note').click();t.fields()[0].value='Plan';t.fields()[1].value='رحلتنا';await t.form().onsubmit({preventDefault(){}});assert.equal(t.rows[1].parent,t.rows[0].id);assert.equal(t.rows[1].note,'رحلتنا');t.button('Plan').click();t.fields()[1].value='My unsaved change';t.fail();await t.form().onsubmit({preventDefault(){}});assert.equal(t.fields()[1].value,'My unsaved change');assert.ok(t.walk(t.root).some(n=>n.textContent==='This item changed'));t.ui.reset();assert.equal(t.walk(t.root).filter(n=>n.open).length,0);});
test('save-from-chat uses a folder picker with an immediately available cancel and stable request ID on retry',async()=>{const t=setup();await t.ui.saveMessage({id:'original'});assert.equal(t.button('Cancel').hidden,false);assert.equal(t.button('Save here').hidden,false);t.fail();await t.button('Save here').click();await t.button('Save here').click();assert.equal(t.calls.length,2);assert.equal(t.calls[0].id,t.calls[1].id);assert.equal(t.calls[0].message,'original');t.button('Cancel').click();assert.equal(t.button('Save here').hidden,true);assert.equal(t.button('Add folder, note or files').hidden,false);});
