import test from 'node:test';
import assert from 'node:assert/strict';
import {composeOptions,composePost} from '../space-compose.mjs';
import {Store} from '../store.mjs';
import {DailyWall} from '../daily.mjs';
import {attentionEvents} from '../push-events.mjs';
process.env.OPENAI_API_KEY='local-test-only';
const result=text=>({status:'completed',usage:{input_tokens:10,output_tokens:20},output:[{type:'message',content:[{type:'output_text',text}]}]});
test('factual genres always require research; invalid options rejected',()=>{for(const kind of ['facts','science','news','books'])assert.equal(composeOptions({kind}).research,true);assert.equal(composeOptions({kind:'romance'}).research,false);assert.equal(composeOptions({sources:'include'}).research,true);assert.throws(()=>composeOptions({kind:'other'}));});
test('manual generation returns only a reviewed draft and carries the chosen brief',async()=>{const calls=[];const r=await composePost({options:{kind:'plan',length:'long',tone:'playful'},fetcher:async(_,o)=>{const b=JSON.parse(o.body);calls.push(b);return Response.json(calls.length===1?result('DATE: none\nChoose a play together, make a snack each, and save ten minutes afterwards to compare your favourite scenes.'):result(JSON.stringify({approve:true,reason:'Specific shared plan.'})));}});assert.equal(r.proposals[0].itemType,'Plan');assert.equal(r.usage.input_tokens,20);assert.match(calls[0].instructions,/140–240/);assert.match(JSON.parse(calls[1].input).brief,/Something to do together/);});
test('near-identical puzzle with changed numbers is rejected without fallback',async()=>{const text='A small puzzle for tonight: three sealed boxes each contain a different number of coins. A and B together contain 117; A and C contain 123; B and C contain 130. How many coins are in each box?';await assert.rejects(composePost({options:{kind:'puzzle'},history:[text.replace('117','113').replace('123','119').replace('130','126')],fetcher:async()=>Response.json(result(JSON.stringify({title:text,hints:['Look at the sums.','Combine two totals.','Subtract the third total.'],answer:'57, 60, 66',explanation:'Solve the three equations.'})))}),/similar/);});
test('news without live search or sources cannot become a draft',async()=>{await assert.rejects(composePost({options:{kind:'news'},fetcher:async()=>Response.json(result('DATE: 2026-09-27\nAn interesting new discovery was announced today but there is no source.'))}),/search|source/i);});
test('manual-only mode disables persisted schedule and blocks reserve and publish',async()=>{const store=new Store(':memory:');try{const d=new DailyWall(store,{manualOnly:true,generate:()=>{throw Error('must not generate');}});assert.equal(store.state().daily.enabled,false);assert.equal(store.state().daily.manualOnly,true);assert.equal(d.reserve({}),false);assert.equal(d.publish({},{}),false);await d.tick();assert.equal(store.state().items.length,0);}finally{store.close();}});
test('published posts notify only the other partner in both directions; drafts do not notify',()=>{for(const by of ['Mahmoud','Safy']){const before={items:[]},after={items:[{id:'post',by,title:'A reviewed Echo draft',comments:[]}]};const e=attentionEvents(before,after,by);assert.equal(e.length,1);assert.equal(e[0].to,by==='Mahmoud'?'Safy':'Mahmoud');assert.equal(e[0].target.post,'post');assert.deepEqual(attentionEvents(after,after,by),[]);assert.deepEqual(attentionEvents(before,{...before,proposals:[{title:'Not published'}]},by),[]);}});
test('a locally rejected duplicate automatically receives one fresh attempt with combined billing',async()=>{
 const duplicate='Choose a play together, make a snack each, and save ten minutes afterwards to compare your favourite scenes.';let calls=0;
 const r=await composePost({options:{kind:'plan'},history:[duplicate],fetcher:async(_,o)=>{const body=JSON.parse(o.body);calls++;if(calls===1)return Response.json(result('DATE: none\n'+duplicate));if(calls===2){assert.match(JSON.parse(body.input).editorialFeedback,/Repeated/);return Response.json(result('DATE: none\nBuild a tiny photo scavenger hunt: each hide three visual clues in pictures from your room, then swap and discover the secret object.'));}return Response.json(result(JSON.stringify({approve:true,reason:'Distinct activity.'})));}});
 assert.equal(calls,3);assert.equal(r.usage.input_tokens,30);assert.match(r.proposals[0].title,/scavenger/);
});
test('case evidence rotates away from the recent mechanism and every new mechanism has a justified answer',async()=>{
 const {diverseMysteryProof}=await import('../mystery-proof.mjs');const a=diverseMysteryProof('easy'),b=diverseMysteryProof('easy',[a.facts]),c=diverseMysteryProof('easy',[b.facts,a.facts]);assert.equal(new Set([a.family,b.family,c.family]).size,3);
 for(const p of [a,b,c]){assert.equal(p.activity.hints.length,3);assert.ok(p.facts.includes(p.activity.answer));assert.ok(p.activity.explanation.includes(p.activity.answer));}
 assert.notEqual(diverseMysteryProof('easy',[],a.family).family,a.family);
});

test('non-timeline cases do not inherit a timeline-only reviewer requirement',async()=>{
 let calls=0;await composePost({options:{kind:'case',difficulty:'easy'},history:['Timeline clues'],fetcher:async(_,o)=>{const b=JSON.parse(o.body),input=JSON.parse(b.input);calls++;if(calls===1){assert.match(b.instructions,/finite timeline is required only/i);return Response.json(result(JSON.stringify({title:'At a small theatre, the final script disappears just before rehearsal. Four crew members give conflicting accounts. Read the verified records below and decide together which account reveals the person responsible.',...input.verifiedSolution})));}assert.match(input.brief,/do not require a timeline/);return Response.json(result(JSON.stringify({approve:true,reason:'Unique solution under the stated evidence.'})));}});assert.equal(calls,2);
});
