import {events} from './ai.mjs';
import {LIGHT_MODEL as MODEL} from './ai-models.mjs';
import {check} from './domain.mjs';
import {drawDeck} from './draw.mjs';
export async function drawingWords({context,signal,fetcher=fetch}){
 const word={type:'object',additionalProperties:false,properties:{word:{type:'string'},hint:{type:'string'},answers:{type:'array',items:{type:'string'}}},required:['word','hint','answers']};
 const response=await fetcher('https://api.openai.com/v1/responses',{method:'POST',signal,headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,store:false,stream:true,max_output_tokens:1800,instructions:'Prepare exactly six distinct fair Pictionary words for two adults. Use the requested language and difficulty. Concrete drawable objects, animals or actions, no spelling challenges or private references. All six must have comparable difficulty. Each hint is a broad category, never the word or an obvious synonym. Include up to six common spelling variants/synonyms as accepted answers, including common Egyptian Arabic forms for Arabic. Keep words under 60 characters and hints under 120. Use drawing_words once.',input:JSON.stringify(context),tools:[{type:'function',name:'drawing_words',strict:true,description:'Prepare a hidden six-round word deck.',parameters:{type:'object',additionalProperties:false,properties:{words:{type:'array',items:word}},required:['words']}}],tool_choice:{type:'function',name:'drawing_words'},parallel_tool_calls:false})});
 check(response.ok,'Echo could not prepare the words.',502);let done;for await(const e of events(response.body)){if(e.type==='response.completed')done=e.response;if(['error','response.failed','response.incomplete'].includes(e.type))throw Error('Incomplete word deck.');}const calls=done?.output?.filter(o=>o.type==='function_call'&&o.name==='drawing_words');check(calls?.length===1,'Echo did not finish the words.',502);const result=JSON.parse(calls[0].arguments).words;drawDeck(result);return {result,usage:done.usage};
}
