import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
// Export the built React interface for offline review, without hosting or credentials.
const destination=process.argv[2];
if(!destination)throw Error('Provide an output HTML path. Build with vite.preview.config.ts first.');
let html=await readFile('dist-preview/preview.html','utf8');
const js=html.match(/<script[^>]*src="([^"]+)"[^>]*><\/script>/);
const css=html.match(/<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/);
if(!js||!css)throw Error('Expected a single built script and stylesheet.');
const code=await readFile(resolve('dist-preview',js[1].replace(/^\//,'')),'utf8');
const style=await readFile(resolve('dist-preview',css[1].replace(/^\//,'')),'utf8');
if(/@import/.test(style))throw Error('Offline preview must not depend on external stylesheets.');
if(/\bimport\s*\(/.test(code)||/^\s*(?:import|export)\s/m.test(code))throw Error('Expected a self-contained script.');
html=html.replace(js[0],'');
html=html.replace('</body>',()=>'<script>'+code.replace(/<\/script/gi,'<\\/script')+'</script></body>');
html=html.replace(css[0],()=>'<style>'+style+'</style>');
html=html.replace(/<link[^>]*rel="icon"[^>]*>/,'');
html=html.replace('<head>','<head><meta name="referrer" content="no-referrer">');
await writeFile(destination,html);
console.log('Offline design preview exported:',destination);
