import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,ChevronRight,Compass,Eye,FileText,Heart,LockKeyhole,MessageCircle,MoreHorizontal,Pause,Pencil,Plus,Send,Settings2,Sparkles,Undo2,X} from 'lucide-react';
import {act,startGame,projectGame, type Game} from '../server/game';
import './design-preview.css';

type View='room'|'us'|'plan'|'prep';
type Activity='case'|'draw'|'secret'|'adventure'|'judge';
type Stroke={color:string;points:{x:number;y:number}[]};
const evidence=[
 {title:'The room log',label:'01 · Timeline',text:'الرسالة كانت في المكتب ٨:١٠. سليم خرج ٨:١٢ ولم يرجع. ليلى دخلت ٨:١٦ وخرجت ٨:١٧. عمر دخل ٨:٢٠.'},
 {title:'The stopped clock',label:'02 · Observation',text:'ساعة الحائط متأخرة ١٠ دقائق. الشاهد سمع الدرج بيتفتح لما الساعة كانت بتقول ٨:٠٦. يبقى الوقت الحقيقي كام؟'},
 {title:'The envelope',label:'03 · Shared evidence',text:'المظروف اتلاقى في صندوق التصليح ومعاه ورقة: «أخذته عشان أصلّح الظرف الممزق». الخط يطابق عينة خط ليلى.'},
];
const activities:{id:Activity;title:string;description:string;icon:React.ElementType}[]=[
 {id:'case',title:'Investigate together',description:'Evidence, secrets and a shared conclusion.',icon:FileText},
 {id:'draw',title:'Draw something',description:'A canvas for two. A line at a time.',icon:Pencil},
 {id:'secret',title:'Read my mind',description:'Choose a secret. Guess theirs.',icon:Eye},
 {id:'adventure',title:'Follow a story',description:'Explore a world shaped by your choices.',icon:Compass},
 {id:'judge',title:'Hear both sides',description:'Make space for two perspectives.',icon:MessageCircle},
];
export default function DesignPreview(){
 const [view,setView]=useState<View>('room'),[activity,setActivity]=useState<Activity>('case'),[chat,setChat]=useState(false),[explore,setExplore]=useState(false),[paused,setPaused]=useState(false),[ask,setAsk]=useState(false),[settings,setSettings]=useState(false),[notice,setNotice]=useState('');
 const [messages,setMessages]=useState([{who:'Safy',text:'أنا هنا.. نكمّل القضية من آخر دليل؟'},{who:'AI',text:'الساعة وسجل الدخول قدامكم. قارنوا التوقيتين قبل ما تثبتوا الإجابة.'}]),[message,setMessage]=useState('');
 const [clue,setClue]=useState(0),[accused,setAccused]=useState(''),[revealed,setRevealed]=useState(false),[secretShared,setSecretShared]=useState(false),[privateClue,setPrivateClue]=useState(false);
 const [usTab,setUsTab]=useState('dreams'),[wish,setWish]=useState(''),[wishes,setWishes]=useState(['Aswan, together','A night under the stars']),[addWish,setAddWish]=useState(false),[selectedWish,setSelectedWish]=useState('Aswan, together'),[planning,setPlanning]=useState(false),[planNote,setPlanNote]=useState('نفسي نروح أسوان ونقضي وقت هادي سوا.'),[days,setDays]=useState(['الوصول وقعدة على النيل','يوم استكشاف نختار تفاصيله سوا','صباح هادي قبل الرجوع']),[done,setDone]=useState<boolean[]>([false,false]),[prep,setPrep]=useState(''),[publishPreview,setPublishPreview]=useState(false),[keeps,setKeeps]=useState<{title:string;text:string}[]>([]);
 const [strokes,setStrokes]=useState<Stroke[]>([]),[color,setColor]=useState('#d6b984'),[word,setWord]=useState(''),[words,setWords]=useState<string[]>([]),[drawingSaved,setDrawingSaved]=useState(false);
 const [game,setGame]=useState<Game|null>(null),[number,setNumber]=useState<number|null>(null),[chapter,setChapter]=useState(0),[judgment,setJudgment]=useState(false),[sides,setSides]=useState(['اتضايقت إن الخطة اتغيّرت من غير ما أعرف بدري.','كنت مرهقة ومش عارفة أشرح ده وقتها.']);
 const canvas=useRef<HTMLCanvasElement>(null),stroke=useRef<Stroke|null>(null),dialog=useRef<HTMLDialogElement>(null);
 const visibleGame=game?projectGame(game,'m'):null;
 function toast(s:string){setNotice(s)}
 function open(v:View){setView(v);setNotice('');setChat(false)}
 function choose(a:Activity){setActivity(a);setExplore(false);open('room')}
 function addMessage(who:string,text:string){setMessages(m=>[...m,{who,text}])}
 useEffect(()=>{if(explore){dialog.current?.showModal()}else dialog.current?.close()},[explore]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(timer)},[notice]);
 function paint(){const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);for(const s of [...strokes,...(stroke.current?[stroke.current]:[])]){ctx.strokeStyle=s.color;ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}ctx.font='28px sans-serif';ctx.textAlign='center';ctx.fillStyle='#ede5df';words.forEach((t,i)=>ctx.fillText(t,450,200+i*42,800))}
 useEffect(paint,[strokes,words,view,activity]);
 function point(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*900/r.width,y:(e.clientY-r.top)*540/r.height}}
 function startSecret(){let g=startGame(crypto.randomUUID(),['m','s']);g=act(act(g,'m','game.ready'),'s','game.ready');g=act(g,'s','game.secret',1+Math.floor(Math.random()*10));setGame(g);setNumber(null)}
 function gameMove(){if(!game)return;let g=game;if(g.phase==='secrets'&&number){g=act(g,'m','game.secret',number)}else if(g.phase==='guesses'&&number){g=act(g,'s','game.guess',1+Math.floor(Math.random()*10));g=act(g,'m','game.guess',number)}else if(g.phase==='reveal'){g=act(act(g,'m','game.next'),'s','game.next');g=act(g,'s','game.secret',1+Math.floor(Math.random()*10))}setGame(g);setNumber(null)}
 function send(e:React.FormEvent){e.preventDefault();if(!message.trim())return;addMessage('Mahmoud',message.trim());if(ask)addMessage('AI','ده رد توضيحي فقط. في النسخة المتصلة هرد على كلامك والنشاط المفتوح؛ طلبك هنا ما اتبعتش لأي نموذج.');setMessage('');setAsk(false)}
 const activeTitle=activities.find(a=>a.id===activity)!.title;
 return <div className="dp">
  <div className="dp-preview">Interactive design preview <span>•</span> Sample data · no live AI</div>
  <header className="dp-header"><button className="dp-brand" onClick={()=>open('room')} aria-label="Mahmoud and Safy room">m<span>×</span>s</button><nav aria-label="Main navigation"><button className={view==='room'?'selected':''} onClick={()=>open('room')}>Room</button><button className={view==='us'||view==='plan'?'selected':''} onClick={()=>open('us')}>Us</button></nav><button className="dp-icon" aria-label="Settings" onClick={()=>setSettings(!settings)}><Settings2 size={20}/></button></header>
  {settings&&<section className="dp-settings"><div className="dp-between"><h2>Your boundaries</h2><button className="dp-icon" onClick={()=>setSettings(false)} aria-label="Close settings"><X/></button></div><p>Just Us pauses AI initiative across Room and Us. Ask once keeps it paused.</p><button onClick={()=>setPaused(!paused)}>{paused?'Resume my permission':'Turn on Just Us'}</button><p className="dp-sub">Preview preferences only. Nothing changes on your account.</p></section>}
  <div className={'dp-layout '+(chat&&view!=='prep'?'with-chat':'')}>
   <main className="dp-main">
   {view==='room'&&<>
    <div className="dp-roomline"><div className="dp-people"><span className="dp-avatar">M</span><span className="dp-avatar rose">S</span><span>Our room<small>Sample presence</small></span></div><button className={'dp-presence '+(paused?'is-paused':'')} onClick={()=>setPaused(!paused)}>{paused?<LockKeyhole size={15}/>:<Sparkles size={15}/>}<span>{paused?'Just Us · Resume':'Just Us'}</span></button></div>
    <section className="dp-stage">
     <div className="dp-stagebar"><span><span className="dp-dot"/>{activeTitle}</span><button onClick={()=>setExplore(true)}>Change activity <ChevronRight size={16}/></button></div>
     {activity==='case'&&<div className="dp-case"><div className="dp-title"><span className="dp-kicker">CASE 01 / FICTION</span><h1>The missing letter</h1><p dir="rtl">رسالة اختفت. ثلاثة أشخاص. وتوقيت واحد محتاج تراجعه.</p></div>
      <div className="dp-investigation"><nav className="dp-evidence" aria-label="Case evidence">{evidence.map((c,i)=><button key={c.title} className={clue===i?'selected':''} onClick={()=>setClue(i)}><span className="dp-evidence-num">0{i+1}</span><span>{c.title}<small>{i===clue?'Reading now':'Open evidence'}</small></span><ChevronRight size={15}/></button>)}</nav><article className="dp-paper"><span className="dp-kicker">{evidence[clue].label}</span><h2>{evidence[clue].title}</h2><p dir="rtl">{evidence[clue].text}</p><div className="dp-paperfoot"><BookOpen size={16}/><span>Both of you can explore independently</span></div></article></div>
      <div className="dp-private"><button onClick={()=>setPrivateClue(!privateClue)}><LockKeyhole size={15}/>Your private clue <span>{privateClue?'Hide':'Open'}</span></button>{privateClue&&<div><p dir="rtl">الشاهد شاف ليلى تخرج بمظروف الساعة ٨:١٧.</p><button disabled={secretShared} onClick={()=>{setSecretShared(true);addMessage('Mahmoud','دليلي: الشاهد شاف ليلى تخرج بمظروف الساعة ٨:١٧.');setChat(true)}}>{secretShared?'Shared in conversation':'Share this clue'}</button><small>Local privacy demonstration only</small></div>}</div>
      <div className="dp-case-action"><label>Our conclusion<select value={accused} onChange={e=>setAccused(e.target.value)} disabled={revealed}><option value="">Choose a suspect</option><option>Salim</option><option>Layla</option><option>Omar</option></select></label><button className="dp-primary" disabled={!accused||revealed} onClick={()=>{setRevealed(true);setKeeps(k=>[...k,{title:'The missing letter',text:'Completed · Accused '+accused+' · Answer: Layla'}])}}>{revealed?'Conclusion saved':'Lock & reveal'}<ArrowRight size={17}/></button></div>
      {revealed&&<div className="dp-result" role="status"><h3>{accused==='Layla'?'You connected the clues.':'The answer is Layla.'}</h3><p dir="rtl">٨:٠٦ على الساعة المتأخرة = ٨:١٦ فعلًا. ليلى كانت بالمكتب، والمظروف وخط الملاحظة يؤكدان النتيجة.</p></div>}
     </div>}
     {activity==='draw'&&<div className="dp-draw"><div className="dp-title"><span className="dp-kicker">CREATE / TOGETHER</span><h1>A line between us</h1><p>Room to draw. Space to make it yours.</p></div><div className="dp-drawtools"><div>{['#d6b984','#d497ac','#ede5df'].map((c,i)=><button key={c} aria-label={['Gold pen','Rose pen','Ivory pen'][i]} aria-pressed={c===color} className={c===color?'selected':''} onClick={()=>setColor(c)}><span style={{background:c}}/></button>)}</div><button onClick={()=>setStrokes(s=>s.slice(0,-1))} disabled={!strokes.length}><Undo2 size={17}/>Undo</button></div><canvas ref={canvas} width={900} height={540} aria-label="Draw using your finger or mouse. Add words below as a keyboard alternative." onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);stroke.current={color,points:[point(e)]};paint()}} onPointerMove={e=>{if(stroke.current){stroke.current.points.push(point(e));paint()}}} onPointerUp={()=>{if(stroke.current){const s=stroke.current;stroke.current=null;setStrokes(a=>[...a,s])}}} onPointerCancel={()=>{stroke.current=null;paint()}}/>
      <div className="dp-drawbottom"><form onSubmit={e=>{e.preventDefault();if(word.trim()){setWords(w=>[...w,word.trim()]);setWord('')}}}><input value={word} onChange={e=>setWord(e.target.value)} placeholder="Add a word…" aria-label="Word for your drawing" maxLength={40}/><button>Add</button></form><button className="dp-primary" onClick={()=>{setDrawingSaved(true);toast('Drawing kept in Us for this preview.')}}><Heart size={16}/>{drawingSaved?'Kept in Us':'Keep in Us'}</button></div><p className="dp-sub">Local canvas · partner drawing and AI recognition are not connected.</p></div>}
     {activity==='secret'&&<div className="dp-game"><div className="dp-title"><span className="dp-kicker">PLAY / {game?'ROUND '+game.round+' OF 3':'FOR TWO'}</span><h1>Read my mind</h1><p>Two secrets. A little intuition.</p></div>{!game?<><p dir="rtl">اختار رقم من ١ لـ١٠ وخمّن رقم صافي. التخمين الصح بـ٣ نقاط، والفرق واحد بنقطة. صافي محاكاة عشوائية هنا.</p><button className="dp-primary" onClick={startSecret}>Ready to play<ArrowRight size={16}/></button></>:<><div className="dp-score"><span>Mahmoud <b>{game.scores.m}</b></span><span>Safy <b>{game.scores.s}</b></span></div>{['secrets','guesses'].includes(game.phase)?<><h2>{game.phase==='secrets'?'Choose your secret':'What did Safy choose?'}</h2><p className="dp-sub">{game.phase==='secrets'?'Safy’s secret has been locked.':'Your secret: '+visibleGame?.mySecret}</p><div className="dp-numbers">{Array.from({length:10},(_,i)=>i+1).map(n=><button className={number===n?'selected':''} key={n} onClick={()=>setNumber(n)}>{n}</button>)}</div><button className="dp-primary" onClick={gameMove} disabled={!number}>{game.phase==='secrets'?'Lock my secret':'Lock & reveal'}<LockKeyhole size={16}/></button></>:<><div className="dp-reveal"><div><small>Safy’s secret</small><b>{game.reveal?.secrets.s}</b><span>You guessed {game.reveal?.guesses.m} · +{game.reveal?.points.m}</span></div><div><small>Your secret</small><b>{game.reveal?.secrets.m}</b><span>Safy guessed {game.reveal?.guesses.s} · +{game.reveal?.points.s}</span></div></div>{game.phase==='complete'?<><h2>{game.scores.m===game.scores.s?'A tie.':game.scores.m>game.scores.s?'Mahmoud wins.':'Safy wins.'}</h2><button className="dp-primary" onClick={()=>{setKeeps(k=>[...k,{title:'Read my mind',text:`Completed · Mahmoud ${game.scores.m} / Safy ${game.scores.s}`}]);open('us');setUsTab('moments');setGame(null)}}>Keep result & finish</button></>:<button className="dp-primary" onClick={gameMove}>Next round<ArrowRight size={16}/></button>}</>}</>}</div>}
     {activity==='adventure'&&<div className="dp-story"><div className="dp-title"><span className="dp-kicker">A SHARED WORLD / CHAPTER 01</span><h1>Beyond the last door</h1></div><article><span className="dp-chapter">0{chapter+1}</span><p dir="rtl">{['بيت قديم على النيل، ورسالة متوجهة ليكم بتاريخ بكرة. الباب مقفول وفي المدخل شباك وصندوق. تفتحوا الصندوق ولا تفحصوا الشباك؟','في الصندوق ورقة: «المفتاح عند الشيء اللي بيشوف كل المسافرين وهو ثابت مكانه». ترجّحوا الشباك؟','خلف إطار الشباك لقيتوا مفتاحًا ورسالة: «الرحلة تبدأ باثنين». فتحتم الباب سوا. نهاية الفرع التجريبي.'][chapter]}</p></article><div className="dp-actions">{chapter<2?<><button className="dp-primary" onClick={()=>setChapter(2)}>Examine the window</button>{chapter===0&&<button onClick={()=>setChapter(1)}>Open the box</button>}</>:<button className="dp-primary" onClick={()=>{setKeeps(k=>[...k,{title:'Beyond the last door',text:'Chapter 1 completed · Window key found'}]);open('us');setUsTab('moments')}}>Keep this chapter</button>}</div><p className="dp-sub">A scripted story sample. Your progress remains while this preview is open.</p></div>}
     {activity==='judge'&&<div className="dp-judge"><div className="dp-title"><span className="dp-kicker">TWO PERSPECTIVES</span><h1>A little understanding</h1><p>No relationship scores. No taking sides.</p></div><div className="dp-sides">{['Mahmoud','Safy'].map((n,i)=><label key={n}>{n}<textarea dir="auto" value={sides[i]} onChange={e=>setSides(s=>s.map((t,j)=>j===i?e.target.value:t))}/></label>)}</div><button className="dp-primary" onClick={()=>setJudgment(true)}>Show a sample response<Sparkles size={16}/></button>{judgment&&<div className="dp-result"><small>Scripted example · not analysis of your input</small><p dir="rtl">في المثال الأصلي، طرف محتاج يعرف بدري، وطرف محتاج مساحة يقول إنه مرهق. ممكن تتفقوا على رسالة قصيرة لما الخطة تتغير، وبديل مناسب ليكم. رأي للنقاش، مش حكم نهائي.</p></div>}</div>}
    </section>
    <div className="dp-stagefooter"><span><Check size={14}/>Progress kept in this preview</span><button onClick={()=>{open('us');setUsTab('ongoing')}}><Pause size={14}/>Leave for later</button></div>
   </>}
   {view==='us'&&<section className="dp-us"><div className="dp-us-heading"><div><span className="dp-kicker">OUR LIFE / TOGETHER</span><h1>More of us.</h1><p>Things to look forward to. Things worth keeping.</p></div><button className="dp-primary" onClick={()=>setAddWish(!addWish)}><Plus size={17}/>Add a wish</button></div><nav className="dp-us-tabs" aria-label="Us collections">{[['dreams','Wishes & plans'],['ongoing','In progress'],['moments','Our moments']].map(([id,t])=><button key={id} onClick={()=>setUsTab(id)} className={usTab===id?'selected':''}>{t}</button>)}</nav>
    {addWish&&<form className="dp-addwish" onSubmit={e=>{e.preventDefault();if(wish.trim()){setWishes(w=>[...w,wish.trim()]);setWish('');setAddWish(false);setUsTab('dreams')}}}><label>A little thing you want to do together<input dir="auto" autoFocus value={wish} onChange={e=>setWish(e.target.value)} placeholder="نفسي نعمل…" required maxLength={160}/></label><button className="dp-primary">Add to our wishes</button></form>}
    {usTab==='dreams'&&<div className="dp-wishes">{wishes.map((w,i)=><button key={i} className="dp-wish" onClick={()=>{setSelectedWish(w);open('plan')}}><div className="dp-wish-top"><span>{i===0&&planning?'A PLAN IN THE MAKING':'SOMEDAY / TOGETHER'}</span><Heart size={18}/></div><h2 dir="auto">{w}</h2><p dir="rtl">{i===0?'نروح أسوان، ونسيب مساحة ليوم هادي على النيل.':i===1?'مكان هادي، سما مفتوحة، ووقت لينا.':'فكرة جديدة نكمّل تفاصيلها سوا.'}</p><div className="dp-wish-bottom"><span>{i===0?'Safy’s idea':i===1?'Our wish':'Your idea'}</span><span>{i===0&&planning?'Open plan':'Make it happen'}<ArrowRight size={16}/></span></div></button>)}</div>}
    {usTab==='ongoing'&&<div className="dp-list">{[{title:'The missing letter',next:revealed?'Completed · revisit the evidence':'Next: compare the time with the room log',a:'case'},{title:'A line between us',next:strokes.length?'Your drawing is waiting':'A blank canvas for your next idea',a:'draw'},{title:'Beyond the last door',next:'Chapter 1 · '+(chapter===0?'At the entrance':chapter===1?'The box is open':'The door is open'),a:'adventure'}].map(x=><button key={x.a} onClick={()=>choose(x.a as Activity)}><span className="dp-list-icon">{x.a==='draw'?<Pencil/>:x.a==='case'?<FileText/>:<Compass/>}</span><span><h3>{x.title}</h3><p>{x.next}</p></span><ArrowRight size={18}/></button>)}</div>}
    {usTab==='moments'&&<div className="dp-moments">{!keeps.length&&!drawingSaved?<div className="dp-empty"><Heart size={30}/><h2>Keep what matters.</h2><p>A drawing, a story, a little moment you choose.</p><button onClick={()=>choose('draw')}>Make our first drawing</button></div>:<>{drawingSaved&&<button className="dp-moment" onClick={()=>choose('draw')}><Pencil/><span><h3>Our drawing</h3><p>Created here · open to continue</p></span><ArrowRight/></button>}{keeps.map((k,i)=><article className="dp-moment" key={i}><Heart/><div><h3>{k.title}</h3><p dir="auto">{k.text}</p><small>Source: this local preview</small></div></article>)}</>}</div>}
   </section>}
   {view==='plan'&&<section className="dp-plan"><button className="dp-back" onClick={()=>open('us')}><ArrowLeft size={17}/>Wishes & plans</button><div className="dp-title"><span className="dp-kicker">FROM A WISH / TO A PLAN</span><h1 dir="auto">{selectedWish}</h1></div><div className="dp-plan-columns"><div><label>What we’re dreaming of<textarea dir="auto" value={planNote} onChange={e=>setPlanNote(e.target.value)}/></label>{planning?<div className="dp-days"><div className="dp-between"><h2>Our three days</h2><span>Editable draft</span></div>{days.map((t,i)=><label key={i}><span>DAY 0{i+1}</span><input dir="auto" value={t} onChange={e=>setDays(d=>d.map((x,j)=>i===j?e.target.value:x))}/></label>)}<p className="dp-sub">A sample outline, not researched travel advice or a booking.</p></div>:<div className="dp-plan-invite"><h2>Give the idea a little shape.</h2><p dir="rtl">نبدأ بمسودة ٣ أيام ونعدّلها سوا؟</p><button className="dp-primary" onClick={()=>setPlanning(true)}>Start a sample plan<Sparkles size={16}/></button></div>}</div><div className="dp-plan-side"><h3>Decide together</h3>{['Choose our dates','Agree on our budget'].map((t,i)=><label key={t}><input type="checkbox" checked={done[i]} onChange={()=>setDone(d=>d.map((x,j)=>i===j?!x:x))}/>{t}</label>)}<div className="dp-plan-person"><span className="dp-avatar rose">S</span><p>Safy’s idea<small>Sample contribution</small></p></div><button onClick={()=>{setChat(true);setAsk(true);addMessage('AI','العينة: أقدر أساعدكم على الخطة المفتوحة دي. الاستجابة الحقيقية تحتاج اتصال النموذج.')}}><Sparkles size={16}/>{paused?'Ask once about this':'Ask AI about this'}</button></div></div><div className="dp-actions"><button className="dp-primary" onClick={()=>{toast('Plan kept in this preview.');open('us')}}>Keep our plan<Check size={17}/></button></div></section>}
   {view==='prep'&&<section className="dp-prep"><button className="dp-back" onClick={()=>open('us')}><ArrowLeft size={16}/>Back</button><div className="dp-title"><span className="dp-kicker">PRIVATE PREP / ONLY YOU</span><h1>A little surprise.</h1><p>Share the finished thought, not the conversation behind it.</p></div><label>Your note<textarea dir="auto" value={prep} onChange={e=>{setPrep(e.target.value);setPublishPreview(false)}} placeholder="اكتب المفاجأة اللي بتحضّرها…"/></label><button className="dp-primary" disabled={!prep.trim()} onClick={()=>setPublishPreview(true)}>Preview before sharing<Eye size={17}/></button>{publishPreview&&<div className="dp-result"><span className="dp-kicker">SHARE WITH / MAHMOUD & SAFY</span><p dir="auto">{prep}</p><button className="dp-primary" onClick={()=>{setKeeps(k=>[...k,{title:'A little surprise',text:prep}]);setPrep('');setPublishPreview(false);open('us');setUsTab('moments')}}>Share this note only</button></div>}<p className="dp-sub">Privacy flow sample. This local file is not a secure private vault.</p></section>}
   </main>
   {chat&&view!=='prep'&&<aside className="dp-chat"><div className="dp-between"><h2>Conversation</h2><button className="dp-icon" onClick={()=>setChat(false)} aria-label="Close conversation"><X size={19}/></button></div><div className="dp-chat-context">{view==='plan'?selectedWish:view==='room'?activeTitle:'Our life together'}<span>{paused?'Just Us':'AI on request'}</span></div><div className="dp-messages">{messages.map((m,i)=><article className={m.who==='Mahmoud'?'me':m.who==='AI'?'ai':''} key={i}><small>{m.who}{m.who!=='Mahmoud'?' · sample':''}</small><p dir="auto">{m.text}</p></article>)}</div><form onSubmit={send}><label className="dp-chat-target">{ask?(paused?'Ask once · Just Us stays on':'To AI'):'To our room'}</label><textarea aria-label="Message" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Say something…" dir="auto" maxLength={1000}/><div className="dp-between"><button type="button" className={ask?'selected':''} onClick={()=>setAsk(!ask)}><Sparkles size={15}/>{paused?'Ask once':'Ask AI'}</button><button className="dp-primary" disabled={!message.trim()} aria-label="Send message"><Send size={16}/></button></div></form></aside>}
  </div>
  {notice&&<div className="dp-notice" role="status">{notice}<button className="dp-icon" onClick={()=>setNotice('')} aria-label="Dismiss"><X size={15}/></button></div>}
  <footer className="dp-dock"><button onClick={()=>open('prep')}><LockKeyhole size={16}/><span>Private prep</span></button><span className="dp-local">Preview · kept on this page only</span><button className={chat?'selected':''} onClick={()=>{if(view==='prep')open('room');setChat(!chat)}}><MessageCircle size={18}/><span>{chat?'Close chat':'Conversation'}</span></button></footer>
  <dialog className="dp-explore" ref={dialog} onCancel={()=>setExplore(false)} onClick={e=>{if(e.target===dialog.current)setExplore(false)}}><div className="dp-between"><div><span className="dp-kicker">EXPLORE</span><h2>What shall we do?</h2></div><button className="dp-icon" onClick={()=>setExplore(false)} aria-label="Close activity chooser"><X/></button></div><p>Pick an example. Your current progress stays here.</p><div>{activities.map(a=><button key={a.id} onClick={()=>choose(a.id)}><a.icon size={22}/><span><h3>{a.title}</h3><small>{a.description}</small></span><ArrowRight size={17}/></button>)}</div></dialog>
 </div>
}
