import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUp, ArrowLeft, ArrowRight, Check, CheckCheck, ChevronDown, CircleHelp, DoorOpen, Heart, LockKeyhole, MessageCircle, MoreHorizontal, Pause, Play, Plus, ShieldCheck, Sparkles, X} from 'lucide-react';
import './style.css';
import DesignPreview from './DesignPreview';

type Message={id:string;name:string;text:string;kind:string};
const demo=location.protocol==='file:'||new URLSearchParams(location.search).has('preview');
const sample={me:'mahmoud',members:[{id:'mahmoud',name:'Mahmoud'},{id:'safy',name:'Safy'}],version:0,pausedBy:[],aiStatus:'idle',game:null,history:[],messages:[{id:'1',name:'Safy',text:'خلصت اللي ورايا.. نلعب حاجة؟',kind:'human'},{id:'2',name:'Mahmoud',text:'جاهز 😌 بس المرة دي مفيش تساهل',kind:'human'}]};
function App(){
 const [state,setState]=useState<any>(demo?sample:null),[tab,setTab]=useState('room'),[text,setText]=useState(''),[ask,setAsk]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[rules,setRules]=useState(false),[pick,setPick]=useState<number|null>(null),[sync,setSync]=useState(demo?'Design preview':'Connecting'),[pending,setPending]=useState(false);
 const bottom=useRef<HTMLDivElement>(null); const stateRef=useRef(state);stateRef.current=state;
 const paused=!!state?.pausedBy?.length, game=state?.game, me=state?.members?.find((x:any)=>x.id===state.me), other=state?.members?.find((x:any)=>x.id!==state.me);
 async function refresh(){try{const r=await fetch('/api/snapshot',{cache:'no-store'});if(r.status===401){setState(null);setSync('Sign in');return}if(!r.ok)throw Error('Connection interrupted. Your saved progress is safe.');const d=await r.json();setState(d);setSync('Synced');}catch(e:any){setSync('Reconnecting');}}
 useEffect(()=>{if(demo)return;refresh();const f=()=>{if(!document.hidden)refresh()};const t=setInterval(f,4000);window.addEventListener('online',f);document.addEventListener('visibilitychange',f);return()=>{clearInterval(t);window.removeEventListener('online',f);document.removeEventListener('visibilitychange',f)}},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[state?.messages?.length]);
 async function command(type:string,payload:any={}){setError('');if(demo){if(type==='presence.pause'||type==='presence.resume')setState({...state,pausedBy:type==='presence.pause'?[state.me]:[]});else if(type==='game.start')setState({...state,game:{phase:'ready',round:1,rounds:3,ready:[],scores:{},submitted:[],guessed:[],id:'preview'}});else if(type==='game.ready')setState({...state,game:{...game,ready:[state.me]}});else setError('Design preview only. Live actions need the connected V2 server.');return}setBusy(true);try{const r=await fetch('/api/commands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),version:stateRef.current.version,type,payload})});const d=await r.json();if(!r.ok)throw Error(d.error||'Action could not be confirmed.');await refresh();setPick(null);return true}catch(e:any){setError(e.message);await refresh();return false}finally{setBusy(false)}}
 async function send(e:React.FormEvent){e.preventDefault();if(!text.trim()||busy)return;setPending(true);const ok=await command(ask?'ai.ask':'message.send',{text:text.trim()});if(ok){setText('');setAsk(false)}setPending(false)}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.error);setPassword('');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!state)return <main className="login"><div className="brand-mark">m<span>×</span>s</div><p className="eyebrow">MAHMOUD × SAFY</p><h1>A little space<br/>for us.</h1><form onSubmit={login}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Signing in…':'Come on in'}<ArrowRight size={18}/></button></form><p className="muted"><LockKeyhole size={14}/> Invite-only. Just your two accounts.</p>{error&&<p role="alert">{error}</p>}</main>;
 return <div className="app-shell">
 {demo&&<div className="preview-banner">Design preview · sample conversation · no live AI</div>}
 <header className="topbar"><a className="wordmark" href="#" aria-label="Our room">m<span>×</span>s</a><div className="room-title"><strong>Mahmoud <span>×</span> Safy</strong><small><LockKeyhole size={11}/> Our private room</small></div><button className="icon-button" aria-label="Sign out" onClick={async()=>{if(demo){setError('You are viewing a design preview.');return}await fetch('/api/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});setState(null)}}><DoorOpen size={20}/></button></header>
 <nav className="tabs"><button className={tab==='room'?'active':''} onClick={()=>setTab('room')}>Room</button><button className={tab==='us'?'active':''} onClick={()=>setTab('us')}>Us</button><span className="sync"><CheckCheck size={13}/>{sync}</span></nav>
 {tab==='us'?<main className="history"><p className="eyebrow">OUR LITTLE HISTORY</p><h1>The things we did.</h1>{state.history?.length?state.history.map((h:any)=><article className="result" key={h.id}><strong>Secret Match</strong><p>{h.status==='complete'?'Completed':'Ended early'}</p>{state.members.map((m:any)=><p key={m.id}>{m.name}: {h.scores[m.id]||0} points</p>)}</article>):<div className="empty"><Heart size={32}/><h2>Our story starts here.</h2><p>Finished games and their results will live here.</p></div>}</main>:<>
 <section className={'stage '+(game?'playing':'')}>
  <div className="stage-head"><span className="eyebrow">{game?'ON OUR STAGE':'OUR SPACE'}</span><button className={'presence '+(paused?'paused':'')} disabled={busy} onClick={()=>command(state.pausedBy.includes(state.me)?'presence.resume':'presence.pause')}><span className="presence-icon">{paused?<Pause size={13}/>:<Sparkles size={13}/>}</span>{paused?'Just Us':'AI is welcome'}<ChevronDown size={13}/></button></div>
  {!game?<><div className="stage-intro"><span className="tiny-star">✳</span><h1>A little room.<br/><em>All ours.</em></h1><p>Pick up wherever we left off.</p></div><button className="game-invite" onClick={()=>{setRules(true)}}><span className="tile-icon"><LockKeyhole size={23}/></span><span><strong>Secret Match</strong><small>Two secrets. A little intuition.</small></span><ArrowUp size={20} className="diagonal"/></button></>:<div className="game-body"><div className="game-meta"><span>SECRET MATCH</span><span>Round {game.round} / {game.rounds}</span></div><h1>{game.phase==='ready'?'Both ready?':game.phase==='secrets'?'Keep a little secret.':game.phase==='guesses'?'Trust your intuition.':game.phase==='complete'?'That was us.':'The reveal.'}</h1><p>{game.phase==='ready'?'Choose a number. Guess theirs. Three rounds.':game.phase==='secrets'?'Choose a number from 1 to 10. Only you can see it until the reveal.':game.phase==='guesses'?`What number did ${other?.name} choose?`:'Exact match: 3 points. One away: 1 point.'}</p>
  {game.phase==='ready'&&<button className="primary" disabled={busy||game.ready.includes(state.me)} onClick={()=>command('game.ready')}>{game.ready.includes(state.me)?`Waiting for ${other?.name}…`:"I'm ready"}<Check size={17}/></button>}
  {['secrets','guesses'].includes(game.phase)&&<>{(game.phase==='secrets'?game.submitted:game.guessed).includes(state.me)?<div className="sealed"><LockKeyhole size={23}/><strong>Safely sealed.</strong><span>Waiting for {other?.name}.</span></div>:<><div className="number-grid">{Array.from({length:10},(_,i)=>i+1).map(n=><button key={n} className={pick===n?'selected':''} onClick={()=>setPick(n)}>{n}</button>)}</div><button className="primary" disabled={!pick||busy} onClick={()=>command(game.phase==='secrets'?'game.secret':'game.guess',{number:pick})}>Lock {game.phase==='secrets'?'my number':'my guess'}<LockKeyhole size={16}/></button></>}</>}
  {['reveal','complete'].includes(game.phase)&&<><div className="reveal-grid">{state.members.map((m:any)=><div key={m.id}><small>{m.name}</small><strong>{game.reveal?.secrets?.[m.id]}</strong><span>Guessed {game.reveal?.guesses?.[m.id]} · +{game.reveal?.points?.[m.id]||0}</span><b>{game.scores[m.id]||0} total</b></div>)}</div><button className="primary" disabled={busy||game.ready.includes(state.me)} onClick={()=>command(game.phase==='complete'?'game.finish':'game.next')}>{game.phase==='complete'?'Back to our room':game.ready.includes(state.me)?'Waiting for the next round…':'Next round'}<ArrowRight size={17}/></button></>}
  {!['complete'].includes(game.phase)&&<button className="quiet-button" disabled={busy} onClick={()=>{if(confirm('End this game? It will be saved as ended early, with no winner.'))command('game.abandon')}}>End game</button>}</div>}
 </section>
 <section className="conversation" aria-label="Conversation"><div className="conversation-label"><span>THE CONVERSATION</span><span>Today</span></div><div className="messages">{state.messages.map((m:Message)=><article key={m.id} className={'message '+(m.name===me?.name?'mine':'')+' '+(m.kind==='ai'?'ai':'')}><div className="avatar">{m.kind==='ai'?<Sparkles size={16}/>:m.name.slice(0,1)}</div><div className="message-content"><small>{m.name}</small><p dir="auto">{m.text}</p>{m.kind==='ai'&&<button className="reply" onClick={()=>setAsk(true)}>Reply to AI</button>}</div></article>)}{state.aiStatus==='working'&&<p className="ai-working"><Sparkles size={15}/> Thinking it through…</p>}<div ref={bottom}/></div></section>
 <footer className="composer-area">{paused&&<p className="pause-note"><Pause size={12}/> AI is quiet. {state.pausedBy.includes(state.me)?'You can resume your permission above.':'Your partner has asked for Just Us.'}</p>}{error&&<p className="error" role="alert">{error}<button aria-label="Dismiss" onClick={()=>setError('')}><X size={14}/></button></p>}<form onSubmit={send}><div className="composer"><button type="button" className={'ask-toggle '+(ask?'on':'')} aria-label={ask?'Send to room instead':'Ask AI'} title="Ask AI" onClick={()=>setAsk(!ask)}><Sparkles size={21}/></button><input aria-label="Message" value={text} maxLength={4000} onChange={e=>setText(e.target.value)} placeholder={ask?(paused?'Ask once. Just Us stays on.':'Ask our AI…'):'Say something…'} dir="auto"/><button type="submit" className="send" disabled={!text.trim()||busy} aria-label="Send"><ArrowUp size={21}/></button></div><div className="composer-meta"><span>{ask?'To AI · request and allowed context only':'To our room'}</span><span>{pending?'Sending…':<><LockKeyhole size={11}/> Just us, in here.</>}</span></div></form></footer>
 </>}
 {rules&&<div className="modal-backdrop" onClick={()=>setRules(false)}><section role="dialog" aria-modal="true" aria-label="Secret Match rules" className="rules" onClick={e=>e.stopPropagation()}><button className="close icon-button" aria-label="Close" onClick={()=>setRules(false)}><X/></button><div className="tile-icon"><LockKeyhole size={24}/></div><p className="eyebrow">A GAME FOR TWO</p><h2>Secret Match</h2><p>Each of you secretly chooses a number from 1 to 10, then guesses the other person's number.</p><div className="rule-row"><span>Exact guess</span><b>3 points</b></div><div className="rule-row"><span>One number away</span><b>1 point</b></div><div className="rule-row"><span>Three rounds</span><b>Both ready to begin</b></div><p className="muted">Secrets reveal together, after both guesses. You can leave and continue later.</p><button className="primary" disabled={busy} onClick={async()=>{setRules(false);await command('game.start')}}>Bring it to our stage<ArrowRight size={17}/></button></section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(demo?<DesignPreview/>:<App/>);
