import React,{useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Bookmark,Check,ChevronRight,Compass,Heart,LockKeyhole,MessageCircle,Pencil,Plus,Sparkles,X} from 'lucide-react';
export type ActivityKind='case'|'draw'|'secret'|'story'|'perspectives';
export type Moment={title:string;detail:string;image?:string;kind?:ActivityKind;id:string};
export type Ongoing={kind:ActivityKind;title:string;detail:string;status:'Active'|'Paused'|'Completed'};
type Wish={id:string;title:string;note:string;steps:{text:string;done:boolean}[];owner:string};
const initial:Wish[]=[{id:'aswan',title:'Aswan, together',note:'A slow morning by the Nile. No packed schedule — just time for us.',owner:'Safy',steps:[{text:'Choose a weekend that works for both of us',done:false},{text:'Agree on a comfortable budget',done:false},{text:'Pick one place we would love to see',done:false}]},{id:'stars',title:'A night under the stars',note:'Find a quiet place, bring something warm, and watch the sky.',owner:'Both of us',steps:[{text:'Choose a place away from city lights',done:false},{text:'Check the weather before we go',done:false},{text:'Pack a blanket and our favourite snacks',done:false}]}];
export default function UsWorkspace({moments,ongoing,onResume,onAsk,onExplore,tab,setTab}:{moments:Moment[];ongoing:Ongoing[];onResume:(k:ActivityKind)=>void;onAsk:(title:string,note:string)=>void;onExplore:()=>void;tab:'plans'|'ongoing'|'moments';setTab:(t:'plans'|'ongoing'|'moments')=>void}){
 const [wishes,setWishes]=useState(initial),[selected,setSelected]=useState<string|null>(null),[adding,setAdding]=useState(false),[newTitle,setNewTitle]=useState('');
 useEffect(()=>{if(tab!=='plans')setSelected(null)},[tab]);
 const wish=wishes.find(w=>w.id===selected);
 function update(p:Partial<Wish>){setWishes(ws=>ws.map(w=>w.id===selected?{...w,...p}:w))}
 return <section className="us-page" aria-label="Us workspace">{wish?<><button className="us-back" onClick={()=>setSelected(null)}><ArrowLeft size={17}/>All wishes</button><div className="us-detail-title"><span className="rs-eyebrow">A WISH BECOMING REAL</span><h2 dir="auto">{wish.title}</h2><span className="us-byline">{wish.owner==='Both of us'?'Our idea':wish.owner+'’s idea'} · edited together</span></div><div className="us-detail-grid"><div><label className="us-field">The idea<textarea value={wish.note} dir="auto" onChange={e=>update({note:e.target.value})}/></label><div className="us-section-head"><h3>Our next steps</h3><span>{wish.steps.filter(s=>s.done).length} of {wish.steps.length} done</span></div><div className="us-steps">{wish.steps.map((s,i)=><div key={i}><input type="checkbox" aria-label={'Complete step '+(i+1)} checked={s.done} onChange={()=>update({steps:wish.steps.map((a,j)=>i===j?{...a,done:!a.done}:a)})}/><input aria-label={'Plan step '+(i+1)} value={s.text} dir="auto" onChange={e=>update({steps:wish.steps.map((a,j)=>j===i?{...a,text:e.target.value}:a)})}/></div>)}</div><button className="us-text-button" onClick={()=>update({steps:[...wish.steps,{text:'',done:false}]})}><Plus size={16}/>Add a step</button></div><aside className="us-plan-aside"><Heart size={22}/><h3>A little closer.</h3><p>Keep the plan small enough to actually do together.</p><button onClick={()=>onAsk(wish.title,wish.note)}><Sparkles size={16}/>Discuss with AI in Room</button><small>One demo reply. Just Us stays as it is.</small></aside></div><div className="us-plan-foot"><span><Check size={15}/>Changes kept while this preview is open</span><button className="rs-primary" onClick={()=>setSelected(null)}>Back to our wishes<ArrowUpRight size={16}/></button></div></>:<><div className="us-intro"><div><span className="rs-eyebrow">OUR LIFE, TOGETHER</span><h2>More than a conversation.</h2><p>What we dream of. What we make. What we keep.</p></div><button className="us-add" onClick={()=>{setAdding(!adding);setTab('plans')}}><Plus size={17}/>Add a wish</button></div><nav className="us-tabs" aria-label="Us collections">{([['plans','Wishes & plans'],['ongoing','Continue'],['moments','Moments']] as const).map(([id,label])=><button className={id===tab?'selected':''} aria-current={id===tab?'page':undefined} key={id} onClick={()=>setTab(id)}>{label}{id==='ongoing'&&ongoing.filter(a=>a.status!=='Completed').length>0&&<span>{ongoing.filter(a=>a.status!=='Completed').length}</span>}{id==='moments'&&moments.length>0&&<span>{moments.length}</span>}</button>)}</nav>
 {adding&&tab==='plans'&&<form className="us-new-wish" onSubmit={e=>{e.preventDefault();if(newTitle.trim()){const id='wish-'+Date.now();setWishes(w=>[...w,{id,title:newTitle.trim(),note:'',owner:'Mahmoud',steps:[]}]);setNewTitle('');setAdding(false);setSelected(id)}}}><label>Something you want to do together<input aria-label="New wish" placeholder="A place, an idea, a little adventure…" value={newTitle} onChange={e=>setNewTitle(e.target.value)} maxLength={150} required/></label><div><button className="rs-primary">Create wish</button><button type="button" onClick={()=>setAdding(false)}>Cancel</button></div></form>}
 {tab==='plans'&&<div className="us-wishes">{wishes.map((w,i)=><button className={'us-wish '+(i%2?'rose':'gold')} key={w.id} onClick={()=>setSelected(w.id)}><span className="us-wish-heading"><span>{w.owner==='Both of us'?'Our idea':w.owner+'’s idea'}</span><Heart size={18}/></span><h3 dir="auto">{w.title}</h3><p dir="auto">{w.note||'A new idea, with room to grow.'}</p><span className="us-wish-footer"><span>{w.steps.length?w.steps.filter(s=>s.done).length+' / '+w.steps.length+' steps':'Start a plan'}</span><ArrowUpRight size={20}/></span></button>)}</div>}
 {tab==='ongoing'&&<div className="us-ongoing">{ongoing.filter(a=>a.status!=='Completed').length?ongoing.filter(a=>a.status!=='Completed').map(a=><button key={a.kind} className="us-progress-item" onClick={()=>onResume(a.kind)}><span className="us-progress-icon">{a.kind==='draw'?<Pencil size={23}/>:<Compass size={23}/>}</span><span><small>{a.status}</small><h3>{a.title}</h3><p>{a.detail}</p></span><ArrowUpRight size={21}/></button>):<div className="us-empty"><Compass size={30}/><h3>A pause is not the end.</h3><p>Your unfinished activities will wait here.</p><button onClick={onExplore}>Explore something together</button></div>}{ongoing.some(a=>a.status==='Completed')&&<div className="us-completed"><h3>Completed</h3>{ongoing.filter(a=>a.status==='Completed').map(a=><button key={a.kind} onClick={()=>onResume(a.kind)}><Check size={17}/><span>{a.title}</span><span>Review<ChevronRight size={15}/></span></button>)}</div>}</div>}
 {tab==='moments'&&<div className="us-moments">{moments.length?moments.map(m=><article key={m.id} className="us-moment">{m.image?<img src={m.image} alt="Your saved drawing"/>:<span className="us-moment-icon"><Bookmark size={23}/></span>}<div><small>{m.kind==='draw'?'A creation':m.kind?'An experience':'A shared note'}</small><h3>{m.title}</h3><p dir="auto">{m.detail}</p><span className="us-source">Source: this preview session</span>{m.kind&&<button onClick={()=>onResume(m.kind!)}>{m.kind==='draw'?'Continue creating':'Revisit experience'}<ArrowUpRight size={16}/></button>}</div></article>):<div className="us-empty"><Bookmark size={30}/><h3>Keep what matters.</h3><p>Save a drawing, a finished game, or a note you choose to share.</p><button onClick={onExplore}>Make a moment</button></div>}</div>}
 </>}</section>
}
export function PrivatePrep({onShare,onBack}:{onShare:(text:string)=>void;onBack:()=>void}){
 const [notes,setNotes]=useState(''),[output,setOutput]=useState(''),[preview,setPreview]=useState(false),[sent,setSent]=useState(false);
 return <section className="us-page pp-page" aria-label="Private preparation"><button className="us-back" onClick={onBack}><ArrowLeft size={16}/>Back to Room</button><div className="us-detail-title"><span className="rs-eyebrow"><LockKeyhole size={13}/> PRIVATE PREP</span><h2>Something just for you.</h2><p>Prepare quietly. Share only the part you choose.</p></div><div className="pp-grid"><label className="us-field">Private working notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Your thoughts, plans, unfinished ideas…" dir="auto"/><small>These notes are never copied into Room by the share action.</small></label><div><label className="us-field">The note you want to share<textarea value={output} onChange={e=>{setOutput(e.target.value);setPreview(false);setSent(false)}} placeholder="Write only what Safy should see…" dir="auto"/></label><button className="rs-primary" disabled={!output.trim()} onClick={()=>setPreview(true)}>Review before sharing<ArrowUpRight size={16}/></button></div></div>{preview&&<div className="pp-review"><span className="rs-eyebrow">SHARE WITH MAHMOUD & SAFY</span><p dir="auto">{output}</p><div><button className="rs-primary" onClick={()=>{onShare(output.trim());setPreview(false);setSent(true);setOutput('')}}>Share this note only<Check size={16}/></button><button onClick={()=>setPreview(false)}>Keep editing</button></div></div>}{sent&&<div className="pp-confirm" role="status"><Check size={17}/>Shared in Room and saved in Us. Your working notes stayed here.</div>}<p className="pp-local">Privacy flow demonstration. This local preview is not a secure vault; all data resets on reload.</p></section>
}
